image:
  file: .gitpod.Dockerfile

tasks:
  - name: Autopilot
    init: |
      bash scripts/gp-autopilot.sh --prepare
    command: |
      bash scripts/gp-autopilot.sh --run

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 4173
    onOpen: ignore
    visibility: public
  - port: 3000
    visibility: public
  - port: 54321
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - ms-playwright.playwright
