# Elevate for Humanity - Gitpod Development Environment
# Simplified configuration for reliable Node.js + Next.js development

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
    name: Next.js Dev Server
    description: "Marketing + LMS Platform"
  - port: 5432
    onOpen: ignore
    visibility: private
    name: PostgreSQL
  - port: 54321
    onOpen: ignore
    visibility: private
    name: Supabase Studio

tasks:
  - name: Setup & Dev Server
    init: |
      # Verify Node.js is available
      echo "🔍 Checking Node.js..."
      node -v
      npm -v
      
      # Enable pnpm
      echo "📦 Setting up pnpm..."
      corepack enable
      corepack prepare pnpm@latest --activate
      
      # Install dependencies
      echo "📦 Installing dependencies..."
      pnpm install
      
      # Make scripts executable
      chmod +x setup-env.sh 2>/dev/null || true
      
      # Setup environment variables
      if [ ! -f .env.local ]; then
        echo ""
        echo "🔧 Setting up environment variables..."
        if [ -n "$VERCEL_TOKEN" ]; then
          echo "✅ VERCEL_TOKEN found - pulling from Vercel..."
          ./setup-env.sh || echo "⚠️  Setup failed, continuing anyway..."
        else
          echo "⚠️  .env.local not found and VERCEL_TOKEN not set"
          echo ""
          echo "To set up automatically:"
          echo "  1. Get Vercel token: https://vercel.com/account/tokens"
          echo "  2. Set it: gp env VERCEL_TOKEN='your-token'"
          echo "  3. Restart workspace or run: ./setup-env.sh"
          echo ""
          echo "Or manually: cp .env.example .env.local"
        fi
      else
        echo "✅ .env.local already exists"
      fi
      
      echo ""
      echo "✅ Setup complete!"
      
    command: |
      # Wait a moment for init to complete
      sleep 2
      
      # Check if .env.local exists
      if [ ! -f .env.local ]; then
        echo "⚠️  .env.local not found - creating from example..."
        cp .env.example .env.local
        echo ""
        echo "📝 Please edit .env.local with your credentials"
        echo "   Then run: pnpm dev"
        echo ""
      else
        echo "🚀 Starting development server..."
        pnpm dev
      fi

vscode:
  extensions:
    # Essential
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    
    # TypeScript
    - ms-vscode.vscode-typescript-next
    
    # Git
    - eamodio.gitlens
    - github.vscode-pull-request-github
    
    # Utilities
    - christian-kohler.path-intellisense
    - yzhang.markdown-all-in-one
    
    # Database
    - cweijan.vscode-postgresql-client2

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
