# Elevate for Humanity - Gitpod Configuration
# Professional LMS development environment

image:
  file: .gitpod.Dockerfile

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public
    name: Vite Dev Server
    description: EFH LMS Development Server
  - port: 8080
    onOpen: open-preview
    visibility: public
    name: Vite Preview Server
    description: Production Build Preview
  - port: 4173
    onOpen: ignore
    visibility: public
    name: Vite Preview (Alt)
    description: Alternative Preview Port
  - port: 7070
    onOpen: ignore
    visibility: public
    name: Backend API
    description: Python FastAPI Backend
  - port: 3000
    onOpen: ignore
    visibility: private

tasks:
  - name: LMS UX & Compliance Benchmark
    init: |
      mkdir -p docs
      
      cat << 'EOF' > docs/lms-benchmark-checklist.md
# LMS Benchmark Checklist (Absorb / Docebo / TalentLMS → Elevate)

Goal: Use the best parts of leading LMS platforms to refine **Elevate** so it feels:
- Enterprise-grade and visually polished
- Easy for adult learners and partners
- Clearly aligned with **DOL, DWD, WorkOne, EmployIndy** and other workforce boards
- Ready for apprenticeships, WIOA/ETPL, WRG, JRI, WEX/OJT, and DOL-registered programs

---

## 1. Reference LMS Platforms & URLs

### 1.1 Absorb LMS
- **Home / Product**:  
  - https://www.absorblms.com/  
  - https://www.absorblms.com/products/learning-management-system
- Focus: AI-powered, enterprise LMS with strong integrations and compliance training positioning.

### 1.2 Docebo
- **Home / Platform**:  
  - https://www.docebo.com/  
  - https://www.docebo.com/learning-platform/
- Focus: AI-first learning platform for employees, partners, customers; heavy on automation, impact, and compliance.

### 1.3 TalentLMS
- **Home / Platform**:  
  - https://www.talentlms.com/  
  - https://www.talentlms.com/platform  
  - https://www.talentlms.com/features
- Focus: Simple, cloud LMS; fast setup; strong for compliance, blended learning, and mobile.

(You may optionally also glance at 1–2 "Top LMS lists" for quick inspiration on wording and layout.)

---

## 2. What to Compare Visually (Design & Layout)

### 2.1 Hero section (top of homepage)
For each vendor, capture:

- **Headline style** (short, benefit-driven, not technical)
- **Sub-headline** (who it helps: employees, partners, customers, schools)
- **Primary CTA buttons** (e.g., "Get a demo", "Start free", "Talk to sales")
- **Hero visuals** (screenshots, people, dashboards, icons)

> ✏️ **Action for Elevate:**  
> Rewrite Elevate's hero to:
> - State clearly: "Workforce training & apprenticeships for [city/region]."
> - Call out: DOL-registered apprenticeships, ETPL/WRG/WorkOne alignment.
> - Include 1–2 CTAs: "Apply as a Student" and "Partner With Elevate".

---

### 2.2 Navigation menu & page structure

Document how each LMS structures the top menu:

- Common sections (e.g., Solutions, Products, Customers, Resources, Pricing)
- Where they put **"Compliance" / "Industries" / "Use Cases"**
- How they highlight **demo / trial / contact** links

> ✏️ **Action for Elevate:**
> - Create or refine top-nav groups such as:
>   - **Programs** (HVAC, Barber, CNA, Apprenticeships, etc.)
>   - **For Agencies** (WorkOne, EmployIndy, DWD partners)
>   - **For Employers** (OJT, WEX, Apprenticeship Sponsors)
>   - **About / Impact** (ETPL approvals, WRG, JRI, Success Stories)
>   - **Portals** (Student Login, Partner Portal, Employer Portal)

---

### 2.3 Section layout & visual rhythm

For each vendor, note:

- How they break the page into **horizontal bands** (hero, benefits, features, use-cases, logos, testimonials)
- Use of **icons, screenshots, cards** to visually group content
- Consistency in spacing, fonts, and color usage

> ✏️ **Action for Elevate:**
> - Rebuild long walls of text into:
>   - 3-column benefit sections
>   - Feature cards with icons
>   - "How it works" steps (1-2-3)
>   - Logos of partners (WorkOne, EmployIndy, training partners) for credibility

---

## 3. Functional Positioning (What They Say Their LMS *Does*)

### 3.1 Key feature themes to copy/adapt

From Absorb / Docebo / TalentLMS, list phrases and ideas around:

- **Compliance training & tracking**
- **Onboarding & upskilling**
- **Multi-audience training** (employees, partners, customers, members)
- **Analytics & reporting**
- **Integrations & automation**
- **Mobile learning**

> ✏️ **Action for Elevate:**
> Create a "What Elevate Delivers" section that maps to your reality:
> - **Workforce-ready programs**: HVAC, Barber, CNA, Building Tech, CDL, etc.
> - **Compliance & reporting**:
>   - Aligned to **DOL, DWD, WorkOne, EmployIndy**
>   - ETPL & WRG reporting exports
>   - Attendance / hours / apprenticeship logs
> - **Multi-audience support**:
>   - Jobseekers & students
>   - Employers & apprenticeship sponsors
>   - Workforce boards & referring agencies
> - **Automation & integrations** (brief call-out to your LMS + portals)

---

## 4. Compliance & Workforce Language

Study how these platforms talk about:

- "Compliance training" and "risk reduction"
- "Regulation", "standards", "certifications"
- Industry-specific compliance (e.g., financial, healthcare)

> ✏️ **Action for Elevate (rewrite ideas):**
> - Add a dedicated **"Compliance & Workforce Partners"** page/section:
>   - Explain alignment with:
>     - **U.S. Department of Labor (DOL)**
>     - **Indiana Department of Workforce Development (DWD)**
>     - **WorkOne**, **EmployIndy**, and local workforce boards
>   - Mention:
>     - WIOA-aligned programs
>     - ETPL-approved training
>     - WRG, JRI, WEX, OJT, and DOL-registered apprenticeships
>   - Include bullets on:
>     - Standardized reporting
>     - Document storage (MOUs, training plans)
>     - Secure handling of participant data

---

## 5. Flows to Sketch for Elevate

For each LMS, quickly walk through:

- How a **new prospect** requests a demo / signs up
- How clearly they explain **"Who it's for"**
- What the **student/learner journey** page looks like (if shown)
- Any example **dashboards or portals** in screenshots

> ✏️ **Action for Elevate:**  
> Make wireframe notes (even simple bullets) for:
> - **Student Journey**:
>   - Discover program → Eligibility check → Apply → Orientation → Training → Certification → Job placement
> - **Agency / WorkOne Journey**:
>   - Refer a client → Track their status → Download reports for audits
> - **Employer Journey**:
>   - Request apprentices → Sign OJT/WEX agreements → View candidate progress → Hire

---

## 6. Deliverables for the Dev/Design Team

When you're done reviewing Absorb, Docebo, and TalentLMS:

1. Fill in this checklist with concrete notes & screenshots.
2. Create a new document: `docs/elevate-lms-ux-plan.md` summarizing:
   - Top 5 design improvements to make Elevate feel like a top LMS.
   - Top 5 content/wording changes for workforce compliance alignment.
   - Navigation changes recommended (and why).
   - Any ideas for dashboards / portals borrowed from these LMSs.
3. Tag items as:
   - **P0**: Must fix before onboarding partners & students
   - **P1**: Important, but can launch without them
   - **P2**: Nice futures (animations, extra dashboards, etc.)

EOF

      cat << 'EOF' > docs/elevate-lms-ux-plan.md
# Elevate LMS – UX, Design & Compliance Upgrade Plan
### Benchmark References: Absorb LMS, Docebo, TalentLMS

## 🔥 Purpose of This Document
This plan outlines how Elevate's LMS should:
- Look polished and enterprise-grade  
- Function like industry-leading LMS platforms (Absorb, Docebo, TalentLMS)  
- Communicate compliance clearly (DOL, DWD, WorkOne, EmployIndy, ETPL, WRG, WEX/OJT, JRI, Apprenticeships)  
- Support students, partners, employers, and workforce agencies  
- Be onboarding-ready for real students today  

---

# 1. Visual Design Direction (Modeled After Absorb, Docebo, TalentLMS)

## 1.1 Hero Section Style
**What we observed from benchmark LMS platforms:**
- Big bold headline with a clear benefit  
- Subheadline explaining who it helps (schools, employers, workforce agencies)  
- Clean CTA buttons  
- Screenshot/dashboard mockups  

**Action for Elevate:**
- Headline: "Workforce Training & Apprenticeships That Transform Communities"  
- Subheadline: "DOL & DWD-aligned training for students, employers, and workforce partners."  
- CTA buttons:
  - "Apply as a Student"
  - "Become a Workforce Partner"
- Replace cartoonish images with real photos or dashboard mockups
- Add a polished hero background gradient or subtle animated particles

---

# 2. Navigation Structure (Lifted From Absorb, Docebo, TalentLMS)

## 2.1 Recommended Menu Layout
**Programs**
- HVAC  
- Barber Apprenticeship  
- CNA  
- CDL  
- Building Maintenance  
- All Programs  

**For Agencies**
- WorkOne Partnership  
- EmployIndy Referral Hub  
- ETPL & WRG Compliance  
- Employer OJT/WEX Portal  
- Apprenticeship Logs  

**For Students**
- Student Portal  
- Apply Now  
- FAQs  

**For Employers**
- Host Apprentices  
- OJT/WEX  
- Talent Pipeline Services  

**About**
- Approvals  
- Workforce Impact  
- Leadership  
- Contact  

---

# 3. Homepage Sections (Modeled After Enterprise LMS)

## 3.1 "Who We Help" Section
**Modeled after Docebo & Absorb**

Three cards:
- **Students** – Hands-on job training, certifications, apprenticeships  
- **Employers** – Skilled talent pipeline, subsidized training  
- **Agencies** – ETPL, WRG, WIOA, JRI, and Apprenticeship compliance  

## 3.2 "How Elevate Works" (Step-by-Step)
Use a 3-step horizontal process like TalentLMS:

1. **Enroll**
2. **Train**
3. **Get Certified & Employed**

## 3.3 "Approved & Aligned" Section
Logos row:
- DOL  
- DWD Indiana  
- WorkOne  
- EmployIndy  
- National Apprenticeship  
- ETPL Provider  

Include short bullets:
- ETPL-approved  
- DOL-registered Barber Apprenticeship  
- WRG & JRI Eligible  
- CNA licensed by IDOH (if applicable)  

---

# 4. Program Page Template (For ALL Programs)

Each program page should mirror enterprise LMS pages:

## 4.1 Program Overview
- High-quality photo  
- Short program summary  
- Learning outcomes  

## 4.2 Compliance Alignment
- ETPL  
- WRG  
- DOL Apprenticeship (if applicable)  
- WorkOne referral ready  
- Hours tracking & logs  

## 4.3 What Students Will Learn
Use checkmark columns:
- Hands-on modules  
- Industry certifications  
- Safety  
- Job placement assistance  

## 4.4 Enrollment Requirements
Easy bullets like:
- 18+  
- Indiana resident (if required)  
- Background check  
- Valid ID  

## 4.5 Career Outcomes
Tiles of jobs:
- HVAC Technician  
- CNA  
- Apprentice Barber  
- CDL Driver  
- Building Technician  

---

# 5. Workforce Compliance Messaging (VERY IMPORTANT)

## 5.1 Build a Dedicated Section Called:
### **"Workforce Compliance & Agency Partners"**

## 5.2 Include bullet-proof language:
- Fully aligned to **DOL Registered Apprenticeships**  
- Listed on **Indiana ETPL**  
- Eligible for **WRG, JRI, WEX, OJT**  
- Workforce agency reporting exports included  
- Time/attendance logs for audits  
- Secure document vault for MOUs & agreements  

This should sound EXACTLY like an enterprise compliance provider.

---

# 6. Portals & Dashboard Structure

## 6.1 Student Portal
- Training progress  
- Hours logs  
- Certifications  
- Orientation  
- Messages  

## 6.2 Employer Portal
- View apprentices  
- Approve hours  
- Submit WEX/OJT documents  
- Hire candidates  

## 6.3 Agency Portal (WorkOne / EmployIndy)
- Refer clients  
- Track progress  
- Download reports  
- Request status updates  

---

# 7. Messaging & Copywriting (Lift Phrases From LMS Leaders)

Use phrases like:

- "Skills that lead to employment."  
- "Data-driven workforce outcomes."  
- "Training aligned to state standards."  
- "A modern learning experience for adult learners."  
- "Compliance-first design."  
- "Tailored for workforce agencies and employers."  
- "From enrollment to employment."  

---

# 8. UI/UX Enhancements to Implement Immediately

Inspired by: Absorb / Docebo / TalentLMS

- Remove cartoonish images  
- Add high-quality stock or AI images  
- Convert long text into "cards"  
- Add micro animations (fade, slide, hover)  
- Clean spacing (consistent 40px–60px padding sections)  
- Add iconography (SVG only)  
- Color palette simplified (2 primaries + 1 accent)  
- Replace heavy blocks with 3-column layouts  
- Consistent headline style (H1: bold, H2: medium, H3: thin)  

---

# 9. Compliance-Ready Structure for Workforce Boards

## Must Include:
- Program code  
- CIP code  
- Credentials issued  
- Hours  
- Modality  
- Approvals documented  
- Employer partners  
- DOL apprenticeship number (if applicable)  
- ETPL listing link  
- Partner school (Choice Medical, Kenny's Barber Academy, etc.)  

---

# 10. Launch Readiness Score (Team Fills In)

Rate each from 0–100%:

- UI polish  
- Program pages completeness  
- Compliance pages  
- Student portal  
- Employer portal  
- Agency portal  
- Mobile optimization  
- Performance  
- SEO  
- Accessibility  
- LMS functionality  
- Workforce compliance mapping  

Then provide:  
**Overall: ONBOARDING-READY? YES / NO**

---

# 11. Priority List (P0 / P1 / P2)

- **P0 (Today)**  
  - Homepage redesign  
  - Program pages polished  
  - Compliance section uploaded  
  - Student apply funnel fixed  

- **P1 (Next 48 hours)**  
  - Employer portal  
  - Agency portal  
  - Workforce dashboards  

- **P2 (Next 7–14 days)**  
  - Animations  
  - Partner success stories  
  - Full LMS documentation  

---

# 12. Deliverables Checklist

- [ ] Homepage rewired  
- [ ] All images replaced (no cartoons)  
- [ ] All program pages updated  
- [ ] Compliance page live  
- [ ] Portals linked  
- [ ] Workforce agency language added  
- [ ] Navigation cleaned  
- [ ] CTA buttons added  
- [ ] Dashboards/screenshots inserted  

---

# END OF DOCUMENT
EOF

      echo "✅ Created docs/lms-benchmark-checklist.md"
      echo "✅ Created docs/elevate-lms-ux-plan.md"
      echo ""
      echo "📚 LMS Benchmark Documentation Ready:"
      echo "   - docs/lms-benchmark-checklist.md (Review Absorb, Docebo, TalentLMS)"
      echo "   - docs/elevate-lms-ux-plan.md (Implementation plan skeleton)"
      echo ""

  - name: Setup Elevate Script Pack & Seeds
    init: |
      echo "🎓 Welcome to Elevate for Humanity LMS Development"
      echo ""
      mkdir -p scripts docs seeds
      echo ""
      echo "🔧 Setting up environment..."
      chmod +x scripts/auto-setup-env.sh || true
      ./scripts/auto-setup-env.sh || echo "⚠️  Environment setup needed - run: bash scripts/setup-env.sh"
      echo ""
      echo "📚 Generating Elevate Script Pack..."
      chmod +x scripts/bootstrap-elevate-scripts.sh || true
      ./scripts/bootstrap-elevate-scripts.sh || echo "Run scripts/bootstrap-elevate-scripts.sh manually if needed."
      echo ""
      echo "🌱 Generating Content Seeds..."
      chmod +x scripts/generate-elevate-seeds.sh || true
      ./scripts/generate-elevate-seeds.sh || echo "Run scripts/generate-elevate-seeds.sh manually if needed."
      echo ""
      echo "📘 Generating Digital Package..."
      chmod +x scripts/generate-elevate-digital.sh || true
      ./scripts/generate-elevate-digital.sh || echo "Run scripts/generate-elevate-digital.sh manually if needed."
      echo ""
      bash scripts/setup.sh || echo "Setup script not found, continuing..."
      echo ""
      echo "🎨 Generating course covers..."
      node scripts/generate-course-covers.mjs || echo "Course cover generation skipped"
    command: |
      echo ""
      echo "✅ Workspace ready!"
      echo ""
      echo "📚 Script Pack: docs/Elevate_Script_Pack.md"
      echo "🔗 Quick Start: QUICK_START.md"
      echo "📞 Phone: (317) 314-3757"
      echo ""
      echo "📚 Quick Start:"
      echo "   npm run dev       - Start dev server"
      echo "   npm run build     - Build for production"
      echo "   npm run typecheck - Check TypeScript"
      echo "   npm run lint      - Run ESLint"
      echo ""
      echo "🔧 Utility Scripts:"
      echo "   bash scripts/verify-env.sh      - Check environment variables"
      echo "   bash scripts/test.sh            - Run all checks"
      echo "   bash scripts/netlify-preview.sh - Deploy preview"
      echo "   npm run generate-covers         - Regenerate course covers"
      echo ""
      echo "🚀 Starting dev server..."
      npm run dev || bash scripts/dev.sh || echo "Start server with: npm run dev"

  - name: Elevate Autopilot
    init: |
      chmod +x elevate-one-shot.sh || true
      chmod +x scripts/elevate-autopilot.sh || true
      chmod +x scripts/fix-everything-now.sh || true
    command: |
      echo "🚀 Elevate Autopilot Ready"
      echo ""
      echo "Run complete implementation:"
      echo "  ./elevate-one-shot.sh"
      echo ""
      echo "Or run specific fixes:"
      echo "  ./scripts/fix-everything-now.sh"
      echo "  ./scripts/elevate-autopilot.sh"
      echo ""
      gp sync-done vercel-check

  - name: Backend (Optional)
    command: |
      gp sync-await vercel-check
      if [ -d backend ] && [ -f backend/requirements.txt ]; then
        echo "🐍 Starting Python backend..."
        cd backend
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        uvicorn main:app --reload --host 0.0.0.0 --port 7070
      else
        echo "ℹ️  No backend directory found - frontend only mode"
        echo "   Backend API not required for basic LMS functionality"
      fi

vscode:
  extensions:
    # Essential
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss

    # TypeScript & React
    - ms-vscode.vscode-typescript-next
    - dsznajder.es7-react-js-snippets

    # Utilities
    - christian-kohler.path-intellisense
    - formulahendry.auto-rename-tag
    - naumovs.color-highlight

    # Git
    - eamodio.gitlens

    # Optional but helpful
    - usernamehw.errorlens
    - streetsidesoftware.code-spell-checker

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false
