tasks:
  - name: Frontend
    command: pnpm install && pnpm dev
  - name: Backend
    command: cd backend && python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --host 0.0.0.0 --port 7070
ports:
  - port: 5173
    visibility: public
  - port: 7070
    visibility: public
