# Gitpod Configuration
# Elevate for Humanity - Workforce Development Platform

# Use Gitpod's universal image with all development tools
image: gitpod/workspace-full:latest

# Tasks to run on workspace start
tasks:
  - name: Welcome
    command: |
      echo "🎓 Welcome to Elevate for Humanity Platform!"
      echo "📚 Digital Binders: docs/digital-binders/"
      echo "✅ All systems ready for development"

# VS Code extensions to install automatically
vscode:
  extensions:
    # Code Quality
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    
    # AI Pair Programming
    - github.copilot
    - github.copilot-chat
    
    # Git Integration
    - eamodio.gitlens
    - github.vscode-pull-request-github
    
    # Language Support
    - ms-python.python
    - ms-vscode.vscode-typescript-next
    
    # Configuration & Utilities
    - redhat.vscode-yaml
    - ms-azuretools.vscode-docker
    - christian-kohler.path-intellisense
    - yzhang.markdown-all-in-one

# Ports configuration (expose ports your application needs)
ports:
  - port: 3000
    onOpen: notify
    visibility: public
  - port: 8080
    onOpen: notify
    visibility: public

# GitHub prebuilds configuration
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false
