image: node:20-bullseye

tasks:
  - name: Setup and Run Elevate Portal
    init: |
      echo "🚀 Installing dependencies..."
      npm install -g pnpm netlify-cli
      pnpm install
      echo "✅ Dependencies installed"
    command: |
      echo "🔧 Starting development server..."
      pnpm run dev --host

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 4173
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
