#!/bin/bash

echo "========================================="
echo "  Supabase Deployment - Quick Guide"
echo "========================================="
echo ""
echo "Project: cuxzzpsyufcewtmicszk"
echo "URL: https://cuxzzpsyufcewtmicszk.supabase.co"
echo ""
echo "All deployment files are ready in: deployment-ready/"
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1️⃣  DEPLOY DATABASE (1 file, 2 minutes)"
echo "   → Open: https://supabase.com/dashboard/project/cuxzzpsyufcewtmicszk/sql/new"
echo "   → Copy: deployment-ready/01-all-migrations.sql"
echo "   → Paste and click 'Run'"
echo "   → Creates: 24 tables, 55 RLS policies, 6 cron jobs"
echo ""
echo "2️⃣  DEPLOY EDGE FUNCTIONS (4 files, 5 minutes)"
echo "   → Open: https://supabase.com/dashboard/project/cuxzzpsyufcewtmicszk/functions"
echo "   → Create function 'email-dispatch' with: deployment-ready/02-email-dispatch.ts"
echo "   → Create function 'webhook-dispatch' with: deployment-ready/03-webhook-dispatch.ts"
echo "   → Create function 'ai-course-create' with: deployment-ready/04-ai-course-create.ts"
echo "   → Create function 'grade-ai' with: deployment-ready/05-grade-ai.ts"
echo ""
echo "3️⃣  CONFIGURE SECRETS (optional, 1 minute)"
echo "   → Open: https://supabase.com/dashboard/project/cuxzzpsyufcewtmicszk/settings/secrets"
echo "   → Add: SENDGRID_API_KEY or RESEND_API_KEY (for email)"
echo "   → Add: ANTHROPIC_API_KEY (optional, for Claude AI)"
echo ""
echo "✅ VERIFICATION:"
echo "   → Database > Tables (should see 24 tables)"
echo "   → Database > Policies (should see 55 policies)"
echo "   → Edge Functions (should see 4 functions)"
echo ""
echo "📦 Files ready for deployment:"
ls -1 deployment-ready/
echo ""
echo "📖 Full instructions: deployment-ready/README.md"
echo ""
echo "========================================="
