#!/bin/bash

# Replace all emojis with Lucide React icons
echo "🔧 Replacing emojis with Lucide icons..."

# Common emoji to icon mappings
declare -A EMOJI_MAP=(
    ["🎯"]="Target"
    ["📊"]="BarChart"
    ["💼"]="Briefcase"
    ["🎓"]="GraduationCap"
    ["📝"]="FileText"
    ["✨"]="Sparkles"
    ["🚀"]="Rocket"
    ["💡"]="Lightbulb"
    ["🔥"]="Flame"
    ["⚡"]="Zap"
    ["🌟"]="Star"
    ["💪"]="Dumbbell"
    ["🎉"]="PartyPopper"
    ["🏆"]="Trophy"
    ["📈"]="TrendingUp"
    ["🎨"]="Palette"
    ["🔔"]="Bell"
    ["📱"]="Smartphone"
    ["💻"]="Laptop"
    ["🌐"]="Globe"
    ["🔒"]="Lock"
    ["✅"]="CheckCircle"
    ["❌"]="XCircle"
    ["⚠️"]="AlertTriangle"
    ["📚"]="BookOpen"
    ["🎬"]="Video"
    ["📧"]="Mail"
    ["📞"]="Phone"
    ["🏠"]="Home"
    ["👥"]="Users"
    ["⏰"]="Clock"
    ["📅"]="Calendar"
    ["💰"]="DollarSign"
    ["🔍"]="Search"
    ["⚙️"]="Settings"
    ["📦"]="Package"
    ["🎁"]="Gift"
    ["🌈"]="Rainbow"
    ["🔗"]="Link"
    ["📄"]="File"
    ["🖼️"]="Image"
    ["🎵"]="Music"
    ["🎮"]="Gamepad"
    ["🏃"]="Activity"
    ["💬"]="MessageCircle"
    ["📢"]="Megaphone"
    ["🔐"]="Shield"
    ["🌍"]="Globe2"
    ["📍"]="MapPin"
    ["🚗"]="Car"
    ["✈️"]="Plane"
    ["🏢"]="Building"
    ["🏥"]="Hospital"
    ["🏫"]="School"
    ["🛒"]="ShoppingCart"
    ["💳"]="CreditCard"
    ["🎤"]="Mic"
    ["📷"]="Camera"
    ["🖨️"]="Printer"
    ["📡"]="Radio"
    ["🔋"]="Battery"
    ["🔌"]="Plug"
    ["💾"]="Save"
    ["📂"]="Folder"
    ["🗂️"]="FolderOpen"
    ["🗃️"]="Archive"
    ["🗄️"]="Database"
    ["🔖"]="Bookmark"
    ["🏷️"]="Tag"
    ["📌"]="Pin"
    ["📎"]="Paperclip"
    ["✏️"]="Edit"
    ["✂️"]="Scissors"
    ["📐"]="Ruler"
    ["📏"]="Ruler"
    ["🔧"]="Wrench"
    ["🔨"]="Hammer"
    ["⚒️"]="Tool"
    ["🛠️"]="Tool"
    ["⚖️"]="Scale"
    ["🔬"]="Microscope"
    ["💊"]="Pill"
    ["💉"]="Syringe"
    ["🩺"]="Stethoscope"
    ["🧬"]="Dna"
    ["🧪"]="TestTube"
    ["🧫"]="Petri"
    ["🧮"]="Calculator"
    ["📊"]="BarChart2"
    ["📉"]="TrendingDown"
    ["📈"]="TrendingUp"
    ["💹"]="ChartLine"
    ["💱"]="Repeat"
    ["💲"]="DollarSign"
    ["💵"]="Banknote"
    ["💴"]="Banknote"
    ["💶"]="Banknote"
    ["💷"]="Banknote"
    ["💸"]="Coins"
    ["🪙"]="Coins"
)

# Find all TSX files with emojis
find app -name "*.tsx" -type f > /tmp/all-tsx-files.txt

# Count total files
TOTAL=$(wc -l < /tmp/all-tsx-files.txt)
echo "Scanning $TOTAL TSX files..."

# Count files with emojis
EMOJI_FILES=0
while IFS= read -r file; do
    if grep -q "[🎯📊💼🎓📝✨🚀💡🔥⚡🌟💪🎉🏆📈🎨🔔📱💻🌐🔒✅❌⚠️]" "$file"; then
        ((EMOJI_FILES++))
    fi
done < /tmp/all-tsx-files.txt

echo "Found $EMOJI_FILES files with emojis"
echo ""
echo "Emoji to Icon mapping:"
for emoji in "${!EMOJI_MAP[@]}"; do
    icon="${EMOJI_MAP[$emoji]}"
    echo "  $emoji → <$icon className=\"w-5 h-5\" />"
done

echo ""
echo "✅ Ready to replace. Run with --execute flag to apply changes."
