#!/bin/bash
# UptimeRobot Setup Guide - Execute these steps manually

echo "🔍 UptimeRobot Monitoring Setup"
echo "================================"
echo ""
echo "Follow these steps to setup uptime monitoring:"
echo ""

echo "1️⃣  Create UptimeRobot Account"
echo "   → Go to: https://uptimerobot.com"
echo "   → Click 'Sign Up' (free account)"
echo "   → Verify your email"
echo ""

echo "2️⃣  Add Monitor #1: Main Website"
echo "   → Click 'Add New Monitor'"
echo "   → Monitor Type: HTTP(s)"
echo "   → Friendly Name: Elevate for Humanity - Main"
echo "   → URL: https://www.elevateforhumanity.org"
echo "   → Monitoring Interval: 5 minutes"
echo "   → Click 'Create Monitor'"
echo ""

echo "3️⃣  Add Monitor #2: LMS Portal"
echo "   → Click 'Add New Monitor'"
echo "   → Monitor Type: HTTP(s)"
echo "   → Friendly Name: Elevate - LMS Portal"
echo "   → URL: https://www.elevateeducationedu.com"
echo "   → Monitoring Interval: 5 minutes"
echo "   → Click 'Create Monitor'"
echo ""

echo "4️⃣  Add Monitor #3: Admin Portal"
echo "   → Click 'Add New Monitor'"
echo "   → Monitor Type: HTTP(s)"
echo "   → Friendly Name: Elevate - Admin Portal"
echo "   → URL: https://www.elevateconnectsdirectory.org"
echo "   → Monitoring Interval: 5 minutes"
echo "   → Click 'Create Monitor'"
echo ""

echo "5️⃣  Add Monitor #4: Health Check"
echo "   → Click 'Add New Monitor'"
echo "   → Monitor Type: HTTP(s)"
echo "   → Friendly Name: Elevate - Health Check"
echo "   → URL: https://www.elevateforhumanity.org/api/health"
echo "   → Monitoring Interval: 5 minutes"
echo "   → Click 'Create Monitor'"
echo ""

echo "6️⃣  Configure Alert Contacts"
echo "   → Go to 'My Settings' → 'Alert Contacts'"
echo "   → Add your email (should be added by default)"
echo "   → Optional: Add SMS, Slack, Discord, etc."
echo ""

echo "7️⃣  Test Alerts (Optional)"
echo "   → Click on a monitor"
echo "   → Click 'Pause Monitoring'"
echo "   → Wait 5 minutes"
echo "   → You should receive a 'Down' alert"
echo "   → Click 'Resume Monitoring'"
echo "   → You should receive an 'Up' alert"
echo ""

echo "✅ Setup Complete!"
echo ""
echo "📊 Monitor URLs:"
echo "   • Main: https://www.elevateforhumanity.org"
echo "   • LMS: https://www.elevateeducationedu.com"
echo "   • Admin: https://www.elevateconnectsdirectory.org"
echo "   • Health: https://www.elevateforhumanity.org/api/health"
echo ""
echo "📧 You'll receive email alerts if any site goes down!"
echo ""
echo "⏱️  Estimated time: 5-10 minutes"
echo ""
