name = "efh-page-deployer"
main = "page-deployer.js"
compatibility_date = "2024-10-14"

# R2 bucket for deployed pages (optional - comment out if not available)
# [[r2_buckets]]
# binding = "PAGES_BUCKET"
# bucket_name = "efh-pages"

# Cron trigger for scheduled deployments (daily at 2 AM UTC)
[triggers]
crons = ["0 2 * * *"]

# Environment variables (set via: wrangler secret put <NAME>)
# Required secrets:
# - SUPABASE_URL: https://<project>.supabase.co
# - SUPABASE_ANON_KEY: Your Supabase anon key
# - SUPABASE_SERVICE_KEY: Your Supabase service role key

[env.production]
name = "efh-page-deployer"
[[env.production.r2_buckets]]
binding = "PAGES_BUCKET"
bucket_name = "efh-pages-prod"

[env.staging]
name = "efh-page-deployer-staging"
[[env.staging.r2_buckets]]
binding = "PAGES_BUCKET"
bucket_name = "efh-pages-staging"
