-- =============================================
-- COMPLETE LMS SETUP - ONE FILE
-- Generated by Ultimate Autopilot
-- =============================================

-- =============================================
-- EFH LMS Database Schema
-- Run this in Supabase SQL Editor
-- =============================================

-- Programs (public catalog)
create table if not exists programs (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  track text not null,
  blurb text,
  hours text,
  cover_url text,
  created_at timestamp with time zone default now()
);

-- Courses
create table if not exists courses (
  id uuid primary key default gen_random_uuid(),
  program_id uuid references programs(id) on delete set null,
  code text not null,
  title text not null,
  summary text,
  cover_url text,
  created_at timestamptz default now()
);
create index if not exists idx_courses_program_id on courses(program_id);

-- Lessons
create table if not exists lessons (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references courses(id) on delete cascade,
  idx int not null,
  title text not null,
  video_url text,
  html text,
  created_at timestamptz default now()
);
create index if not exists idx_lessons_course_id_idx on lessons(course_id, idx);

-- Enrollments
create table if not exists enrollments (
  user_id uuid not null,
  course_id uuid not null references courses(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (user_id, course_id)
);

-- Lesson Progress
create table if not exists lesson_progress (
  user_id uuid not null,
  lesson_id uuid not null references lessons(id) on delete cascade,
  percent int not null default 0,
  updated_at timestamptz default now(),
  primary key (user_id, lesson_id)
);

-- Quiz Questions
create table if not exists quiz_questions (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references lessons(id) on delete cascade,
  prompt text not null,
  options text[] not null default '{}',
  answer text
);

-- Quiz Responses
create table if not exists quiz_responses (
  question_id uuid references quiz_questions(id) on delete cascade,
  user_id uuid not null,
  answer text,
  created_at timestamptz default now()
);

-- =============================================
-- Row Level Security (RLS)
-- =============================================

-- Enable RLS on all tables
alter table programs enable row level security;
alter table courses enable row level security;
alter table lessons enable row level security;
alter table enrollments enable row level security;
alter table lesson_progress enable row level security;
alter table quiz_questions enable row level security;
alter table quiz_responses enable row level security;

-- Public read for catalog
create policy "programs are readable" on programs for select using (true);
create policy "courses readable" on courses for select using (true);
create policy "lessons readable" on lessons for select using (true);

-- Authenticated for learning records
create policy "enrollments by owner" on enrollments
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "progress by owner" on lesson_progress
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "quiz read" on quiz_questions for select using (true);

create policy "quiz responses owner" on quiz_responses
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- =============================================
-- Seed Sample Data
-- =============================================

-- Insert sample programs
insert into programs (slug, title, track, blurb, hours, cover_url) values
  ('cna-hha', 'CNA / HHA', 'Healthcare', 'State-aligned training with clinicals and direct employer placement.', '4–8 weeks', '/programs/cna.jpg'),
  ('welding-aws', 'Welding (AWS SENSE)', 'Construction', 'Hands-on welding lab and industry-recognized AWS SENSE credentials.', '6–10 weeks', '/programs/welding.jpg'),
  ('nail-tech', 'Nail Technology', 'Beauty', 'State board preparation with salon-ready portfolio and sanitation.', '8–12 weeks', '/programs/nails.jpg'),
  ('cdl', 'CDL (A/B) Prep', 'Business', 'Permit prep, simulator practice, and employer-ready onboarding.', '3–6 weeks', '/programs/cdl.jpg'),
  ('office-tech', 'Office Tech & AI', 'Tech', 'Docs, Sheets, CRM, and AI workflows for modern office careers.', '4–6 weeks', '/programs/office.jpg'),
  ('osha10', 'OSHA-10 + CPR', 'Construction', 'Worksite safety fundamentals plus life-saving CPR/AED certification.', '1–2 weeks', '/programs/osha.jpg')
on conflict (slug) do nothing;

-- Insert sample course
insert into courses (program_id, code, title, summary)
select id, 'HLTH-101', 'Patient Care Basics', 'Intro to patient care, HIPAA, and safety.'
from programs where slug='cna-hha'
on conflict do nothing;

-- Insert sample lesson
insert into lessons (course_id, idx, title, video_url, html)
select c.id, 1, 'Hand Hygiene', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '<p>Proper hand hygiene saves lives. Follow the 7-step process for effective handwashing.</p>'
from courses c where c.code='HLTH-101'
on conflict do nothing;

-- Insert sample quiz question
insert into quiz_questions (lesson_id, prompt, options, answer)
select l.id, 'Which is the best time to wash hands?', array['Before patient contact','After removing gloves','Both'], 'Both'
from lessons l
join courses c on l.course_id = c.id
where c.code='HLTH-101' and l.idx = 1
on conflict do nothing;

-- =============================================
-- Success Message
-- =============================================
do $$
begin
  raise notice 'LMS schema created successfully!';
  raise notice 'Sample data inserted: 6 programs, 1 course, 1 lesson, 1 quiz question';
end $$;
-- =============================================
-- EFH LMS Part 2: Auth, Instructor Tools, Certificates
-- Run this AFTER 001_lms_schema.sql
-- =============================================

-- Profiles (extends auth.users)
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'student' check (role in ('student', 'instructor', 'admin')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Certificates
create table if not exists certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references courses(id) on delete cascade,
  certificate_number text unique not null,
  issued_at timestamptz default now(),
  unique(user_id, course_id)
);

create index if not exists idx_certificates_user_id on certificates(user_id);
create index if not exists idx_certificates_number on certificates(certificate_number);

-- =============================================
-- Row Level Security (RLS)
-- =============================================

alter table profiles enable row level security;
alter table certificates enable row level security;

-- Profiles: Users can read all profiles, but only update their own
create policy "profiles are readable" on profiles for select using (true);

create policy "users can update own profile" on profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- Certificates: Public read for verification, users can see their own
create policy "certificates readable by owner" on certificates
  for select using (auth.uid() = user_id or true);

create policy "certificates insertable by system" on certificates
  for insert with check (auth.uid() = user_id);

-- =============================================
-- Functions
-- =============================================

-- Auto-create profile on user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'student');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Function to check course completion
create or replace function check_course_completion(
  p_user_id uuid,
  p_course_id uuid
) returns boolean as $$
declare
  total_lessons int;
  completed_lessons int;
begin
  -- Count total lessons
  select count(*) into total_lessons
  from lessons
  where course_id = p_course_id;

  -- Count completed lessons (100% progress)
  select count(*) into completed_lessons
  from lesson_progress lp
  join lessons l on l.id = lp.lesson_id
  where l.course_id = p_course_id
    and lp.user_id = p_user_id
    and lp.percent = 100;

  return total_lessons > 0 and total_lessons = completed_lessons;
end;
$$ language plpgsql;

-- =============================================
-- Seed Data
-- =============================================

-- Create sample instructor account (password: instructor123)
-- Note: You'll need to create this user via Supabase Auth UI or API
-- Then update their role:
-- UPDATE profiles SET role = 'instructor' WHERE email = 'instructor@example.com';

-- =============================================
-- Success Message
-- =============================================
do $$
begin
  raise notice 'Part 2 schema created successfully!';
  raise notice 'Added: profiles, certificates tables';
  raise notice 'Added: RLS policies, triggers, functions';
  raise notice 'Next: Create instructor user and update role in profiles table';
end $$;
-- Creates core analytics tables and helpers for dashboard visibility.
create extension if not exists "uuid-ossp";

create table if not exists public.analytics_events (
  id uuid primary key default uuid_generate_v4(),
  event_type text not null,
  actor jsonb,
  properties jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

comment on table public.analytics_events is 'Normalized event log used for analytics dashboards and KPIs.';
comment on column public.analytics_events.event_type is 'Domain event identifier, e.g. course.enrolled or video.completed.';
comment on column public.analytics_events.actor is 'JSON object capturing user metadata at time of event (id, role, email).';
comment on column public.analytics_events.properties is 'Arbitrary JSON payload describing the event context.';

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_event_type_idx on public.analytics_events (event_type);

create or replace view public.analytics_daily_activity as
with days as (
  select generate_series(current_date - interval '29 days', current_date, interval '1 day')::date as day
),
counts as (
  select date_trunc('day', created_at)::date as day,
         count(*) as events,
         count(distinct actor ->> 'id') as unique_actors
  from public.analytics_events
  where created_at >= current_date - interval '29 days'
  group by 1
)
select d.day,
       coalesce(c.events, 0) as events,
       coalesce(c.unique_actors, 0) as unique_actors
from days d
left join counts c on d.day = c.day
order by d.day asc;

comment on view public.analytics_daily_activity is '30 day rolling window of total events and unique actors.';

create or replace function public.analytics_dashboard_metrics()
returns jsonb
language sql
stable
as
$$
  with series as (
    select * from public.analytics_daily_activity
  ),
  top_events as (
    select event_type, count(*) as total
    from public.analytics_events
    where created_at >= now() - interval '30 days'
    group by event_type
    order by total desc
    limit 5
  ),
  recent_students as (
    select count(distinct actor ->> 'id')::integer as total
    from public.analytics_events
    where created_at >= now() - interval '30 days'
      and coalesce(actor ->> 'role', '') = 'student'
  )
  select jsonb_build_object(
    'totalEvents', (select count(*) from public.analytics_events),
    'eventsLast7Days', (
      select count(*)
      from public.analytics_events
      where created_at >= now() - interval '7 days'
    ),
    'activeStudentsLast30Days', coalesce((select total from recent_students), 0),
    'series', (
      select jsonb_agg(
        jsonb_build_object('date', day, 'events', events, 'uniqueActors', unique_actors)
        order by day
      )
      from series
    ),
    'topEvents', coalesce((
      select jsonb_agg(jsonb_build_object('eventType', event_type, 'total', total))
      from top_events
    ), '[]'::jsonb)
  );
$$;

comment on function public.analytics_dashboard_metrics is 'Bundles headline KPI metrics for the admin analytics dashboard.';
-- Add Missing RLS Policies
-- This migration adds comprehensive RLS policies for tables that were missing them

-- ============================================
-- MODULES TABLE POLICIES
-- ============================================

-- Allow everyone to view modules for published courses
CREATE POLICY "Modules are viewable for published courses" ON public.modules
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.courses
            WHERE courses.id = modules.course_id
            AND courses.published = true
        )
        OR
        -- Instructors can view their own course modules
        EXISTS (
            SELECT 1 FROM public.courses
            WHERE courses.id = modules.course_id
            AND courses.instructor_id = auth.uid()
        )
        OR
        -- Enrolled students can view modules
        EXISTS (
            SELECT 1 FROM public.enrollments
            JOIN public.courses ON courses.id = enrollments.course_id
            WHERE courses.id = modules.course_id
            AND enrollments.user_id = auth.uid()
        )
    );

-- Instructors can insert modules for their courses
CREATE POLICY "Instructors can insert modules" ON public.modules
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.courses
            WHERE courses.id = modules.course_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- Instructors can update their own course modules
CREATE POLICY "Instructors can update own modules" ON public.modules
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.courses
            WHERE courses.id = modules.course_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- Instructors can delete their own course modules
CREATE POLICY "Instructors can delete own modules" ON public.modules
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.courses
            WHERE courses.id = modules.course_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- ============================================
-- ASSIGNMENTS TABLE POLICIES
-- ============================================

-- Students can view assignments for courses they're enrolled in
CREATE POLICY "Students can view assignments for enrolled courses" ON public.assignments
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.modules
            JOIN public.courses ON courses.id = modules.course_id
            JOIN public.enrollments ON enrollments.course_id = courses.id
            WHERE modules.id = assignments.module_id
            AND enrollments.user_id = auth.uid()
        )
        OR
        -- Instructors can view assignments for their courses
        EXISTS (
            SELECT 1 FROM public.modules
            JOIN public.courses ON courses.id = modules.course_id
            WHERE modules.id = assignments.module_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- Instructors can insert assignments for their course modules
CREATE POLICY "Instructors can insert assignments" ON public.assignments
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.modules
            JOIN public.courses ON courses.id = modules.course_id
            WHERE modules.id = assignments.module_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- Instructors can update assignments for their courses
CREATE POLICY "Instructors can update assignments" ON public.assignments
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.modules
            JOIN public.courses ON courses.id = modules.course_id
            WHERE modules.id = assignments.module_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- Instructors can delete assignments for their courses
CREATE POLICY "Instructors can delete assignments" ON public.assignments
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.modules
            JOIN public.courses ON courses.id = modules.course_id
            WHERE modules.id = assignments.module_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- ============================================
-- MODULE_PROGRESS TABLE - ADD UPDATE POLICY
-- ============================================

-- Users can update their own progress
CREATE POLICY "Users can update own module progress" ON public.module_progress
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.enrollments
            WHERE enrollments.id = module_progress.enrollment_id
            AND enrollments.user_id = auth.uid()
        )
    );

-- ============================================
-- SUBMISSIONS TABLE - ADD MISSING POLICIES
-- ============================================

-- Instructors can view submissions for their courses
CREATE POLICY "Instructors can view course submissions" ON public.submissions
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.assignments
            JOIN public.modules ON modules.id = assignments.module_id
            JOIN public.courses ON courses.id = modules.course_id
            WHERE assignments.id = submissions.assignment_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- Users can update their own submissions (for resubmissions)
CREATE POLICY "Users can update own submissions" ON public.submissions
    FOR UPDATE USING (auth.uid() = user_id);

-- Instructors can update submissions (for grading)
CREATE POLICY "Instructors can update submissions for grading" ON public.submissions
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.assignments
            JOIN public.modules ON modules.id = assignments.module_id
            JOIN public.courses ON courses.id = modules.course_id
            WHERE assignments.id = submissions.assignment_id
            AND courses.instructor_id = auth.uid()
        )
    );

-- ============================================
-- CERTIFICATES TABLE - ADD MISSING POLICIES
-- ============================================

-- Allow public viewing of certificates (for verification)
CREATE POLICY "Certificates are publicly viewable" ON public.certificates
    FOR SELECT USING (true);

-- System can insert certificates (via trigger or admin)
-- Note: This is handled by SECURITY DEFINER functions, but we add a policy for explicit admin inserts
CREATE POLICY "System can insert certificates" ON public.certificates
    FOR INSERT WITH CHECK (
        -- Only allow if user completed the course
        EXISTS (
            SELECT 1 FROM public.enrollments
            WHERE enrollments.user_id = certificates.user_id
            AND enrollments.course_id = certificates.course_id
            AND enrollments.status = 'completed'
        )
    );

-- ============================================
-- ENROLLMENTS TABLE - ADD DELETE POLICY
-- ============================================

-- Users can delete their own enrollments (unenroll)
CREATE POLICY "Users can delete own enrollments" ON public.enrollments
    FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- COURSES TABLE - ADD DELETE POLICY
-- ============================================

-- Instructors can delete their own courses
CREATE POLICY "Instructors can delete own courses" ON public.courses
    FOR DELETE USING (auth.uid() = instructor_id);

-- ============================================
-- PROFILES TABLE - ADD DELETE POLICY
-- ============================================

-- Users can delete their own profile
CREATE POLICY "Users can delete own profile" ON public.profiles
    FOR DELETE USING (auth.uid() = id);
-- Enable row level security and define baseline policies for analytics events.
alter table public.analytics_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'allow_insert_from_authenticated_clients'
  ) then
    create policy allow_insert_from_authenticated_clients
      on public.analytics_events
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'allow_service_role_full_access'
  ) then
    create policy allow_service_role_full_access
      on public.analytics_events
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;

alter function public.analytics_dashboard_metrics() security definer;
alter function public.analytics_dashboard_metrics() set search_path = public;
comment on function public.analytics_dashboard_metrics is 'Bundles headline KPI metrics for the admin analytics dashboard (executes as definer to avoid RLS friction).';
-- Migration: Create tables for automation functions
-- Created: 2025-01-27

-- Students table
CREATE TABLE IF NOT EXISTS students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enrollments table
CREATE TABLE IF NOT EXISTS enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  program_id TEXT NOT NULL,
  program_name TEXT NOT NULL,
  enrollment_date TIMESTAMPTZ DEFAULT NOW(),
  completion_date TIMESTAMPTZ,
  funding_source TEXT DEFAULT 'self-pay',
  status TEXT DEFAULT 'pending',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Job placements table
CREATE TABLE IF NOT EXISTS job_placements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES students(id) ON DELETE CASCADE,
  enrollment_id UUID REFERENCES enrollments(id) ON DELETE CASCADE,
  employer_name TEXT NOT NULL,
  job_title TEXT NOT NULL,
  starting_salary NUMERIC,
  employment_type TEXT DEFAULT 'full-time',
  placement_date TIMESTAMPTZ DEFAULT NOW(),
  industry TEXT,
  location TEXT,
  benefits JSONB DEFAULT '{}',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activity log table
CREATE TABLE IF NOT EXISTS activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type TEXT NOT NULL,
  entity_id UUID NOT NULL,
  action TEXT NOT NULL,
  details JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reports table
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_type TEXT NOT NULL,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  data JSONB NOT NULL,
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_students_email ON students(email);
CREATE INDEX IF NOT EXISTS idx_enrollments_student_id ON enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_status ON enrollments(status);
CREATE INDEX IF NOT EXISTS idx_enrollments_funding_source ON enrollments(funding_source);
CREATE INDEX IF NOT EXISTS idx_enrollments_created_at ON enrollments(created_at);
CREATE INDEX IF NOT EXISTS idx_job_placements_student_id ON job_placements(student_id);
CREATE INDEX IF NOT EXISTS idx_job_placements_enrollment_id ON job_placements(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_job_placements_placement_date ON job_placements(placement_date);
CREATE INDEX IF NOT EXISTS idx_activity_log_entity ON activity_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_created_at ON activity_log(created_at);
CREATE INDEX IF NOT EXISTS idx_reports_type_date ON reports(report_type, generated_at);

-- Enable Row Level Security
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_placements ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- RLS Policies (adjust based on your auth setup)

-- Students: Service role can do everything
CREATE POLICY "Service role full access on students"
  ON students
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Enrollments: Service role can do everything
CREATE POLICY "Service role full access on enrollments"
  ON enrollments
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Job placements: Service role can do everything
CREATE POLICY "Service role full access on job_placements"
  ON job_placements
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Activity log: Service role can do everything
CREATE POLICY "Service role full access on activity_log"
  ON activity_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Reports: Service role can do everything
CREATE POLICY "Service role full access on reports"
  ON reports
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add triggers for updated_at
CREATE TRIGGER update_students_updated_at
  BEFORE UPDATE ON students
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_enrollments_updated_at
  BEFORE UPDATE ON enrollments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_job_placements_updated_at
  BEFORE UPDATE ON job_placements
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
-- Migration: Create generated content table
-- Created: 2025-01-27

-- Generated content table
CREATE TABLE IF NOT EXISTS generated_content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Content Details
  content_type TEXT NOT NULL,
  platform TEXT NOT NULL,
  program TEXT,
  theme TEXT,
  content TEXT NOT NULL,
  
  -- Media
  image_url TEXT,
  video_url TEXT,
  
  -- Scheduling
  scheduled_date TIMESTAMPTZ,
  published_date TIMESTAMPTZ,
  status TEXT DEFAULT 'draft',
  
  -- Engagement Metrics
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  
  -- Metadata
  generated_by TEXT DEFAULT 'openai',
  edited_by UUID,
  approved_by UUID,
  
  -- Timestamps
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_generated_content_platform ON generated_content(platform);
CREATE INDEX IF NOT EXISTS idx_generated_content_status ON generated_content(status);
CREATE INDEX IF NOT EXISTS idx_generated_content_scheduled_date ON generated_content(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_generated_content_content_type ON generated_content(content_type);
CREATE INDEX IF NOT EXISTS idx_generated_content_program ON generated_content(program);

-- Enable Row Level Security
ALTER TABLE generated_content ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Service role full access
CREATE POLICY "Service role full access on generated_content"
  ON generated_content
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Authenticated users can view published content
CREATE POLICY "Authenticated users can view published content"
  ON generated_content
  FOR SELECT
  TO authenticated
  USING (status = 'published');

-- Add updated_at trigger
CREATE TRIGGER update_generated_content_updated_at
  BEFORE UPDATE ON generated_content
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
-- Migration: Create scholarship applications table
-- Created: 2025-01-27

-- Scholarship applications table
CREATE TABLE IF NOT EXISTS scholarship_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Personal Information
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  date_of_birth DATE NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip TEXT NOT NULL,
  
  -- Scholarship & Program
  scholarship_type TEXT NOT NULL,
  program_interest TEXT NOT NULL,
  
  -- Eligibility
  household_income TEXT NOT NULL,
  household_size INTEGER NOT NULL,
  employment_status TEXT NOT NULL,
  education_level TEXT NOT NULL,
  
  -- Circumstances
  is_single_parent BOOLEAN DEFAULT false,
  is_formerly_incarcerated BOOLEAN DEFAULT false,
  is_homeless BOOLEAN DEFAULT false,
  is_veteran BOOLEAN DEFAULT false,
  has_disability BOOLEAN DEFAULT false,
  
  -- Essays
  why_scholarship TEXT NOT NULL,
  career_goals TEXT NOT NULL,
  financial_need TEXT,
  
  -- Uploaded Files
  proof_of_income_url TEXT,
  identification_url TEXT,
  additional_docs_url TEXT,
  
  -- Status & Tracking
  status TEXT DEFAULT 'pending',
  reviewed_by UUID,
  reviewed_at TIMESTAMPTZ,
  decision TEXT,
  decision_notes TEXT,
  award_amount NUMERIC,
  
  -- Timestamps
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_scholarship_applications_email ON scholarship_applications(email);
CREATE INDEX IF NOT EXISTS idx_scholarship_applications_status ON scholarship_applications(status);
CREATE INDEX IF NOT EXISTS idx_scholarship_applications_scholarship_type ON scholarship_applications(scholarship_type);
CREATE INDEX IF NOT EXISTS idx_scholarship_applications_submitted_at ON scholarship_applications(submitted_at);

-- Enable Row Level Security
ALTER TABLE scholarship_applications ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Service role full access
CREATE POLICY "Service role full access on scholarship_applications"
  ON scholarship_applications
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Applicants can view their own applications
CREATE POLICY "Applicants can view own applications"
  ON scholarship_applications
  FOR SELECT
  TO authenticated
  USING (auth.jwt() ->> 'email' = email);

-- Add updated_at trigger
CREATE TRIGGER update_scholarship_applications_updated_at
  BEFORE UPDATE ON scholarship_applications
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create storage bucket for documents
INSERT INTO storage.buckets (id, name, public)
VALUES ('documents', 'documents', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for documents bucket
CREATE POLICY "Service role can upload documents"
  ON storage.objects
  FOR INSERT
  TO service_role
  WITH CHECK (bucket_id = 'documents');

CREATE POLICY "Service role can read documents"
  ON storage.objects
  FOR SELECT
  TO service_role
  USING (bucket_id = 'documents');

CREATE POLICY "Authenticated users can read own documents"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'documents' AND
    (storage.foldername(name))[1] = 'scholarship-applications' AND
    (storage.foldername(name))[2] = auth.jwt() ->> 'email'
  );
-- Migration: Create tables for Stripe split payouts
-- Created: 2025-01-27

-- Instructors table
CREATE TABLE IF NOT EXISTS instructors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  stripe_account_id TEXT UNIQUE,
  stripe_account_status TEXT DEFAULT 'pending',
  payout_percentage NUMERIC DEFAULT 80.00,
  bio TEXT,
  specialties TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Split payouts table
CREATE TABLE IF NOT EXISTS split_payouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_intent_id TEXT NOT NULL,
  program_id TEXT NOT NULL,
  instructor_id UUID REFERENCES instructors(id) ON DELETE SET NULL,
  total_amount INTEGER NOT NULL,
  efh_amount INTEGER NOT NULL,
  instructor_amount INTEGER NOT NULL,
  selfish_inc_amount INTEGER NOT NULL,
  platform_amount INTEGER NOT NULL,
  transfers JSONB DEFAULT '[]',
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Instructor programs junction table
CREATE TABLE IF NOT EXISTS instructor_programs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instructor_id UUID REFERENCES instructors(id) ON DELETE CASCADE,
  program_id TEXT NOT NULL,
  program_name TEXT NOT NULL,
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_instructors_email ON instructors(email);
CREATE INDEX IF NOT EXISTS idx_instructors_stripe_account ON instructors(stripe_account_id);
CREATE INDEX IF NOT EXISTS idx_split_payouts_payment_intent ON split_payouts(payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_split_payouts_instructor ON split_payouts(instructor_id);
CREATE INDEX IF NOT EXISTS idx_split_payouts_created_at ON split_payouts(created_at);
CREATE INDEX IF NOT EXISTS idx_split_payouts_status ON split_payouts(status);
CREATE INDEX IF NOT EXISTS idx_instructor_programs_instructor ON instructor_programs(instructor_id);
CREATE INDEX IF NOT EXISTS idx_instructor_programs_program ON instructor_programs(program_id);

-- Enable Row Level Security
ALTER TABLE instructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE split_payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE instructor_programs ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Instructors: Service role full access
CREATE POLICY "Service role full access on instructors"
  ON instructors
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Instructors: Authenticated users can view
CREATE POLICY "Authenticated users can view instructors"
  ON instructors
  FOR SELECT
  TO authenticated
  USING (true);

-- Split payouts: Service role full access
CREATE POLICY "Service role full access on split_payouts"
  ON split_payouts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Instructor programs: Service role full access
CREATE POLICY "Service role full access on instructor_programs"
  ON instructor_programs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Instructor programs: Authenticated users can view
CREATE POLICY "Authenticated users can view instructor_programs"
  ON instructor_programs
  FOR SELECT
  TO authenticated
  USING (true);

-- Add updated_at triggers
CREATE TRIGGER update_instructors_updated_at
  BEFORE UPDATE ON instructors
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_split_payouts_updated_at
  BEFORE UPDATE ON split_payouts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Insert sample instructors (optional - remove in production)
INSERT INTO instructors (first_name, last_name, email, payout_percentage, specialties) VALUES
  ('Sarah', 'Johnson', 'sarah.johnson@example.com', 80.00, ARRAY['Tax Preparation', 'Business Formation']),
  ('Michael', 'Davis', 'michael.davis@example.com', 80.00, ARRAY['Barbering', 'Cosmetology']),
  ('Jennifer', 'Martinez', 'jennifer.martinez@example.com', 80.00, ARRAY['Healthcare', 'CPR/First Aid']),
  ('Robert', 'Wilson', 'robert.wilson@example.com', 80.00, ARRAY['Construction', 'OSHA Safety'])
ON CONFLICT (email) DO NOTHING;


-- =============================================
-- IRS VITA COURSE
-- =============================================

-- =============================================
-- IRS VITA Tax Preparation Program
-- All content links to official IRS resources
-- =============================================

-- Insert Program
INSERT INTO programs (slug, title, track, blurb, hours, cover_url)
VALUES (
  'irs-vita-tax-preparation',
  'IRS VITA Tax Preparation Training',
  'Finance',
  'Become an IRS-certified volunteer tax preparer. Free training provided by the IRS to help low-to-moderate income families prepare their tax returns.',
  '40 hours',
  'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800'
) ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  track = EXCLUDED.track,
  blurb = EXCLUDED.blurb,
  hours = EXCLUDED.hours,
  cover_url = EXCLUDED.cover_url;

-- Insert Course
INSERT INTO courses (program_id, code, title, summary, cover_url)
VALUES (
  (SELECT id FROM programs WHERE slug = 'irs-vita-tax-preparation'),
  'VITA101',
  'VITA Volunteer Tax Preparer Certification',
  'Complete IRS-certified training to become a volunteer tax preparer. Learn to prepare basic tax returns for individuals and families earning $64,000 or less per year.',
  'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800'
) ON CONFLICT DO NOTHING;

-- Get the course ID for lessons
DO $$
DECLARE
  v_course_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE code = 'VITA101';
  
  -- Lesson 1: Introduction to VITA Program
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    1,
    'Welcome to VITA Volunteer Training',
    NULL,
    '<h2>Welcome to VITA Volunteer Training</h2>
    
    <p>The <strong>Volunteer Income Tax Assistance (VITA)</strong> program offers free tax help to people who generally make $64,000 or less, persons with disabilities, and limited English-speaking taxpayers who need assistance in preparing their own tax returns.</p>
    
    <h3>What You''ll Learn</h3>
    <ul>
      <li>How to prepare basic tax returns</li>
      <li>IRS tax law and regulations</li>
      <li>Ethics and standards of conduct</li>
      <li>Quality review procedures</li>
      <li>Taxpayer rights and responsibilities</li>
    </ul>
    
    <h3>Official IRS Resources</h3>
    <p><strong>📋 Sign Up to Volunteer:</strong><br>
    <a href="https://freetaxassistance.for.irs.gov/s/sign-up-form" target="_blank">IRS VITA/TCE Volunteer Sign Up Form</a></p>
    
    <p><strong>📚 Program Overview:</strong><br>
    <a href="https://www.irs.gov/individuals/irs-tax-volunteers" target="_blank">IRS Tax Volunteers Information</a></p>
    
    <p><strong>🎓 Training Resources:</strong><br>
    <a href="https://www.irs.gov/individuals/volunteer-training-resources" target="_blank">IRS Volunteer Training Resources</a></p>
    
    <h3>Course Outline</h3>
    <ol>
      <li><strong>Lesson 1:</strong> Welcome to VITA (you are here)</li>
      <li><strong>Lesson 2:</strong> Understanding the IRS VITA Program</li>
      <li><strong>Lesson 3:</strong> Volunteer Roles and Requirements</li>
      <li><strong>Lesson 4:</strong> IRS Link & Learn Taxes Online Training</li>
      <li><strong>Lesson 5:</strong> Tax Software Practice Lab</li>
      <li><strong>Lesson 6:</strong> Ethics and Standards of Conduct</li>
      <li><strong>Lesson 7:</strong> Quality Review and Accuracy</li>
      <li><strong>Lesson 8:</strong> Getting Started - Next Steps</li>
    </ol>
    
    <h3>Next Steps</h3>
    <ol>
      <li>Complete this online orientation course</li>
      <li>Sign up as a volunteer using the IRS form above</li>
      <li>Complete IRS Link & Learn Taxes training</li>
      <li>Pass the IRS certification test</li>
      <li>Start volunteering at a local VITA site</li>
    </ol>
    
    <p style="margin-top: 30px;"><strong>Ready to begin?</strong> Click "Next Lesson" to continue!</p>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 2: Introduction to VITA Program
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    2,
    'Understanding the IRS VITA Program',
    NULL,
    '<h2>Welcome to IRS VITA Volunteer Training</h2>
    
    <p>The <strong>Volunteer Income Tax Assistance (VITA)</strong> program offers free tax help to people who generally make $64,000 or less, persons with disabilities, and limited English-speaking taxpayers who need assistance in preparing their own tax returns.</p>
    
    <h3>What You''ll Learn</h3>
    <ul>
      <li>How to prepare basic tax returns</li>
      <li>IRS tax law and regulations</li>
      <li>Ethics and standards of conduct</li>
      <li>Quality review procedures</li>
      <li>Taxpayer rights and responsibilities</li>
    </ul>
    
    <h3>Official IRS Resources</h3>
    <p><strong>📋 Sign Up to Volunteer:</strong><br>
    <a href="https://freetaxassistance.for.irs.gov/s/sign-up-form" target="_blank">IRS VITA/TCE Volunteer Sign Up Form</a></p>
    
    <p><strong>📚 Program Overview:</strong><br>
    <a href="https://www.irs.gov/individuals/irs-tax-volunteers" target="_blank">IRS Tax Volunteers Information</a></p>
    
    <p><strong>🎓 Training Resources:</strong><br>
    <a href="https://www.irs.gov/individuals/volunteer-training-resources" target="_blank">IRS Volunteer Training Resources</a></p>
    
    <h3>Next Steps</h3>
    <ol>
      <li>Complete this online orientation course</li>
      <li>Sign up as a volunteer using the IRS form above</li>
      <li>Complete IRS Link & Learn Taxes training</li>
      <li>Pass the IRS certification test</li>
      <li>Start volunteering at a local VITA site</li>
    </ol>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 3: Volunteer Roles and Requirements
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    3,
    'Volunteer Roles and Requirements',
    NULL,
    '<h2>Choose Your Volunteer Role</h2>
    
    <p>VITA offers several volunteer positions to match your skills and interests:</p>
    
    <h3>Available Roles</h3>
    
    <h4>1. Tax Preparer</h4>
    <ul>
      <li>Prepare tax returns for taxpayers</li>
      <li>Interview taxpayers to gather information</li>
      <li>Use tax software to complete returns</li>
      <li><strong>Training Required:</strong> Basic or Advanced certification</li>
    </ul>
    
    <h4>2. Quality Reviewer</h4>
    <ul>
      <li>Review completed returns for accuracy</li>
      <li>Ensure all required documentation is present</li>
      <li>Verify calculations and tax law application</li>
      <li><strong>Training Required:</strong> Quality Review certification</li>
    </ul>
    
    <h4>3. Greeter/Intake Specialist</h4>
    <ul>
      <li>Welcome taxpayers to the site</li>
      <li>Help complete intake forms</li>
      <li>Organize taxpayer documents</li>
      <li><strong>Training Required:</strong> Intake/Interview training</li>
    </ul>
    
    <h4>4. Site Coordinator</h4>
    <ul>
      <li>Manage VITA site operations</li>
      <li>Schedule volunteers</li>
      <li>Ensure quality standards</li>
      <li><strong>Training Required:</strong> All certifications plus coordinator training</li>
    </ul>
    
    <h3>Official IRS Information</h3>
    <p><strong>📋 Volunteer Roles:</strong><br>
    <a href="https://www.irs.gov/individuals/choose-your-tax-volunteer-role" target="_blank">IRS - Choose Your Tax Volunteer Role</a></p>
    
    <p><strong>📝 Sign Up Form:</strong><br>
    <a href="https://freetaxassistance.for.irs.gov/s/sign-up-form" target="_blank">VITA/TCE Volunteer and Partner Sign Up</a></p>
    
    <h3>Time Commitment</h3>
    <ul>
      <li><strong>Training:</strong> 20-40 hours (online and in-person)</li>
      <li><strong>Volunteering:</strong> 4-8 hours per week during tax season (January-April)</li>
      <li><strong>Flexible scheduling:</strong> Sites open evenings and weekends</li>
    </ul>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 4: IRS Link & Learn Taxes Training
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    4,
    'IRS Link & Learn Taxes Online Training',
    NULL,
    '<h2>Link & Learn Taxes (L&LT)</h2>
    
    <p>Link & Learn Taxes is the <strong>official IRS online training platform</strong> for VITA/TCE volunteers. All training and certification is done through this system.</p>
    
    <h3>Training Courses Available</h3>
    
    <h4>Basic Certification</h4>
    <ul>
      <li>Filing status and exemptions</li>
      <li>Standard deduction</li>
      <li>Earned Income Tax Credit (EITC)</li>
      <li>Child Tax Credit</li>
      <li>Education credits</li>
      <li>Retirement income</li>
    </ul>
    
    <h4>Advanced Certification</h4>
    <ul>
      <li>Itemized deductions</li>
      <li>Self-employment income</li>
      <li>Rental property income</li>
      <li>Capital gains and losses</li>
      <li>Business expenses</li>
    </ul>
    
    <h4>Specialty Certifications</h4>
    <ul>
      <li><strong>Military:</strong> Military-specific tax issues</li>
      <li><strong>International:</strong> Foreign students and scholars</li>
      <li><strong>Puerto Rico:</strong> Puerto Rico residents</li>
    </ul>
    
    <h3>🎓 Access IRS Training</h3>
    <p><strong>Link & Learn Taxes Portal:</strong><br>
    <a href="https://apps.irs.gov/app/vita/" target="_blank">IRS Link & Learn Taxes</a></p>
    
    <p><strong>Training Introduction:</strong><br>
    <a href="https://www.irs.gov/individuals/link-and-learn-taxes" target="_blank">IRS - Link and Learn Taxes Information</a></p>
    
    <h3>Certification Process</h3>
    <ol>
      <li><strong>Create Account:</strong> Register on Link & Learn Taxes</li>
      <li><strong>Complete Training:</strong> Study the online modules</li>
      <li><strong>Take Practice Tests:</strong> Use the practice lab</li>
      <li><strong>Pass Certification Test:</strong> Score 80% or higher</li>
      <li><strong>Receive Certificate:</strong> Print your certification</li>
    </ol>
    
    <h3>📚 Additional Resources</h3>
    <p><strong>Publication 4012 - Volunteer Resource Guide:</strong><br>
    <a href="https://www.irs.gov/pub/irs-pdf/p4012.pdf" target="_blank">Download PDF</a></p>
    
    <p><strong>Publication 4491 - Student Training Guide:</strong><br>
    Available through Link & Learn Taxes</p>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 5: Tax Software Practice Lab
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    5,
    'Tax Software Practice Lab',
    NULL,
    '<h2>Practice with Real Tax Software</h2>
    
    <p>The IRS provides a <strong>free practice lab</strong> where you can practice preparing tax returns using the same software used at VITA sites.</p>
    
    <h3>🖥️ Access Practice Lab</h3>
    <p><strong>TaxSlayer Pro Practice Lab:</strong><br>
    <a href="https://vita.taxslayerpro.com/IRSTraining/en/Account/Access" target="_blank">IRS Tax Software Practice Lab</a></p>
    
    <h3>What You''ll Practice</h3>
    <ul>
      <li>Entering taxpayer information</li>
      <li>Completing Form 1040</li>
      <li>Calculating credits and deductions</li>
      <li>Reviewing returns for accuracy</li>
      <li>E-filing procedures</li>
    </ul>
    
    <h3>Practice Scenarios</h3>
    <p>The practice lab includes realistic tax scenarios:</p>
    <ul>
      <li>Single filer with W-2 income</li>
      <li>Married filing jointly with dependents</li>
      <li>Self-employed individual</li>
      <li>Retiree with Social Security and pension</li>
      <li>Student with education expenses</li>
    </ul>
    
    <h3>📖 Practice Lab Resources</h3>
    <p><strong>Practice Lab Fact Sheet:</strong><br>
    <a href="https://www.irs.gov/pub/irs-pdf/p5377.pdf" target="_blank">Publication 5377 (PDF)</a></p>
    
    <p><strong>Getting Started Guide:</strong><br>
    <a href="https://www.irs.gov/pub/irs-pdf/p5378.pdf" target="_blank">Publication 5378 (PDF)</a></p>
    
    <h3>Tips for Success</h3>
    <ul>
      <li>Complete at least 5 practice returns before certification</li>
      <li>Review your work carefully</li>
      <li>Use Publication 4012 as a reference</li>
      <li>Ask questions in the volunteer forums</li>
      <li>Practice different types of returns</li>
    </ul>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 6: Ethics and Standards of Conduct
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    6,
    'Ethics and Standards of Conduct',
    NULL,
    '<h2>Volunteer Standards of Conduct</h2>
    
    <p>As an IRS-certified volunteer, you must follow strict <strong>ethical standards</strong> to protect taxpayer information and maintain program integrity.</p>
    
    <h3>Core Ethical Principles</h3>
    
    <h4>1. Confidentiality</h4>
    <ul>
      <li>Never share taxpayer information</li>
      <li>Secure all documents and data</li>
      <li>Shred documents after use</li>
      <li>No photos of tax returns</li>
    </ul>
    
    <h4>2. Accuracy</h4>
    <ul>
      <li>Prepare returns carefully</li>
      <li>Double-check all entries</li>
      <li>Use quality review process</li>
      <li>Never guess or estimate</li>
    </ul>
    
    <h4>3. Professionalism</h4>
    <ul>
      <li>Treat all taxpayers with respect</li>
      <li>Maintain professional appearance</li>
      <li>Be punctual and reliable</li>
      <li>Follow site procedures</li>
    </ul>
    
    <h4>4. Integrity</h4>
    <ul>
      <li>Never accept payment or tips</li>
      <li>No solicitation of business</li>
      <li>Report suspected fraud</li>
      <li>Follow IRS guidelines</li>
    </ul>
    
    <h3>📋 Required Training</h3>
    <p><strong>Publication 4961 - Ethics Training:</strong><br>
    Available through Link & Learn Taxes</p>
    
    <p><strong>Volunteer Standards of Conduct:</strong><br>
    <a href="https://www.irs.gov/individuals/volunteer-training-resources" target="_blank">IRS Training Resources</a></p>
    
    <h3>Taxpayer Rights</h3>
    <p>All taxpayers have rights, including:</p>
    <ul>
      <li>Right to quality service</li>
      <li>Right to privacy and confidentiality</li>
      <li>Right to be informed</li>
      <li>Right to challenge IRS decisions</li>
      <li>Right to a fair and just tax system</li>
    </ul>
    
    <p><strong>Taxpayer Bill of Rights:</strong><br>
    <a href="https://www.irs.gov/taxpayer-bill-of-rights" target="_blank">IRS Taxpayer Bill of Rights</a></p>
    
    <h3>Consequences of Violations</h3>
    <ul>
      <li>Immediate removal from program</li>
      <li>Loss of certification</li>
      <li>Possible legal action</li>
      <li>Site closure</li>
    </ul>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 7: Quality Review Process
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    7,
    'Quality Review and Accuracy',
    NULL,
    '<h2>Ensuring Return Accuracy</h2>
    
    <p>Every tax return prepared at a VITA site must go through a <strong>quality review process</strong> before being filed.</p>
    
    <h3>Quality Review Steps</h3>
    
    <h4>1. Document Review</h4>
    <ul>
      <li>Verify all required documents present</li>
      <li>Check W-2s, 1099s, and other forms</li>
      <li>Confirm Social Security numbers</li>
      <li>Review intake form completeness</li>
    </ul>
    
    <h4>2. Return Review</h4>
    <ul>
      <li>Verify filing status</li>
      <li>Check dependent information</li>
      <li>Review income entries</li>
      <li>Verify deductions and credits</li>
      <li>Check calculations</li>
    </ul>
    
    <h4>3. Taxpayer Interview</h4>
    <ul>
      <li>Review return with taxpayer</li>
      <li>Explain refund or balance due</li>
      <li>Answer questions</li>
      <li>Obtain signature</li>
    </ul>
    
    <h4>4. Final Check</h4>
    <ul>
      <li>Verify bank account information</li>
      <li>Confirm e-file authorization</li>
      <li>Provide copy to taxpayer</li>
      <li>Submit return electronically</li>
    </ul>
    
    <h3>📚 Quality Review Training</h3>
    <p><strong>Publication 5101 - Quality Review Training:</strong><br>
    <a href="https://www.irs.gov/pub/irs-pdf/p5101.pdf" target="_blank">Download PDF</a></p>
    
    <h3>Common Errors to Avoid</h3>
    <ul>
      <li>Incorrect filing status</li>
      <li>Missing or incorrect SSNs</li>
      <li>Math errors</li>
      <li>Incorrect bank account numbers</li>
      <li>Missing signatures</li>
      <li>Incorrect credit calculations</li>
    </ul>
    
    <h3>Quality Assurance Goals</h3>
    <ul>
      <li><strong>Target:</strong> 90% accuracy rate</li>
      <li><strong>Review:</strong> 100% of returns reviewed</li>
      <li><strong>Feedback:</strong> Continuous improvement</li>
    </ul>'
  ) ON CONFLICT DO NOTHING;
  
  -- Lesson 8: Getting Started as a Volunteer
  INSERT INTO lessons (course_id, idx, title, video_url, html)
  VALUES (
    v_course_id,
    8,
    'Getting Started - Next Steps',
    NULL,
    '<h2>Ready to Volunteer?</h2>
    
    <p>You''ve completed the orientation! Here''s how to become an official IRS VITA volunteer.</p>
    
    <h3>🚀 Step-by-Step Process</h3>
    
    <h4>Step 1: Sign Up</h4>
    <p><strong>Complete the official IRS volunteer sign-up form:</strong><br>
    <a href="https://freetaxassistance.for.irs.gov/s/sign-up-form" target="_blank" class="btn btn-primary">Sign Up as VITA Volunteer</a></p>
    
    <h4>Step 2: Complete Training</h4>
    <p><strong>Access Link & Learn Taxes:</strong><br>
    <a href="https://apps.irs.gov/app/vita/" target="_blank">IRS Link & Learn Taxes Portal</a></p>
    
    <ul>
      <li>Register for an account</li>
      <li>Complete Basic certification course</li>
      <li>Study Publication 4012</li>
      <li>Practice in the software lab</li>
    </ul>
    
    <h4>Step 3: Pass Certification Test</h4>
    <ul>
      <li>Take the online certification test</li>
      <li>Score 80% or higher to pass</li>
      <li>Retake if needed (no limit)</li>
      <li>Print your certificate</li>
    </ul>
    
    <h4>Step 4: Find a VITA Site</h4>
    <p><strong>Locate VITA sites near you:</strong><br>
    <a href="https://www.irs.gov/individuals/find-a-location-for-free-tax-prep" target="_blank">IRS - Find a VITA Location</a></p>
    
    <h4>Step 5: Start Volunteering</h4>
    <ul>
      <li>Contact your local site coordinator</li>
      <li>Complete any additional site training</li>
      <li>Schedule your volunteer shifts</li>
      <li>Begin helping taxpayers!</li>
    </ul>
    
    <h3>📞 Need Help?</h3>
    
    <p><strong>IRS Volunteer Resources:</strong><br>
    <a href="https://www.irs.gov/individuals/volunteer-training-resources" target="_blank">Training Resources</a></p>
    
    <p><strong>Partner and Volunteer Resource Center:</strong><br>
    <a href="https://www.irs.gov/individuals/partner-and-volunteer-resource-center" target="_blank">Resource Center</a></p>
    
    <p><strong>Volunteer Hotline:</strong><br>
    Available January through April during tax season</p>
    
    <h3>📅 Important Dates</h3>
    <ul>
      <li><strong>November-December:</strong> Training and certification</li>
      <li><strong>January-April:</strong> Tax season (volunteer period)</li>
      <li><strong>Year-round:</strong> Site coordinator planning</li>
    </ul>
    
    <h3>🎉 Thank You for Volunteering!</h3>
    <p>By becoming a VITA volunteer, you''re making a real difference in your community. Last year, VITA volunteers:</p>
    <ul>
      <li>Prepared over 2.5 million tax returns</li>
      <li>Helped taxpayers receive $2.8 billion in refunds</li>
      <li>Saved taxpayers $400+ million in preparation fees</li>
      <li>Served communities in all 50 states</li>
    </ul>
    
    <p><strong>Ready to get started?</strong><br>
    <a href="https://freetaxassistance.for.irs.gov/s/sign-up-form" target="_blank" class="btn btn-primary btn-lg">Sign Up Now</a></p>'
  ) ON CONFLICT DO NOTHING;
  
END$$;

-- Verify the course was created
SELECT 
  p.title as program,
  c.code,
  c.title as course,
  COUNT(l.id) as lesson_count
FROM programs p
JOIN courses c ON c.program_id = p.id
LEFT JOIN lessons l ON l.course_id = c.id
WHERE p.slug = 'irs-vita-tax-preparation'
GROUP BY p.title, c.code, c.title;


-- =============================================
-- SETUP COMPLETE!
-- =============================================
