name = "lms-webhook"
main = "src/index.ts"
compatibility_date = "2024-10-14"

# Environment variables (set these in Cloudflare dashboard)
[vars]
# SUPABASE_URL = "https://your-project.supabase.co"

# Secrets (set with: wrangler secret put SECRET_NAME)
# SUPABASE_SERVICE_ROLE_KEY
# WEBHOOK_SECRET (optional)

# Routes
routes = [
  { pattern = "*/lms/webhook", zone_name = "yourdomain.com" }
]

# Or use custom domain
# routes = [
#   { pattern = "lms.yourdomain.com/webhook" }
# ]
