/* AUTO-GENERATED by scripts/generate-routes.mjs – DO NOT EDIT */
import React, { lazy, Suspense } from 'react';
import { Routes, Route } from 'react-router-dom';
import SiteLayout from '../layouts/SiteLayout';

class RouteErrorBoundary extends React.Component<{children: React.ReactNode}, {e: Error | null}> {
  constructor(props: {children: React.ReactNode}) {
    super(props);
    this.state = {e: null};
  }
  static getDerivedStateFromError(error: Error) {
    return {e: error};
  }
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    console.error('Route error:', error, errorInfo);
  }
  render() {
    return this.state.e
      ? React.createElement('pre', null, String(this.state.e?.message || this.state.e))
      : this.props.children;
  }
}
const Fallback = () => <div className="min-h-screen grid place-items-center">Loading…</div>;

const Page_0 = lazy(() => import('../pages/AITutor.jsx'));
const Page_1 = lazy(() => import('../pages/About.tsx'));
const Page_2 = lazy(() => import('../pages/Accessibility.jsx'));
const Page_3 = lazy(() => import('../pages/AccessibilitySettings.jsx'));
const Page_4 = lazy(() => import('../pages/Account.jsx'));
const Page_5 = lazy(() => import('../pages/AdminConsole.jsx'));
const Page_6 = lazy(() => import('../pages/AdminDashboard.jsx'));
const Page_7 = lazy(() => import('../pages/Analytics.jsx'));
const Page_8 = lazy(() => import('../pages/AnalyticsDashboard.jsx'));
const Page_9 = lazy(() => import('../pages/AnalyticsDashboardRUM.tsx'));
const Page_10 = lazy(() => import('../pages/ApplyPage.tsx'));
const Page_11 = lazy(() => import('../pages/ApplyScholarship.tsx'));
const Page_12 = lazy(() => import('../pages/ApplySuccessPage.tsx'));
const Page_13 = lazy(() => import('../pages/Assignment.jsx'));
const Page_14 = lazy(() => import('../pages/AuthCallback.jsx'));
const Page_15 = lazy(() => import('../pages/AutopilotAdmin.tsx'));
const Page_16 = lazy(() => import('../pages/BingSiteVerification.jsx'));
const Page_17 = lazy(() => import('../pages/Blog.tsx'));
const Page_18 = lazy(() => import('../pages/Branding.jsx'));
const Page_19 = lazy(() => import('../pages/BusinessHub.jsx'));
const Page_20 = lazy(() => import('../pages/CPRFirstAidTraining.jsx'));
const Page_21 = lazy(() => import('../pages/CRMDashboardPage.tsx'));
const Page_22 = lazy(() => import('../pages/Calendar.jsx'));
const Page_23 = lazy(() => import('../pages/CertificatePage.tsx'));
const Page_24 = lazy(() => import('../pages/Certificates.jsx'));
const Page_25 = lazy(() => import('../pages/CertiportTestingCenter.jsx'));
const Page_26 = lazy(() => import('../pages/CloneLanding.jsx'));
const Page_27 = lazy(() => import('../pages/Community.jsx'));
const Page_28 = lazy(() => import('../pages/CommunityHub.jsx'));
const Page_29 = lazy(() => import('../pages/Compliance.tsx'));
const Page_30 = lazy(() => import('../pages/Connect.tsx'));
const Page_31 = lazy(() => import('../pages/Contact.tsx'));
const Page_32 = lazy(() => import('../pages/Course.jsx'));
const Page_33 = lazy(() => import('../pages/CourseBuilder.jsx'));
const Page_34 = lazy(() => import('../pages/CourseCatalog.jsx'));
const Page_35 = lazy(() => import('../pages/CourseDetail.jsx'));
const Page_36 = lazy(() => import('../pages/CourseLibrary.jsx'));
const Page_37 = lazy(() => import('../pages/CurriculumUpload.jsx'));
const Page_38 = lazy(() => import('../pages/Docs.jsx'));
const Page_39 = lazy(() => import('../pages/Donate.tsx'));
const Page_40 = lazy(() => import('../pages/DonateSuccess.tsx'));
const Page_41 = lazy(() => import('../pages/DurableAI.jsx'));
const Page_42 = lazy(() => import('../pages/DurableConsole.tsx'));
const Page_43 = lazy(() => import('../pages/DurableFeatures.jsx'));
const Page_44 = lazy(() => import('../pages/DurableLanding.jsx'));
const Page_45 = lazy(() => import('../pages/DurablePricing.jsx'));
const Page_46 = lazy(() => import('../pages/DurableTemplates.jsx'));
const Page_47 = lazy(() => import('../pages/EFHLanding.tsx'));
const Page_48 = lazy(() => import('../pages/Ecommerce.jsx'));
const Page_49 = lazy(() => import('../pages/Ecosystem.jsx'));
const Page_50 = lazy(() => import('../pages/EducatorHub.jsx'));
const Page_51 = lazy(() => import('../pages/Elevate.tsx'));
const Page_52 = lazy(() => import('../pages/ElevateBrain.jsx'));
const Page_53 = lazy(() => import('../pages/Email.jsx'));
const Page_54 = lazy(() => import('../pages/FAQ.tsx'));
const Page_55 = lazy(() => import('../pages/FileManager.jsx'));
const Page_56 = lazy(() => import('../pages/ForgotPassword.jsx'));
const Page_57 = lazy(() => import('../pages/Forms.jsx'));
const Page_58 = lazy(() => import('../pages/FullSailLanding.jsx'));
const Page_59 = lazy(() => import('../pages/FundingImpact.jsx'));
const Page_60 = lazy(() => import('../pages/GetStarted.tsx'));
const Page_61 = lazy(() => import('../pages/GoogleAnalyticsSetup.jsx'));
const Page_62 = lazy(() => import('../pages/GoogleSiteVerification.jsx'));
const Page_63 = lazy(() => import('../pages/Government.jsx'));
const Page_64 = lazy(() => import('../pages/GradeBook.jsx'));
const Page_65 = lazy(() => import('../pages/Groups.jsx'));
const Page_66 = lazy(() => import('../pages/Home-Durable.tsx'));
const Page_67 = lazy(() => import('../pages/Home.jsx'));
const Page_68 = lazy(() => import('../pages/Home.tsx'));
const Page_69 = lazy(() => import('../pages/HomePage.tsx'));
const Page_70 = lazy(() => import('../pages/HomeProduction.tsx'));
const Page_71 = lazy(() => import('../pages/HomeProfessional.jsx'));
const Page_72 = lazy(() => import('../pages/Hub.tsx'));
const Page_73 = lazy(() => import('../pages/Instructor.jsx'));
const Page_74 = lazy(() => import('../pages/InstructorCourseCreate.jsx'));
const Page_75 = lazy(() => import('../pages/InstructorEdit.jsx'));
const Page_76 = lazy(() => import('../pages/InstructorNew.jsx'));
const Page_77 = lazy(() => import('../pages/Integrations.jsx'));
const Page_78 = lazy(() => import('../pages/IntuitTaxBookkeeping.jsx'));
const Page_79 = lazy(() => import('../pages/InvoiceCreatorPage.tsx'));
const Page_80 = lazy(() => import('../pages/InvoiceListPage.tsx'));
const Page_81 = lazy(() => import('../pages/JobReadyIndy.jsx'));
const Page_82 = lazy(() => import('../pages/LMS.tsx'));
const Page_83 = lazy(() => import('../pages/LMSCourses.tsx'));
const Page_84 = lazy(() => import('../pages/LMSDashboard.jsx'));
const Page_85 = lazy(() => import('../pages/LMSLanding.jsx'));
const Page_86 = lazy(() => import('../pages/LiveClassRoom.jsx'));
const Page_87 = lazy(() => import('../pages/LiveClassSchedule.jsx'));
const Page_88 = lazy(() => import('../pages/Login.jsx'));
const Page_89 = lazy(() => import('../pages/MainLanding.jsx'));
const Page_90 = lazy(() => import('../pages/MobileApp.jsx'));
const Page_91 = lazy(() => import('../pages/MyCertificates.tsx'));
const Page_92 = lazy(() => import('../pages/NCCERCareerStarter.jsx'));
const Page_93 = lazy(() => import('../pages/NotAuthorized.tsx'));
const Page_94 = lazy(() => import('../pages/NotFound.tsx'));
const Page_95 = lazy(() => import('../pages/NotebookLM.jsx'));
const Page_96 = lazy(() => import('../pages/NotificationCenter.jsx'));
const Page_97 = lazy(() => import('../pages/NotificationSettings.jsx'));
const Page_98 = lazy(() => import('../pages/Notifications.jsx'));
const Page_99 = lazy(() => import('../pages/OurPartners.jsx'));
const Page_100 = lazy(() => import('../pages/Partners.jsx'));
const Page_101 = lazy(() => import('../pages/PartnersPage.tsx'));
const Page_102 = lazy(() => import('../pages/Pay.tsx'));
const Page_103 = lazy(() => import('../pages/PaymentCancelled.tsx'));
const Page_104 = lazy(() => import('../pages/PaymentSuccess.tsx'));
const Page_105 = lazy(() => import('../pages/Philanthropy.jsx'));
const Page_106 = lazy(() => import('../pages/PrivacyPage.tsx'));
const Page_107 = lazy(() => import('../pages/PrivacyPolicy.jsx'));
const Page_108 = lazy(() => import('../pages/ProfessionalHome.jsx'));
const Page_109 = lazy(() => import('../pages/ProfessionalSite.jsx'));
const Page_110 = lazy(() => import('../pages/Profile.jsx'));
const Page_111 = lazy(() => import('../pages/ProgramDetail.tsx'));
const Page_112 = lazy(() => import('../pages/ProgramPage.tsx'));
const Page_113 = lazy(() => import('../pages/Programs.tsx'));
const Page_114 = lazy(() => import('../pages/ProgramsDurable.jsx'));
const Page_115 = lazy(() => import('../pages/ProgramsIndex.tsx'));
const Page_116 = lazy(() => import('../pages/ProgramsPage.tsx'));
const Page_117 = lazy(() => import('../pages/Quiz.jsx'));
const Page_118 = lazy(() => import('../pages/QuizBuilder.jsx'));
const Page_119 = lazy(() => import('../pages/QuizResults.jsx'));
const Page_120 = lazy(() => import('../pages/QuizTake.jsx'));
const Page_121 = lazy(() => import('../pages/RefundPolicy.jsx'));
const Page_122 = lazy(() => import('../pages/ResetPassword.tsx'));
const Page_123 = lazy(() => import('../pages/SearchResults.jsx'));
const Page_124 = lazy(() => import('../pages/SereneComfortCare.jsx'));
const Page_125 = lazy(() => import('../pages/Services.tsx'));
const Page_126 = lazy(() => import('../pages/Settings.jsx'));
const Page_127 = lazy(() => import('../pages/Sheets.jsx'));
const Page_128 = lazy(() => import('../pages/Signup.jsx'));
const Page_129 = lazy(() => import('../pages/Sitemap.tsx'));
const Page_130 = lazy(() => import('../pages/Sites.jsx'));
const Page_131 = lazy(() => import('../pages/Slides.jsx'));
const Page_132 = lazy(() => import('../pages/SocialMediaManager.tsx'));
const Page_133 = lazy(() => import('../pages/StaffPanel.jsx'));
const Page_134 = lazy(() => import('../pages/Student.jsx'));
const Page_135 = lazy(() => import('../pages/StudentDashboard.jsx'));
const Page_136 = lazy(() => import('../pages/StudentGrades.jsx'));
const Page_137 = lazy(() => import('../pages/StudentHandbook.jsx'));
const Page_138 = lazy(() => import('../pages/StudentHub.jsx'));
const Page_139 = lazy(() => import('../pages/StudentPortal.tsx'));
const Page_140 = lazy(() => import('../pages/StudentPortalLMS.jsx'));
const Page_141 = lazy(() => import('../pages/Support.jsx'));
const Page_142 = lazy(() => import('../pages/TermsOfService.jsx'));
const Page_143 = lazy(() => import('../pages/TermsPage.tsx'));
const Page_144 = lazy(() => import('../pages/ThankYou.tsx'));
const Page_145 = lazy(() => import('../pages/UrbanBuildCrew.jsx'));
const Page_146 = lazy(() => import('../pages/UserManagement.jsx'));
const Page_147 = lazy(() => import('../pages/VITAProgram.jsx'));
const Page_148 = lazy(() => import('../pages/VITATaxCertification.jsx'));
const Page_149 = lazy(() => import('../pages/VerifyCertificate.tsx'));
const Page_150 = lazy(() => import('../pages/VerifyCertificatePage.tsx'));
const Page_151 = lazy(() => import('../pages/VerifyEmail.jsx'));
const Page_152 = lazy(() => import('../pages/VideoMeeting.jsx'));
const Page_153 = lazy(() => import('../pages/Vids.jsx'));
const Page_154 = lazy(() => import('../pages/WebsiteBuilder.jsx'));
const Page_155 = lazy(() => import('../pages/admin/AutopilotTasks.tsx'));
const Page_156 = lazy(() => import('../pages/auth/Account.tsx'));
const Page_157 = lazy(() => import('../pages/auth/ForgotPassword.tsx'));
const Page_158 = lazy(() => import('../pages/auth/Login.tsx'));
const Page_159 = lazy(() => import('../pages/auth/Signup.tsx'));
const Page_160 = lazy(() => import('../pages/instructor/CourseEditor.tsx'));
const Page_161 = lazy(() => import('../pages/instructor/InstructorDashboard.tsx'));
const Page_162 = lazy(() => import('../pages/instructor/LessonManager.tsx'));
const Page_163 = lazy(() => import('../pages/legal/DMCA.tsx'));
const Page_164 = lazy(() => import('../pages/legal/LegalIPNotice.tsx'));
const Page_165 = lazy(() => import('../pages/legal/Privacy.tsx'));
const Page_166 = lazy(() => import('../pages/legal/TermsOfUse.tsx'));
const Page_167 = lazy(() => import('../pages/lms/ClientSafetyCertification.jsx'));
const Page_168 = lazy(() => import('../pages/lms/CoursePage.tsx'));
const Page_169 = lazy(() => import('../pages/lms/CoursesIndex.tsx'));
const Page_170 = lazy(() => import('../pages/lms/Dashboard.tsx'));
const Page_171 = lazy(() => import('../pages/lms/DiscussionsPage.tsx'));
const Page_172 = lazy(() => import('../pages/lms/EnrollmentSuccess.jsx'));
const Page_173 = lazy(() => import('../pages/lms/LessonPage.jsx'));
const Page_174 = lazy(() => import('../pages/lms/LessonPage.tsx'));
const Page_175 = lazy(() => import('../pages/lms/MiladyBarberApprenticeship.jsx'));
const Page_176 = lazy(() => import('../pages/lms/MiladyBarberCourse.jsx'));
const Page_177 = lazy(() => import('../pages/lms/MiladyRISEEnrollment.jsx'));
const Page_178 = lazy(() => import('../pages/lms/MiladyRISEIntegration.jsx'));
const Page_179 = lazy(() => import('../pages/lms/MyCertificatesPage.tsx'));
const Page_180 = lazy(() => import('../pages/lms/QuizBlock.tsx'));
const Page_181 = lazy(() => import('../pages/programs/BarberPage.tsx'));
const Page_182 = lazy(() => import('../pages/programs/BuildingTechPage.tsx'));
const Page_183 = lazy(() => import('../pages/programs/CPRSPage.tsx'));
const Page_184 = lazy(() => import('../pages/programs/DigitalSkillsPage.tsx'));
const Page_185 = lazy(() => import('../pages/programs/DrugTestingPage.tsx'));
const Page_186 = lazy(() => import('../pages/programs/HVACPage.tsx'));
const Page_187 = lazy(() => import('../pages/programs/HealthcarePage.tsx'));
const Page_188 = lazy(() => import('../pages/programs/LeadershipPage.tsx'));
const Page_189 = lazy(() => import('../pages/programs/ProgramTemplate.tsx'));
const Page_190 = lazy(() => import('../pages/sisters/MentorDirectory.jsx'));
const Page_191 = lazy(() => import('../pages/sisters/MentorSignup.jsx'));
const Page_192 = lazy(() => import('../pages/sisters/Mentorship-old.jsx'));
const Page_193 = lazy(() => import('../pages/sisters/Mentorship.jsx'));
const Page_194 = lazy(() => import('../pages/sisters/PeerSupport.jsx'));
const Page_195 = lazy(() => import('../pages/sisters/Volunteer.jsx'));
const Page_196 = lazy(() => import('../pages/sisters/VolunteerOpportunities.jsx'));
const Page_197 = lazy(() => import('../pages/sisters/VolunteerStories.jsx'));
const Page_198 = lazy(() => import('../pages/sisters/Wellness.jsx'));
const Page_199 = lazy(() => import('../pages/sisters/WellnessResources.jsx'));

export default function AppRoutes(){
  return (
    <RouteErrorBoundary>
      <Suspense fallback={<Fallback />}>
        <SiteLayout>
          <Routes>
            <Route path="/aitutor" element={<Page_0 />} />
            <Route path="/about" element={<Page_1 />} />
            <Route path="/accessibility" element={<Page_2 />} />
            <Route path="/accessibility-settings" element={<Page_3 />} />
            <Route path="/account" element={<Page_4 />} />
            <Route path="/admin-console" element={<Page_5 />} />
            <Route path="/admin-dashboard" element={<Page_6 />} />
            <Route path="/analytics" element={<Page_7 />} />
            <Route path="/analytics-dashboard" element={<Page_8 />} />
            <Route path="/analytics-dashboard-rum" element={<Page_9 />} />
            <Route path="/apply-page" element={<Page_10 />} />
            <Route path="/apply-scholarship" element={<Page_11 />} />
            <Route path="/apply-success-page" element={<Page_12 />} />
            <Route path="/assignment" element={<Page_13 />} />
            <Route path="/auth-callback" element={<Page_14 />} />
            <Route path="/autopilot-admin" element={<Page_15 />} />
            <Route path="/bing-site-verification" element={<Page_16 />} />
            <Route path="/blog" element={<Page_17 />} />
            <Route path="/branding" element={<Page_18 />} />
            <Route path="/business-hub" element={<Page_19 />} />
            <Route path="/cprfirst-aid-training" element={<Page_20 />} />
            <Route path="/crmdashboard-page" element={<Page_21 />} />
            <Route path="/calendar" element={<Page_22 />} />
            <Route path="/certificate-page" element={<Page_23 />} />
            <Route path="/certificates" element={<Page_24 />} />
            <Route path="/certiport-testing-center" element={<Page_25 />} />
            <Route path="/clone-landing" element={<Page_26 />} />
            <Route path="/community" element={<Page_27 />} />
            <Route path="/community-hub" element={<Page_28 />} />
            <Route path="/compliance" element={<Page_29 />} />
            <Route path="/connect" element={<Page_30 />} />
            <Route path="/contact" element={<Page_31 />} />
            <Route path="/course" element={<Page_32 />} />
            <Route path="/course-builder" element={<Page_33 />} />
            <Route path="/course-catalog" element={<Page_34 />} />
            <Route path="/course-detail" element={<Page_35 />} />
            <Route path="/course-library" element={<Page_36 />} />
            <Route path="/curriculum-upload" element={<Page_37 />} />
            <Route path="/docs" element={<Page_38 />} />
            <Route path="/donate" element={<Page_39 />} />
            <Route path="/donate/success" element={<Page_40 />} />
            <Route path="/durable-ai" element={<Page_41 />} />
            <Route path="/durable-console" element={<Page_42 />} />
            <Route path="/durable-features" element={<Page_43 />} />
            <Route path="/durable-landing" element={<Page_44 />} />
            <Route path="/durable-pricing" element={<Page_45 />} />
            <Route path="/durable-templates" element={<Page_46 />} />
            <Route path="/efh-landing" element={<Page_47 />} />
            <Route path="/ecommerce" element={<Page_48 />} />
            <Route path="/ecosystem" element={<Page_49 />} />
            <Route path="/educator-hub" element={<Page_50 />} />
            <Route path="/elevate" element={<Page_51 />} />
            <Route path="/elevate-brain" element={<Page_52 />} />
            <Route path="/email" element={<Page_53 />} />
            <Route path="/faq" element={<Page_54 />} />
            <Route path="/file-manager" element={<Page_55 />} />
            <Route path="/forgot-password" element={<Page_56 />} />
            <Route path="/forms" element={<Page_57 />} />
            <Route path="/full-sail-landing" element={<Page_58 />} />
            <Route path="/funding-impact" element={<Page_59 />} />
            <Route path="/get-started" element={<Page_60 />} />
            <Route path="/google-analytics-setup" element={<Page_61 />} />
            <Route path="/google-site-verification" element={<Page_62 />} />
            <Route path="/government" element={<Page_63 />} />
            <Route path="/grade-book" element={<Page_64 />} />
            <Route path="/groups" element={<Page_65 />} />
            <Route path="/home-durable" element={<Page_66 />} />
            <Route path="/" element={<Page_67 />} />
            <Route path="/home" element={<Page_68 />} />
            <Route path="/home-page" element={<Page_69 />} />
            <Route path="/home-production" element={<Page_70 />} />
            <Route path="/home-professional" element={<Page_71 />} />
            <Route path="/hub" element={<Page_72 />} />
            <Route path="/instructor" element={<Page_73 />} />
            <Route path="/instructor-course-create" element={<Page_74 />} />
            <Route path="/instructor-edit" element={<Page_75 />} />
            <Route path="/instructor-new" element={<Page_76 />} />
            <Route path="/integrations" element={<Page_77 />} />
            <Route path="/intuit-tax-bookkeeping" element={<Page_78 />} />
            <Route path="/invoice-creator-page" element={<Page_79 />} />
            <Route path="/invoice-list-page" element={<Page_80 />} />
            <Route path="/job-ready-indy" element={<Page_81 />} />
            <Route path="/lms" element={<Page_82 />} />
            <Route path="/lms/courses" element={<Page_83 />} />
            <Route path="/lmsdashboard" element={<Page_84 />} />
            <Route path="/lmslanding" element={<Page_85 />} />
            <Route path="/live-class-room" element={<Page_86 />} />
            <Route path="/live-class-schedule" element={<Page_87 />} />
            <Route path="/login" element={<Page_88 />} />
            <Route path="/main-landing" element={<Page_89 />} />
            <Route path="/mobile-app" element={<Page_90 />} />
            <Route path="/my-certificates" element={<Page_91 />} />
            <Route path="/nccercareer-starter" element={<Page_92 />} />
            <Route path="/not-authorized" element={<Page_93 />} />
            <Route path="/notebook-lm" element={<Page_95 />} />
            <Route path="/notification-center" element={<Page_96 />} />
            <Route path="/notification-settings" element={<Page_97 />} />
            <Route path="/notifications" element={<Page_98 />} />
            <Route path="/our-partners" element={<Page_99 />} />
            <Route path="/partners" element={<Page_100 />} />
            <Route path="/partners-page" element={<Page_101 />} />
            <Route path="/pay" element={<Page_102 />} />
            <Route path="/payment-cancelled" element={<Page_103 />} />
            <Route path="/payment-success" element={<Page_104 />} />
            <Route path="/philanthropy" element={<Page_105 />} />
            <Route path="/privacy-page" element={<Page_106 />} />
            <Route path="/privacy-policy" element={<Page_107 />} />
            <Route path="/professional-home" element={<Page_108 />} />
            <Route path="/professional-site" element={<Page_109 />} />
            <Route path="/profile" element={<Page_110 />} />
            <Route path="/programs/:slug" element={<Page_111 />} />
            <Route path="/program-page" element={<Page_112 />} />
            <Route path="/programs" element={<Page_113 />} />
            <Route path="/programs-durable" element={<Page_114 />} />
            <Route path="/programs-index" element={<Page_115 />} />
            <Route path="/programs-page" element={<Page_116 />} />
            <Route path="/quiz" element={<Page_117 />} />
            <Route path="/quiz-builder" element={<Page_118 />} />
            <Route path="/quiz-results" element={<Page_119 />} />
            <Route path="/quiz-take" element={<Page_120 />} />
            <Route path="/refund-policy" element={<Page_121 />} />
            <Route path="/reset-password" element={<Page_122 />} />
            <Route path="/search-results" element={<Page_123 />} />
            <Route path="/serene-comfort-care" element={<Page_124 />} />
            <Route path="/services" element={<Page_125 />} />
            <Route path="/settings" element={<Page_126 />} />
            <Route path="/sheets" element={<Page_127 />} />
            <Route path="/signup" element={<Page_128 />} />
            <Route path="/sitemap" element={<Page_129 />} />
            <Route path="/sites" element={<Page_130 />} />
            <Route path="/slides" element={<Page_131 />} />
            <Route path="/social-media-manager" element={<Page_132 />} />
            <Route path="/staff-panel" element={<Page_133 />} />
            <Route path="/student" element={<Page_134 />} />
            <Route path="/student-dashboard" element={<Page_135 />} />
            <Route path="/student-grades" element={<Page_136 />} />
            <Route path="/student-handbook" element={<Page_137 />} />
            <Route path="/student-hub" element={<Page_138 />} />
            <Route path="/student-portal" element={<Page_139 />} />
            <Route path="/student-portal-lms" element={<Page_140 />} />
            <Route path="/support" element={<Page_141 />} />
            <Route path="/terms-of-service" element={<Page_142 />} />
            <Route path="/terms-page" element={<Page_143 />} />
            <Route path="/thank-you" element={<Page_144 />} />
            <Route path="/urban-build-crew" element={<Page_145 />} />
            <Route path="/user-management" element={<Page_146 />} />
            <Route path="/vitaprogram" element={<Page_147 />} />
            <Route path="/vitatax-certification" element={<Page_148 />} />
            <Route path="/verify" element={<Page_149 />} />
            <Route path="/verify-certificate-page" element={<Page_150 />} />
            <Route path="/verify-email" element={<Page_151 />} />
            <Route path="/video-meeting" element={<Page_152 />} />
            <Route path="/vids" element={<Page_153 />} />
            <Route path="/website-builder" element={<Page_154 />} />
            <Route path="/admin/autopilot-tasks" element={<Page_155 />} />
            <Route path="/auth/account" element={<Page_156 />} />
            <Route path="/auth/forgot-password" element={<Page_157 />} />
            <Route path="/auth/login" element={<Page_158 />} />
            <Route path="/auth/signup" element={<Page_159 />} />
            <Route path="/instructor/course-editor" element={<Page_160 />} />
            <Route path="/instructor/instructor-dashboard" element={<Page_161 />} />
            <Route path="/instructor/lesson-manager" element={<Page_162 />} />
            <Route path="/legal/dmca" element={<Page_163 />} />
            <Route path="/legal/legal-ipnotice" element={<Page_164 />} />
            <Route path="/legal/privacy" element={<Page_165 />} />
            <Route path="/legal/terms-of-use" element={<Page_166 />} />
            <Route path="/lms/client-safety-certification" element={<Page_167 />} />
            <Route path="/lms/course/:courseId" element={<Page_168 />} />
            <Route path="/lms/courses-index" element={<Page_169 />} />
            <Route path="/lms/dashboard" element={<Page_170 />} />
            <Route path="/lms/discussions-page" element={<Page_171 />} />
            <Route path="/lms/enrollment-success" element={<Page_172 />} />
            <Route path="/lms/lesson-page" element={<Page_173 />} />
            <Route path="/lms/lesson/:lessonId" element={<Page_174 />} />
            <Route path="/lms/milady-barber-apprenticeship" element={<Page_175 />} />
            <Route path="/lms/milady-barber-course" element={<Page_176 />} />
            <Route path="/lms/milady-riseenrollment" element={<Page_177 />} />
            <Route path="/lms/milady-riseintegration" element={<Page_178 />} />
            <Route path="/lms/my-certificates-page" element={<Page_179 />} />
            <Route path="/lms/quiz-block" element={<Page_180 />} />
            <Route path="/programs/barber-page" element={<Page_181 />} />
            <Route path="/programs/building-tech-page" element={<Page_182 />} />
            <Route path="/programs/cprspage" element={<Page_183 />} />
            <Route path="/programs/digital-skills-page" element={<Page_184 />} />
            <Route path="/programs/drug-testing-page" element={<Page_185 />} />
            <Route path="/programs/hvacpage" element={<Page_186 />} />
            <Route path="/programs/healthcare-page" element={<Page_187 />} />
            <Route path="/programs/leadership-page" element={<Page_188 />} />
            <Route path="/programs/program-template" element={<Page_189 />} />
            <Route path="/sisters/mentor-directory" element={<Page_190 />} />
            <Route path="/sisters/mentor-signup" element={<Page_191 />} />
            <Route path="/sisters/mentorship-old" element={<Page_192 />} />
            <Route path="/sisters/mentorship" element={<Page_193 />} />
            <Route path="/sisters/peer-support" element={<Page_194 />} />
            <Route path="/sisters/volunteer" element={<Page_195 />} />
            <Route path="/sisters/volunteer-opportunities" element={<Page_196 />} />
            <Route path="/sisters/volunteer-stories" element={<Page_197 />} />
            <Route path="/sisters/wellness" element={<Page_198 />} />
            <Route path="/sisters/wellness-resources" element={<Page_199 />} />
            <Route path="*" element={<Page_94 />} />
          </Routes>
        </SiteLayout>
      </Suspense>
    </RouteErrorBoundary>
  );
}
