/* AUTO-GENERATED by scripts/generate-routes.mjs – DO NOT EDIT */
import React, { lazy, Suspense } from 'react';
import { Routes, Route } from 'react-router-dom';
import SiteLayout from '../layouts/SiteLayout';

class RouteErrorBoundary extends React.Component {
  constructor(p) {
    super(p);
    this.state = { e: null };
  }
  static getDerivedStateFromError(e) {
    return { e };
  }
  componentDidCatch(e, i) {
    console.error('Route error:', e, i);
  }
  render() {
    return this.state.e
      ? React.createElement(
          'pre',
          null,
          String(this.state.e?.message || this.state.e)
        )
      : this.props.children;
  }
}
const Fallback = () => (
  <div className="min-h-screen grid place-items-center">Loading…</div>
);

const Page_0 = lazy(() => import('../pages/AITutor.jsx'));
const Page_1 = lazy(() => import('../pages/About.jsx'));
const Page_2 = lazy(() => import('../pages/Accessibility.jsx'));
const Page_3 = lazy(() => import('../pages/AccessibilitySettings.jsx'));
const Page_4 = lazy(() => import('../pages/Account.jsx'));
const Page_5 = lazy(() => import('../pages/AdminConsole.jsx'));
const Page_6 = lazy(() => import('../pages/AdminDashboard.jsx'));
const Page_7 = lazy(() => import('../pages/Analytics.jsx'));
const Page_8 = lazy(() => import('../pages/AnalyticsDashboard.jsx'));
const Page_9 = lazy(() => import('../pages/AnalyticsDashboardRUM.tsx'));
const Page_10 = lazy(() => import('../pages/ApplyScholarship.tsx'));
const Page_11 = lazy(() => import('../pages/Assignment.jsx'));
const Page_12 = lazy(() => import('../pages/AutopilotAdmin.tsx'));
const Page_13 = lazy(() => import('../pages/BingSiteVerification.jsx'));
const Page_14 = lazy(() => import('../pages/Branding.jsx'));
const Page_15 = lazy(() => import('../pages/BusinessHub.jsx'));
const Page_16 = lazy(() => import('../pages/Calendar.jsx'));
const Page_17 = lazy(() => import('../pages/CertificatePage.tsx'));
const Page_18 = lazy(() => import('../pages/Certificates.jsx'));
const Page_19 = lazy(() => import('../pages/CloneLanding.jsx'));
const Page_20 = lazy(() => import('../pages/Community.jsx'));
const Page_21 = lazy(() => import('../pages/CommunityHub.jsx'));
const Page_22 = lazy(() => import('../pages/Compliance.tsx'));
const Page_23 = lazy(() => import('../pages/Connect.tsx'));
const Page_24 = lazy(() => import('../pages/Course.jsx'));
const Page_25 = lazy(() => import('../pages/CourseBuilder.jsx'));
const Page_26 = lazy(() => import('../pages/CourseCatalog.jsx'));
const Page_27 = lazy(() => import('../pages/CourseDetail.jsx'));
const Page_28 = lazy(() => import('../pages/CourseLibrary.jsx'));
const Page_29 = lazy(() => import('../pages/CurriculumUpload.jsx'));
const Page_30 = lazy(() => import('../pages/Docs.jsx'));
const Page_31 = lazy(() => import('../pages/Donate.tsx'));
const Page_32 = lazy(() => import('../pages/DonatePage.tsx'));
const Page_33 = lazy(() => import('../pages/DonateSuccess.tsx'));
const Page_34 = lazy(() => import('../pages/DurableAI.jsx'));
const Page_35 = lazy(() => import('../pages/DurableFeatures.jsx'));
const Page_36 = lazy(() => import('../pages/DurableLanding.jsx'));
const Page_37 = lazy(() => import('../pages/DurablePricing.jsx'));
const Page_38 = lazy(() => import('../pages/DurableTemplates.jsx'));
const Page_39 = lazy(() => import('../pages/EFHLanding.tsx'));
const Page_40 = lazy(() => import('../pages/Ecommerce.jsx'));
const Page_41 = lazy(() => import('../pages/Ecosystem.jsx'));
const Page_42 = lazy(() => import('../pages/EducatorHub.jsx'));
const Page_43 = lazy(() => import('../pages/ElevateBrain.jsx'));
const Page_44 = lazy(() => import('../pages/Email.jsx'));
const Page_45 = lazy(() => import('../pages/FileManager.jsx'));
const Page_46 = lazy(() => import('../pages/ForgotPassword.jsx'));
const Page_47 = lazy(() => import('../pages/Forms.jsx'));
const Page_48 = lazy(() => import('../pages/FullSailLanding.jsx'));
const Page_49 = lazy(() => import('../pages/FundingImpact.jsx'));
const Page_50 = lazy(() => import('../pages/GetStarted.tsx'));
const Page_51 = lazy(() => import('../pages/GoogleAnalyticsSetup.jsx'));
const Page_52 = lazy(() => import('../pages/GoogleSiteVerification.jsx'));
const Page_53 = lazy(() => import('../pages/Government.jsx'));
const Page_54 = lazy(() => import('../pages/GradeBook.jsx'));
const Page_55 = lazy(() => import('../pages/Groups.jsx'));
const Page_56 = lazy(() => import('../pages/Home.jsx'));
const Page_57 = lazy(() => import('../pages/HomePage.tsx'));
const Page_58 = lazy(() => import('../pages/Hub.tsx'));
const Page_59 = lazy(() => import('../pages/Instructor.jsx'));
const Page_60 = lazy(() => import('../pages/InstructorCourseCreate.jsx'));
const Page_61 = lazy(() => import('../pages/InstructorEdit.jsx'));
const Page_62 = lazy(() => import('../pages/InstructorNew.jsx'));
const Page_63 = lazy(() => import('../pages/Integrations.jsx'));
const Page_64 = lazy(() => import('../pages/LMS.tsx'));
const Page_65 = lazy(() => import('../pages/LMSCourses.tsx'));
const Page_66 = lazy(() => import('../pages/LMSDashboard.jsx'));
const Page_67 = lazy(() => import('../pages/LMSLanding.jsx'));
const Page_68 = lazy(() => import('../pages/LiveClassRoom.jsx'));
const Page_69 = lazy(() => import('../pages/LiveClassSchedule.jsx'));
const Page_70 = lazy(() => import('../pages/Login.jsx'));
const Page_71 = lazy(() => import('../pages/MainLanding.jsx'));
const Page_72 = lazy(() => import('../pages/MobileApp.jsx'));
const Page_73 = lazy(() => import('../pages/MyCertificates.tsx'));
const Page_74 = lazy(() => import('../pages/NotFound.tsx'));
const Page_75 = lazy(() => import('../pages/NotebookLM.jsx'));
const Page_76 = lazy(() => import('../pages/NotificationCenter.jsx'));
const Page_77 = lazy(() => import('../pages/NotificationSettings.jsx'));
const Page_78 = lazy(() => import('../pages/Notifications.jsx'));
const Page_79 = lazy(() => import('../pages/Partners.jsx'));
const Page_80 = lazy(() => import('../pages/Pay.tsx'));
const Page_81 = lazy(() => import('../pages/PaymentCancelled.tsx'));
const Page_82 = lazy(() => import('../pages/PaymentSuccess.tsx'));
const Page_83 = lazy(() => import('../pages/Philanthropy.jsx'));
const Page_84 = lazy(() => import('../pages/PrivacyPolicy.jsx'));
const Page_85 = lazy(() => import('../pages/ProfessionalHome.jsx'));
const Page_86 = lazy(() => import('../pages/ProfessionalSite.jsx'));
const Page_87 = lazy(() => import('../pages/Profile.jsx'));
const Page_88 = lazy(() => import('../pages/ProgramDetail.tsx'));
const Page_89 = lazy(() => import('../pages/ProgramPage.tsx'));
const Page_90 = lazy(() => import('../pages/Programs.tsx'));
const Page_91 = lazy(() => import('../pages/ProgramsDurable.jsx'));
const Page_92 = lazy(() => import('../pages/ProgramsIndex.tsx'));
const Page_93 = lazy(() => import('../pages/ProgramsPage.tsx'));
const Page_94 = lazy(() => import('../pages/Quiz.jsx'));
const Page_95 = lazy(() => import('../pages/QuizBuilder.jsx'));
const Page_96 = lazy(() => import('../pages/QuizResults.jsx'));
const Page_97 = lazy(() => import('../pages/QuizTake.jsx'));
const Page_98 = lazy(() => import('../pages/RefundPolicy.jsx'));
const Page_99 = lazy(() => import('../pages/ResetPassword.tsx'));
const Page_100 = lazy(() => import('../pages/SearchResults.jsx'));
const Page_101 = lazy(() => import('../pages/SereneComfortCare.jsx'));
const Page_102 = lazy(() => import('../pages/Settings.jsx'));
const Page_103 = lazy(() => import('../pages/Sheets.jsx'));
const Page_104 = lazy(() => import('../pages/Signup.jsx'));
const Page_105 = lazy(() => import('../pages/Sitemap.tsx'));
const Page_106 = lazy(() => import('../pages/Sites.jsx'));
const Page_107 = lazy(() => import('../pages/Slides.jsx'));
const Page_108 = lazy(() => import('../pages/SocialMediaManager.tsx'));
const Page_109 = lazy(() => import('../pages/Student.jsx'));
const Page_110 = lazy(() => import('../pages/StudentDashboard.jsx'));
const Page_111 = lazy(() => import('../pages/StudentGrades.jsx'));
const Page_112 = lazy(() => import('../pages/StudentHandbook.jsx'));
const Page_113 = lazy(() => import('../pages/StudentHub.jsx'));
const Page_114 = lazy(() => import('../pages/StudentPortalLMS.jsx'));
const Page_115 = lazy(() => import('../pages/Support.jsx'));
const Page_116 = lazy(() => import('../pages/TermsOfService.jsx'));
const Page_117 = lazy(() => import('../pages/TestPage.jsx'));
const Page_118 = lazy(() => import('../pages/ThankYou.tsx'));
const Page_119 = lazy(() => import('../pages/UrbanBuildCrew.jsx'));
const Page_120 = lazy(() => import('../pages/UserManagement.jsx'));
const Page_121 = lazy(() => import('../pages/VerifyCertificate.tsx'));
const Page_122 = lazy(() => import('../pages/VerifyEmail.jsx'));
const Page_123 = lazy(() => import('../pages/VideoMeeting.jsx'));
const Page_124 = lazy(() => import('../pages/Vids.jsx'));
const Page_125 = lazy(() => import('../pages/admin/AutopilotTasks.tsx'));
const Page_126 = lazy(() => import('../pages/auth/Account.tsx'));
const Page_127 = lazy(() => import('../pages/auth/ForgotPassword.tsx'));
const Page_128 = lazy(() => import('../pages/auth/Login.tsx'));
const Page_129 = lazy(() => import('../pages/auth/Signup.tsx'));
const Page_130 = lazy(() => import('../pages/instructor/CourseEditor.tsx'));
const Page_131 = lazy(
  () => import('../pages/instructor/InstructorDashboard.tsx')
);
const Page_132 = lazy(() => import('../pages/instructor/LessonManager.tsx'));
const Page_133 = lazy(() => import('../pages/lms/CoursePage.tsx'));
const Page_134 = lazy(() => import('../pages/lms/CoursesIndex.tsx'));
const Page_135 = lazy(() => import('../pages/lms/Dashboard.tsx'));
const Page_136 = lazy(() => import('../pages/lms/LessonPage.tsx'));
const Page_137 = lazy(() => import('../pages/lms/QuizBlock.tsx'));
const Page_138 = lazy(() => import('../pages/sisters/MentorDirectory.jsx'));
const Page_139 = lazy(() => import('../pages/sisters/MentorSignup.jsx'));
const Page_140 = lazy(() => import('../pages/sisters/Mentorship.jsx'));
const Page_141 = lazy(() => import('../pages/sisters/PeerSupport.jsx'));
const Page_142 = lazy(() => import('../pages/sisters/Volunteer.jsx'));
const Page_143 = lazy(
  () => import('../pages/sisters/VolunteerOpportunities.jsx')
);
const Page_144 = lazy(() => import('../pages/sisters/VolunteerStories.jsx'));
const Page_145 = lazy(() => import('../pages/sisters/Wellness.jsx'));
const Page_146 = lazy(() => import('../pages/sisters/WellnessResources.jsx'));

export default function AppRoutes() {
  return (
    <RouteErrorBoundary>
      <Suspense fallback={<Fallback />}>
        <SiteLayout>
          <Routes>
            <Route path="/aitutor" element={<Page_0 />} />
            <Route path="/about" element={<Page_1 />} />
            <Route path="/accessibility" element={<Page_2 />} />
            <Route path="/accessibility-settings" element={<Page_3 />} />
            <Route path="/account" element={<Page_4 />} />
            <Route path="/admin-console" element={<Page_5 />} />
            <Route path="/admin-dashboard" element={<Page_6 />} />
            <Route path="/analytics" element={<Page_7 />} />
            <Route path="/analytics-dashboard" element={<Page_8 />} />
            <Route path="/analytics-dashboard-rum" element={<Page_9 />} />
            <Route path="/apply-scholarship" element={<Page_10 />} />
            <Route path="/assignment" element={<Page_11 />} />
            <Route path="/autopilot-admin" element={<Page_12 />} />
            <Route path="/bing-site-verification" element={<Page_13 />} />
            <Route path="/branding" element={<Page_14 />} />
            <Route path="/business-hub" element={<Page_15 />} />
            <Route path="/calendar" element={<Page_16 />} />
            <Route path="/certificate-page" element={<Page_17 />} />
            <Route path="/certificates" element={<Page_18 />} />
            <Route path="/clone-landing" element={<Page_19 />} />
            <Route path="/community" element={<Page_20 />} />
            <Route path="/community-hub" element={<Page_21 />} />
            <Route path="/compliance" element={<Page_22 />} />
            <Route path="/connect" element={<Page_23 />} />
            <Route path="/course" element={<Page_24 />} />
            <Route path="/course-builder" element={<Page_25 />} />
            <Route path="/course-catalog" element={<Page_26 />} />
            <Route path="/course-detail" element={<Page_27 />} />
            <Route path="/course-library" element={<Page_28 />} />
            <Route path="/curriculum-upload" element={<Page_29 />} />
            <Route path="/docs" element={<Page_30 />} />
            <Route path="/donate" element={<Page_31 />} />
            <Route path="/donate-page" element={<Page_32 />} />
            <Route path="/donate/success" element={<Page_33 />} />
            <Route path="/durable-ai" element={<Page_34 />} />
            <Route path="/durable-features" element={<Page_35 />} />
            <Route path="/durable-landing" element={<Page_36 />} />
            <Route path="/durable-pricing" element={<Page_37 />} />
            <Route path="/durable-templates" element={<Page_38 />} />
            <Route path="/" element={<Page_39 />} />
            <Route path="/ecommerce" element={<Page_40 />} />
            <Route path="/ecosystem" element={<Page_41 />} />
            <Route path="/educator-hub" element={<Page_42 />} />
            <Route path="/elevate-brain" element={<Page_43 />} />
            <Route path="/email" element={<Page_44 />} />
            <Route path="/file-manager" element={<Page_45 />} />
            <Route path="/forgot-password" element={<Page_46 />} />
            <Route path="/forms" element={<Page_47 />} />
            <Route path="/full-sail-landing" element={<Page_48 />} />
            <Route path="/funding-impact" element={<Page_49 />} />
            <Route path="/get-started" element={<Page_50 />} />
            <Route path="/google-analytics-setup" element={<Page_51 />} />
            <Route path="/google-site-verification" element={<Page_52 />} />
            <Route path="/government" element={<Page_53 />} />
            <Route path="/grade-book" element={<Page_54 />} />
            <Route path="/groups" element={<Page_55 />} />
            <Route path="/home" element={<Page_56 />} />
            <Route path="/home-page" element={<Page_57 />} />
            <Route path="/hub" element={<Page_58 />} />
            <Route path="/instructor" element={<Page_59 />} />
            <Route path="/instructor-course-create" element={<Page_60 />} />
            <Route path="/instructor-edit" element={<Page_61 />} />
            <Route path="/instructor-new" element={<Page_62 />} />
            <Route path="/integrations" element={<Page_63 />} />
            <Route path="/lms" element={<Page_64 />} />
            <Route path="/lms/courses" element={<Page_65 />} />
            <Route path="/lmsdashboard" element={<Page_66 />} />
            <Route path="/lmslanding" element={<Page_67 />} />
            <Route path="/live-class-room" element={<Page_68 />} />
            <Route path="/live-class-schedule" element={<Page_69 />} />
            <Route path="/login" element={<Page_70 />} />
            <Route path="/main-landing" element={<Page_71 />} />
            <Route path="/mobile-app" element={<Page_72 />} />
            <Route path="/my-certificates" element={<Page_73 />} />
            <Route path="/notebook-lm" element={<Page_75 />} />
            <Route path="/notification-center" element={<Page_76 />} />
            <Route path="/notification-settings" element={<Page_77 />} />
            <Route path="/notifications" element={<Page_78 />} />
            <Route path="/partners" element={<Page_79 />} />
            <Route path="/pay" element={<Page_80 />} />
            <Route path="/payment-cancelled" element={<Page_81 />} />
            <Route path="/payment-success" element={<Page_82 />} />
            <Route path="/philanthropy" element={<Page_83 />} />
            <Route path="/privacy-policy" element={<Page_84 />} />
            <Route path="/professional-home" element={<Page_85 />} />
            <Route path="/professional-site" element={<Page_86 />} />
            <Route path="/profile" element={<Page_87 />} />
            <Route path="/programs/:slug" element={<Page_88 />} />
            <Route path="/program-page" element={<Page_89 />} />
            <Route path="/programs" element={<Page_90 />} />
            <Route path="/programs-durable" element={<Page_91 />} />
            <Route path="/programs-index" element={<Page_92 />} />
            <Route path="/programs-page" element={<Page_93 />} />
            <Route path="/quiz" element={<Page_94 />} />
            <Route path="/quiz-builder" element={<Page_95 />} />
            <Route path="/quiz-results" element={<Page_96 />} />
            <Route path="/quiz-take" element={<Page_97 />} />
            <Route path="/refund-policy" element={<Page_98 />} />
            <Route path="/reset-password" element={<Page_99 />} />
            <Route path="/search-results" element={<Page_100 />} />
            <Route path="/serene-comfort-care" element={<Page_101 />} />
            <Route path="/settings" element={<Page_102 />} />
            <Route path="/sheets" element={<Page_103 />} />
            <Route path="/signup" element={<Page_104 />} />
            <Route path="/sitemap" element={<Page_105 />} />
            <Route path="/sites" element={<Page_106 />} />
            <Route path="/slides" element={<Page_107 />} />
            <Route path="/social-media-manager" element={<Page_108 />} />
            <Route path="/student" element={<Page_109 />} />
            <Route path="/student-dashboard" element={<Page_110 />} />
            <Route path="/student-grades" element={<Page_111 />} />
            <Route path="/student-handbook" element={<Page_112 />} />
            <Route path="/student-hub" element={<Page_113 />} />
            <Route path="/student-portal-lms" element={<Page_114 />} />
            <Route path="/support" element={<Page_115 />} />
            <Route path="/terms-of-service" element={<Page_116 />} />
            <Route path="/test-page" element={<Page_117 />} />
            <Route path="/thank-you" element={<Page_118 />} />
            <Route path="/urban-build-crew" element={<Page_119 />} />
            <Route path="/user-management" element={<Page_120 />} />
            <Route path="/verify" element={<Page_121 />} />
            <Route path="/verify-email" element={<Page_122 />} />
            <Route path="/video-meeting" element={<Page_123 />} />
            <Route path="/vids" element={<Page_124 />} />
            <Route path="/admin/autopilot-tasks" element={<Page_125 />} />
            <Route path="/auth/account" element={<Page_126 />} />
            <Route path="/auth/forgot-password" element={<Page_127 />} />
            <Route path="/auth/login" element={<Page_128 />} />
            <Route path="/auth/signup" element={<Page_129 />} />
            <Route path="/instructor/course-editor" element={<Page_130 />} />
            <Route
              path="/instructor/instructor-dashboard"
              element={<Page_131 />}
            />
            <Route path="/instructor/lesson-manager" element={<Page_132 />} />
            <Route path="/lms/course/:courseId" element={<Page_133 />} />
            <Route path="/lms/courses-index" element={<Page_134 />} />
            <Route path="/lms/dashboard" element={<Page_135 />} />
            <Route path="/lms/lesson/:lessonId" element={<Page_136 />} />
            <Route path="/lms/quiz-block" element={<Page_137 />} />
            <Route path="/sisters/mentor-directory" element={<Page_138 />} />
            <Route path="/sisters/mentor-signup" element={<Page_139 />} />
            <Route path="/sisters/mentorship" element={<Page_140 />} />
            <Route path="/sisters/peer-support" element={<Page_141 />} />
            <Route path="/sisters/volunteer" element={<Page_142 />} />
            <Route
              path="/sisters/volunteer-opportunities"
              element={<Page_143 />}
            />
            <Route path="/sisters/volunteer-stories" element={<Page_144 />} />
            <Route path="/sisters/wellness" element={<Page_145 />} />
            <Route path="/sisters/wellness-resources" element={<Page_146 />} />
            <Route path="*" element={<Page_74 />} />
          </Routes>
        </SiteLayout>
      </Suspense>
    </RouteErrorBoundary>
  );
}
