import { MetadataRoute } from 'next';
import { createBuildTimeSupabaseClient } from '@/lib/auth';
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl =
    process.env.NEXT_PUBLIC_SITE_URL || 'https://www.elevateforhumanity.org';
  // High-priority pages for SEO
  const highPriorityPages = [
    { url: '', priority: 1.0, changeFrequency: 'daily' as const },
    {
      url: '/supersonic-fast-cash',
      priority: 1.0,
      changeFrequency: 'daily' as const,
    },
    { url: '/apply', priority: 0.9, changeFrequency: 'daily' as const },
    { url: '/programs', priority: 0.9, changeFrequency: 'weekly' as const },
    { url: '/contact', priority: 0.9, changeFrequency: 'monthly' as const },
  ];

  // Static pages - consolidated public routes
  const staticPages = [
    '/about',
    '/about/team',
    '/accessibility',
    '/academic-integrity',
    '/accreditation',
    '/ai-tutor',
    '/alumni',
    '/annual-report',
    '/app-hub',
    '/apprenticeships',
    '/blog',
    '/calendar',
    '/career-services',
    '/certificates/verify',
    '/community',
    '/compare',
    '/courses',
    '/credentials',
    '/delegate/dashboard',
    '/delegate/messages',
    '/delegate/reports',
    '/delegate/reports/export',
    '/demo',
    '/directory',
    '/docs',
    '/docs/api',
    '/ecosystem',
    '/educatorhub',
    '/email',
    '/employers',
    '/enroll',
    '/enroll/apply',
    '/enroll/course',
    '/enroll/success',
    '/faq',
    '/file-manager',
    '/financial-aid',
    '/financial-aid/apply',
    '/forgotpassword',
    '/forms',
    '/funding/dol',
    '/funding/jri',
    '/funding/wioa',
    '/funding/wrg',
    '/fundingimpact',
    '/getstarted',
    '/government',
    '/groups',
    '/help',
    '/help/tutorials',
    '/kingdomkonnect',
    '/leaderboard',
    '/learners',
    '/cookies',
    '/legal/cookies',
    '/legal/privacy',
    '/legal/terms',
    '/login',
    '/marketplace',
    '/media-showcase',
    '/mentorship',
    '/messages',
    '/micro-classes',
    '/mobile-app',
    '/notebooklm',
    '/notfound',
    '/offline',
    '/ojt-and-funding',
    '/onboarding',
    '/onboarding/handbook',
    '/onboarding/learner',
    '/onboarding/mou',
    '/onboarding/partner',
    '/onboarding/school',
    '/onboarding/staff',
    '/partner-application',
    '/partner/attendance',
    '/partner/dashboard',
    '/partners',
    '/partners/enroll',
    '/partners/mou',
    '/partners/portal',
    '/partners/training-provider',
    '/partners/workforce',
    '/philanthropy',
    '/platform',
    '/platform/partner-portal',
    '/platform/training-providers',
    '/platform/workforce-analytics',
    '/platform/workforce-boards',
    '/pricing',
    '/privacy',
    '/privacy-policy',
    '/programs',
    '/programs-full',
    '/programs-lms',
    '/programs/barber',
    '/programs/barber-apprenticeship',
    '/programs/beauty-career-educator',
    '/programs/building-maintenance',
    '/programs/building-tech',
    '/programs/business-apprenticeship',
    '/programs/business-startup-marketing',
    '/programs/cdl',
    '/programs/childcare',
    '/programs/cna',
    '/programs/cpr-certification',
    '/programs/dental-assistant',
    '/programs/ekg-technician',
    '/programs/emergency-health-safety-tech',
    '/programs/esthetics-apprenticeship',
    '/programs/hvac',
    '/programs/hvac-tech',
    '/programs/hvac-technician',
    '/programs/direct-support-professional',
    '/programs/patient-care-technician',
    '/programs/peer-recovery-coach',
    '/programs/pharmacy-technician',
    '/programs/phlebotomy',
    '/programs/professional-esthetician',
    '/programs/rise-up',
    '/programs/sterile-processing',
    '/programs/tax-prep',
    '/programs/tax-prep-financial-services',
    '/programs/tax-vita',
    '/supersonic-fast-cash',
    '/supersonic-fast-cash/upload',
    '/programs/truck-driving',
    '/programs/workforce-readiness',
    '/pwa-test',
    '/receptionist',
    '/refundpolicy',
    '/reports',
    '/resetpassword',
    '/resources',
    '/selfish-inc',
    '/serenecomfortcare',
    '/share',
    '/sheets',
    '/signup',
    '/sites',
    '/slides',
    '/staff',
    '/start',
    '/study-groups',
    '/success-stories',
    '/support',
    '/terms',
    '/terms-of-service',
    '/thankyou',
    '/training-providers',
    '/unauthorized',
    '/urbanbuildcrew',
    '/usermanagement',
    '/verify-credential',
    '/verifycertificate',
    '/verifyemail',
    '/video',
    '/videos/barber-spotlight',
    '/videos/elevate-overview',
    '/videos/employer-pipeline',
    '/vita',
    '/vita/resources',
    '/webinars',
    '/what-we-offer',
    '/wioa-eligibility',
    '/workforce-partners',
    '/videos',
    '/cm',
    '/checkout/prog-business-apprentice',
    '/checkout/prog-esthetics-apprentice',
    '/checkout/prog-tax-vita',
    '/community/admins',
    '/community/developers',
    '/community/teachers',
    '/docs/admins',
    '/docs/case-management',
    '/docs/lms',
    '/docs/program-holders',
    '/docs/reporting',
    '/docs/students',
    '/kingdom-konnect/events',
    '/kingdom-konnect/mission',
    '/kingdom-konnect/programs',
    '/partners/reentry',
    '/partners/sales',
    '/partners/technology',
    '/partners/training',
    '/serene-comfort-care/apply',
    '/serene-comfort-care/care-team',
    '/serene-comfort-care/services',
    '/solutions/distance-learning',
    '/solutions/higher-ed',
    '/solutions/k12',
    '/training/certifications',
    '/training/learning-center',
    '/urban-build-crew/about',
    '/urban-build-crew/contact',
    '/urban-build-crew/courses',
    '/community',
    '/courses/catalog',
    '/create-course',
    '/employee',
    '/funding',
    '/funding/federal-programs',
    '/funding/state-programs',
    '/home-v2',
    '/mobile',
    '/refund-policy',
    '/refunds',
    '/search',
    '/sitemap-page',
    '/all-pages',
    '/credentials',
    '/program-holders',
    '/program-holder/portal',
    '/program-holder/mou',
    '/program-holder/sign-mou',
    '/program-holder/apply',
    '/program-holder/dashboard',
    '/program-holder/training',
    '/program-holder/how-to-use',
    '/hire-graduates',
    '/what-we-do',
    '/orientation',
    '/orientation/competency-test',
    '/orientation/schedule',
    '/onboarding/employer',
    '/onboarding/employer/orientation',
    '/onboarding/school/orientation',
    '/onboarding/staff/orientation',
    '/portal',
    '/portal/student',
    '/portal/employer',
    '/portal/staff',
    '/employer/dashboard',
    '/employer/opportunities',
    '/employer/placements',
    '/employer/post-job',
    '/employer/analytics',
    '/employers/intake',
    '/app-hub',
    '/features',
    '/demos',
    '/workforce-board/dashboard',
    '/funding/how-it-works',
    '/program-holders/acknowledgement',
    '/partners/create-program',
    '/cert/verify',
    '/healthcare-administration',
  ];
  // Create high-priority sitemap entries
  const highPrioritySitemap: MetadataRoute.Sitemap = highPriorityPages.map(
    (page) => ({
      url: `${baseUrl}${page.url}`,
      lastModified: new Date(),
      changeFrequency: page.changeFrequency,
      priority: page.priority,
    })
  );

  const staticSitemap: MetadataRoute.Sitemap = staticPages.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));
  try {
    // Skip dynamic content during build if no database connection
    if (
      !process.env.NEXT_PUBLIC_SUPABASE_URL ||
      process.env.NEXT_PUBLIC_SUPABASE_URL.includes('placeholder')
    ) {
      return [...highPrioritySitemap, ...staticSitemap];
    }
    const supabase = createBuildTimeSupabaseClient();
    // Get dynamic program pages - use created_at instead of updated_at
    const { data: programs, error: programsError } = await supabase
      .from('programs')
      .select('slug, created_at')
      .eq('is_published', true);
    // Skip courses table if it doesn't exist
    const courses = null;
    if (programsError) {
      return [...highPrioritySitemap, ...staticSitemap];
    }
    const sitemap: MetadataRoute.Sitemap = [
      ...highPrioritySitemap,
      ...staticSitemap,
      // Program pages
      ...(programs || []).map((program) => ({
        url: `${baseUrl}/programs/${program.slug}`,
        lastModified: program.created_at
          ? new Date(program.created_at)
          : new Date(),
        changeFrequency: 'monthly' as const,
        priority: 0.8,
      })),
    ];
    return sitemap;
  } catch (err) {
    return [...highPrioritySitemap, ...staticSitemap];
  }
}
