import { MetadataRoute } from 'next';
import { createBuildTimeSupabaseClient } from '@/lib/auth';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = 'https://www.elevateforhumanity.org';

  // Static pages - all public routes (200+ public pages)
  const staticPages = [
    '',
    '/about',
    '/accessibility',
    '/ai-chat',
    '/ai-tutor',
    '/aitutor',
    '/alumni',
    '/analyticsdashboard',
    '/app',
    '/apply',
    '/apply/workflow',
    '/blog',
    '/board/dashboard',
    '/board/referrals',
    '/calendar',
    '/call-now',
    '/career-fair',
    '/career-services',
    '/careers',
    '/careers/interview-prep',
    '/careers/job-board',
    '/careers/resume-builder',
    '/chat',
    '/community/communityhub',
    '/compare',
    '/consumer-education',
    '/contact',
    '/courses',
    '/courses/coursebuilder',
    '/courses/coursecatalog',
    '/courses/coursedetail',
    '/curriculumupload',
    '/delegate/dashboard',
    '/delegate/messages',
    '/delegate/reports',
    '/delegate/reports/export',
    '/demo',
    '/directory',
    '/docs',
    '/docs/api',
    '/ecosystem',
    '/educatorhub',
    '/email',
    '/employers',
    '/enroll',
    '/enroll/apply',
    '/enroll/course',
    '/enroll/success',
    '/faq',
    '/file-manager',
    '/financial-aid',
    '/financial-aid/apply',
    '/forgotpassword',
    '/forms',
    '/funding/dol',
    '/funding/jri',
    '/funding/wioa',
    '/funding/wrg',
    '/fundingimpact',
    '/getstarted',
    '/government',
    '/groups',
    '/help',
    '/help/tutorials',
    '/kingdomkonnect',
    '/leaderboard',
    '/learners',
    '/cookies',
    '/legal/cookies',
    '/legal/privacy',
    '/legal/terms',
    '/login',
    '/marketplace',
    '/media-showcase',
    '/mentorship',
    '/messages',
    '/micro-classes',
    '/mobile-app',
    '/notebooklm',
    '/notfound',
    '/offline',
    '/ojt-and-funding',
    '/onboarding',
    '/onboarding/handbook',
    '/onboarding/learner',
    '/onboarding/mou',
    '/onboarding/partner',
    '/onboarding/school',
    '/onboarding/staff',
    '/partner-application',
    '/partner/attendance',
    '/partner/dashboard',
    '/partners',
    '/partners/enroll',
    '/partners/mou',
    '/partners/portal',
    '/partners/training-provider',
    '/partners/workforce',
    '/philanthropy',
    '/platform',
    '/platform/partner-portal',
    '/platform/training-providers',
    '/platform/workforce-analytics',
    '/platform/workforce-boards',
    '/pricing',
    '/privacy',
    '/privacy-policy',
    '/programs',
    '/programs-full',
    '/programs-lms',
    '/programs/barber',
    '/programs/barber-apprenticeship',
    '/programs/beauty-career-educator',
    '/programs/building-maintenance',
    '/programs/building-tech',
    '/programs/business-apprenticeship',
    '/programs/business-startup-marketing',
    '/programs/cdl',
    '/programs/childcare',
    '/programs/cna',
    '/programs/cpr-certification',
    '/programs/dental-assistant',
    '/programs/ekg-technician',
    '/programs/emergency-health-safety-tech',
    '/programs/esthetics-apprenticeship',
    '/programs/hvac',
    '/programs/hvac-tech',
    '/programs/hvac-technician',
    '/programs/medical-assistant',
    '/programs/patient-care-technician',
    '/programs/peer-recovery-coach',
    '/programs/peer-support-professional',
    '/programs/pharmacy-technician',
    '/programs/phlebotomy',
    '/programs/professional-esthetician',
    '/programs/rise-up',
    '/programs/sterile-processing',
    '/programs/tax-prep',
    '/programs/tax-prep-financial-services',
    '/programs/tax-vita',
    '/programs/truck-driving',
    '/programs/workforce-readiness',
    '/pwa-test',
    '/receptionist',
    '/refundpolicy',
    '/reports',
    '/resetpassword',
    '/resources',
    '/selfish-inc',
    '/serenecomfortcare',
    '/share',
    '/sheets',
    '/signup',
    '/sites',
    '/slides',
    '/staff',
    '/start',
    '/study-groups',
    '/success-stories',
    '/support',
    '/terms',
    '/terms-of-service',
    '/thankyou',
    '/training-providers',
    '/unauthorized',
    '/urbanbuildcrew',
    '/usermanagement',
    '/verify-credential',
    '/verifycertificate',
    '/verifyemail',
    '/video',
    '/videos/barber-spotlight',
    '/videos/elevate-overview',
    '/videos/employer-pipeline',
    '/vita',
    '/vita/resources',
    '/webinars',
    '/what-we-offer',
    '/wioa-eligibility',
    '/workforce-partners',
    '/videos',
    '/cm',
    '/checkout/prog-business-apprentice',
    '/checkout/prog-esthetics-apprentice',
    '/checkout/prog-tax-vita',
    '/community/admins',
    '/community/developers',
    '/community/teachers',
    '/docs/admins',
    '/docs/case-management',
    '/docs/lms',
    '/docs/program-holders',
    '/docs/reporting',
    '/docs/students',
    '/kingdom-konnect/events',
    '/kingdom-konnect/mission',
    '/kingdom-konnect/programs',
    '/partners/reentry',
    '/partners/sales',
    '/partners/technology',
    '/partners/training',
    '/serene-comfort-care/apply',
    '/serene-comfort-care/care-team',
    '/serene-comfort-care/services',
    '/solutions/distance-learning',
    '/solutions/higher-ed',
    '/solutions/k12',
    '/training/certifications',
    '/training/learning-center',
    '/urban-build-crew/about',
    '/urban-build-crew/contact',
    '/urban-build-crew/courses',
    '/community',
    '/courses/catalog',
    '/create-course',
    '/employee',
    '/funding',
    '/funding/federal-programs',
    '/funding/state-programs',
    '/home-v2',
    '/lms',
    '/lms/achievements',
    '/lms/adaptive',
    '/lms/analytics',
    '/lms/assignments',
    '/lms/attendance',
    '/lms/builder',
    '/lms/calendar',
    '/lms/certificates',
    '/lms/chat',
    '/lms/collaborate',
    '/lms/courses',
    '/lms/dashboard',
    '/lms/enroll',
    '/lms/enroll-workforce',
    '/lms/files',
    '/lms/forums',
    '/lms/grades',
    '/lms/help',
    '/lms/integrations',
    '/lms/learning-paths',
    '/lms/library',
    '/lms/messages',
    '/lms/notifications',
    '/lms/peer-review',
    '/lms/profile',
    '/lms/progress',
    '/lms/resources',
    '/lms/social',
    '/lms/study-groups',
    '/lms/support',
    '/mobile',
    '/refund-policy',
    '/refunds',
    '/search',
    '/sitemap-page',
    '/all-pages',
    '/credentials',
    '/program-holders',
    '/program-holder/portal',
    '/program-holder/mou',
    '/program-holder/sign-mou',
    '/program-holder/apply',
    '/program-holder/dashboard',
    '/program-holder/training',
    '/program-holder/how-to-use',
    '/hire-graduates',
    '/what-we-do',
    '/orientation',
    '/orientation/competency-test',
    '/orientation/schedule',
    '/onboarding/employer',
    '/onboarding/employer/orientation',
    '/onboarding/school/orientation',
    '/onboarding/staff/orientation',
    '/portal',
    '/portal/student',
    '/portal/employer',
    '/portal/staff',
    '/employer/dashboard',
    '/employer/opportunities',
    '/employer/placements',
    '/employer/post-job',
    '/employer/analytics',
    '/employers/intake',
    '/instructor/dashboard',
    '/instructor/analytics',
    '/app-hub',
    '/features',
    '/demos',
    '/workforce-board/dashboard',
    '/funding/how-it-works',
    '/program-holders/acknowledgement',
    '/partners/create-program',
    '/cert/verify',
    '/healthcare-administration',
  ];

  const staticSitemap: MetadataRoute.Sitemap = staticPages.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: route === '' ? 1 : 0.8,
  }));

  try {
    // Skip dynamic content during build if no database connection
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || 
        process.env.NEXT_PUBLIC_SUPABASE_URL.includes('placeholder')) {
      // console.log('Sitemap: Using static routes only (no database connection)');
      return staticSitemap;
    }

    const supabase = createBuildTimeSupabaseClient();

    // Get dynamic program pages - use created_at instead of updated_at
    const { data: programs, error: programsError } = await supabase
      .from('programs')
      .select('slug, created_at')
      .eq('is_published', true);

    // Skip courses table if it doesn't exist
    const courses = null;

    if (programsError) {
      // console.log('Sitemap: Database query failed, using static routes only');
      return staticSitemap;
    }

    const sitemap: MetadataRoute.Sitemap = [
      ...staticSitemap,

      // Program pages
      ...(programs || []).map((program) => ({
        url: `${baseUrl}/programs/${program.slug}`,
        lastModified: program.created_at ? new Date(program.created_at) : new Date(),
        changeFrequency: 'monthly' as const,
        priority: 0.7,
      })),
    ];

    return sitemap;
  } catch (err) {
    // console.log('Sitemap: Error during generation, using static routes only');
    // Fallback to static sitemap if Supabase fails
    return staticSitemap;
  }
}
