/**
 * Program data - Single source of truth
 * Update this file to change program information across the site
 * This data should match what's in Supabase and on ETPL
 */

export interface ProgramData {
  slug: string;
  name: string;
  blurb: string;
  funding: string;
  duration: string;
  image: string;
  etplApproved: boolean;
}

export const PROGRAMS: ProgramData[] = [
  {
    slug: 'tax-prep-financial-services',
    name: 'Tax Preparation & Financial Services',
    blurb: 'State Certified Earn and Learn program! Earn IRS VITA/TCE, QuickBooks Pro Advisor, and Microsoft 365 certifications in just 10 weeks. Learn federal and state tax law, bookkeeping, and financial literacy with supervised practicum at IRS-approved VITA site. Graduate ready for Tax Preparer, Bookkeeping Assistant, and Financial Service Specialist roles.',
    funding: 'WIOA • WRG • Earn and Learn',
    duration: '10 Weeks • 150 Hours',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'business-startup-marketing',
    name: 'Business Start-Up & Marketing',
    blurb: 'Launch your own business in 5 weeks! Learn entrepreneurship, digital marketing, LLC formation, and business planning with mentorship and startup support. Program includes business match stipend and laptop kit. Perfect for youth ages 16+ ready to explore self-employment and leadership pathways.',
    funding: 'WIOA • WRG',
    duration: '5 Weeks • 32 Hours',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'emergency-health-safety-tech',
    name: 'Emergency Health & Safety Technician',
    blurb: 'DOL Federally Registered Apprenticeship! Earn OSHA 10, CPR, and Emergency Medical Responder (EMR) certifications in 4 weeks. Prepare for life-saving response roles in schools, workplaces, and emergency settings. Hybrid program with 80 instructional hours.',
    funding: 'WIOA • WRG • Apprenticeship',
    duration: '4 Weeks • 80 Hours',
    image: 'https://images.unsplash.com/photo-1504813184591-01572f98c85f?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'professional-esthetician',
    name: 'Professional Esthetician & Client Services',
    blurb: 'DOL Federally Registered Apprenticeship! Master skincare, facial treatments, hair removal, and client services in 5 weeks. Earn OSHA 10, Customer Service, and Business of Retail certifications. Hands-on training in professional spa setting with career readiness and business startup support.',
    funding: 'WIOA • WRG • Apprenticeship',
    duration: '5 Weeks • 60 Hours',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'beauty-career-educator',
    name: 'Beauty & Career Educator Training',
    blurb: 'Become a licensed beauty instructor! This program prepares experienced cosmetologists and barbers to teach the next generation. Learn curriculum development, classroom management, and state licensing requirements. Perfect for those with 3+ years industry experience.',
    funding: 'WIOA • WRG',
    duration: '12-16 Weeks',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'peer-support-professional',
    name: 'Certified Peer Support Professional',
    blurb: 'Make a difference in recovery! Train to provide peer support services in behavioral health, addiction recovery, and mental health settings. Learn trauma-informed care, crisis intervention, and recovery coaching. No prior healthcare experience required.',
    funding: 'WIOA • JRI',
    duration: '6-8 Weeks',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'peer-recovery-coach',
    name: 'Certified Peer Recovery Coach (CPRC)',
    blurb: 'Support individuals in addiction recovery! Become a Certified Peer Recovery Coach and help others navigate their recovery journey. Learn motivational interviewing, relapse prevention, and community resources. Justice-involved individuals welcome.',
    funding: 'WIOA • JRI',
    duration: '45 Days • 180 Hours',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'cpr-certification',
    name: 'CPR & First Aid Certification',
    blurb: 'Life-saving skills for everyone! Earn American Heart Association CPR/AED and First Aid certifications. Perfect for healthcare workers, teachers, childcare providers, and anyone who wants to be prepared for emergencies. Classes available day, evening, and weekend.',
    funding: 'Self-Pay • Employer Sponsored',
    duration: '1 Day • 4-8 Hours',
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=600&q=80',
    etplApproved: false,
  },
  {
    slug: 'medical-assistant',
    name: 'Medical Assistant',
    blurb: 'Train for a healthcare career in just 16-24 weeks! Learn vital signs, EKG, phlebotomy, medical records, and patient care through hands-on clinical practice. Our hybrid program combines online coursework with real clinic experience, preparing you for immediate employment in doctors\' offices, hospitals, and urgent care centers. ETPL-approved and WRG/WIOA funded.',
    funding: 'WRG • WIOA • Workforce Grants',
    duration: '16–24 Weeks • Hybrid (Online + Clinical)',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'barber-apprenticeship',
    name: 'Barber Apprenticeship',
    blurb: 'Earn while you learn! This state-approved apprenticeship places you in real barbershops where you\'ll master fades, tapers, razor work, and client service while building your hours toward Indiana barber licensure. Perfect for career changers and re-entry participants. Get paid on-the-job training, business coaching, and a clear path to owning your own chair or shop.',
    funding: 'Registered Apprenticeship • WIOA • WRG',
    duration: '12–18 Months • Barbershop + Classroom',
    image: 'https://images.unsplash.com/photo-1622287162716-f311baa1a2b8?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'hvac-technician',
    name: 'HVAC Technician',
    blurb: 'Start a high-paying skilled trade career! Learn to install, repair, and maintain heating, cooling, and refrigeration systems through hands-on lab work and real job sites. Our 4-9 month hybrid program covers EPA certification, electrical basics, troubleshooting, and customer service. Graduate ready for immediate employment with HVAC companies, property management, or start your own business.',
    funding: 'Workforce Grants • Employer Sponsors • WIOA',
    duration: '4–9 Months • Hybrid (Lab + Field Training)',
    image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'building-maintenance',
    name: 'Building Maintenance Technician',
    blurb: 'Become the go-to person who keeps buildings running! Learn plumbing basics, electrical repairs, HVAC maintenance, carpentry, and safety systems through hands-on training. This 4-9 month program prepares you for steady employment with property management companies, schools, hospitals, and commercial buildings. Perfect for those who like variety and problem-solving.',
    funding: 'Workforce Grants • Apprenticeship • WIOA',
    duration: '4–9 Months • Hands-On Training',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'truck-driving',
    name: 'CDL / Truck Driving',
    blurb: 'Get your Commercial Driver\'s License in just 4-6 weeks! Our 160-hour program includes classroom instruction, range practice, and real road experience. Learn pre-trip inspections, backing maneuvers, highway driving, and DOT regulations. Graduate with your CDL Class A and immediate job placement assistance with trucking companies offering $50K+ starting salaries.',
    funding: 'Workforce Grants • Employer Sponsors • WIOA',
    duration: '4–6 Weeks (160 Hours) • Range + Road',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'workforce-readiness',
    name: 'Workforce Readiness & Re-Entry',
    blurb: 'Rebuild your career with confidence! Whether you\'re re-entering after incarceration, overcoming gaps in work history, or starting fresh, this 4-12 week program provides resume building, interview coaching, workplace skills, and direct connections to employers who hire second-chance candidates. Includes support with transportation, childcare, and work clothing.',
    funding: 'Support Services • Referrals • Case Management',
    duration: '4–12 Weeks • Flexible Coaching + Workshops',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80',
    etplApproved: false,
  },
  {
    slug: 'phlebotomy',
    name: 'Phlebotomy Technician',
    blurb: 'Launch your healthcare career in just 4-8 weeks! Learn proper blood draw techniques, patient interaction, lab safety, and specimen handling. Our hands-on program includes clinical rotations at real healthcare facilities. Graduate ready for immediate employment in hospitals, clinics, blood banks, and diagnostic labs with national certification.',
    funding: 'WRG • WIOA • Workforce Grants',
    duration: '4–8 Weeks • Clinical Rotations Included',
    image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'welding',
    name: 'Welding Technology',
    blurb: 'Master a high-demand skilled trade! Learn MIG, TIG, stick welding, blueprint reading, and metal fabrication through intensive hands-on training. Our 12-24 week program prepares you for AWS certification and immediate employment in manufacturing, construction, automotive, and industrial settings. Welders earn $40K-$60K+ starting.',
    funding: 'Workforce Grants • Apprenticeship • WIOA',
    duration: '12–24 Weeks • Hands-On Lab Training',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'electrical',
    name: 'Electrical Technician',
    blurb: 'Start your career in the electrical trades! Learn residential and commercial wiring, electrical code, circuit design, troubleshooting, and safety procedures. Our 16-24 week program combines classroom theory with real-world installations. Graduate ready for apprenticeship positions or immediate employment with electrical contractors.',
    funding: 'Registered Apprenticeship • WIOA • WRG',
    duration: '16–24 Weeks • Classroom + Field Work',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'pharmacy-tech',
    name: 'Pharmacy Technician',
    blurb: 'Enter the growing pharmacy field in 12-16 weeks! Learn medication dispensing, prescription processing, inventory management, insurance billing, and patient service. Our program includes externship at retail or hospital pharmacies. Graduate ready for national PTCB certification and employment at CVS, Walgreens, hospitals, and clinics.',
    funding: 'WRG • WIOA • Workforce Grants',
    duration: '12–16 Weeks • Externship Included',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'it-support',
    name: 'IT Support Specialist',
    blurb: 'Launch your tech career with CompTIA A+ certification! Learn computer hardware, software, networking, troubleshooting, and customer service. Our 12-20 week program prepares you for help desk, desktop support, and IT technician roles. No prior experience needed. Tech jobs start at $40K+ with room for growth.',
    funding: 'Workforce Grants • WIOA • Employer Sponsors',
    duration: '12–20 Weeks • Online + Hands-On Labs',
    image: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=600&q=80',
    etplApproved: true,
  },
  {
    slug: 'culinary-arts',
    name: 'Culinary Arts & Food Service',
    blurb: 'Turn your passion for cooking into a career through our Registered Apprenticeship! Earn while you learn in professional kitchens. Master food preparation, kitchen safety, menu planning, nutrition, and restaurant operations through hands-on training. Graduate ready for line cook, prep cook, or food service management positions in restaurants, hotels, and catering.',
    funding: 'Registered Apprenticeship • WIOA • WRG',
    duration: '12–18 Months • Earn While You Learn',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&q=80',
    etplApproved: true,
  },
];
