/**
 * COMPLETE Program Data - All 15 ETPL Programs
 * Extracted from supabase/migrations/20241115_add_all_etpl_programs.sql
 * This is the authoritative source for all program information
 */

export interface ProgramData {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  summary: string;
  bullets: string[];
  funding: string[];
  duration: string;
  image: string;
  etplApproved: boolean;
}

export const COMPLETE_PROGRAMS: ProgramData[] = [
  {
    slug: 'business-startup-marketing',
    name: 'Business Start-Up & Marketing Program',
    tagline: 'Launch your own business with Rise Forward',
    description: 'The Business Start-Up & Marketing Program with Rise Forward equips participants with hands-on skills to launch their own business ventures. Students will learn the fundamentals of entrepreneurship, digital marketing, LLC formation, business planning, customer service, and resume development. The program includes guided startup support, mentorship, and ends with a business match stipend and laptop kit to empower real-world implementation. Ideal for youth ready to explore self-employment and leadership pathways in today\'s economy.',
    summary: 'Learn entrepreneurship, digital marketing, LLC formation, and business planning with mentorship and startup support.',
    bullets: [
      '5-week accelerated program',
      '32 instructional hours (8 hours/week)',
      'LLC formation and business planning',
      'Digital marketing and customer service',
      'Business match stipend + laptop kit',
      'Resume development and professional branding',
      '100% online, flexible schedule',
      'Open to youth ages 16+'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '5 Weeks • 32 Hours',
    image: '/images/business-startup.jpg',
    etplApproved: true,
  },
  {
    slug: 'emergency-health-safety-tech',
    name: 'Emergency Health & Safety Technician',
    tagline: 'Life-saving skills through DOL Federally Registered Apprenticeship',
    description: 'The Emergency Health & Safety Technician is a DOL Federally Registered Apprenticeship that prepares individuals for life-saving response roles in schools, workplaces and emergency settings. This hybrid (time-based and competency-based) apprenticeship includes CPR, OSHA 10, and Emergency Medical Responder (EMR) training. Students graduate with nationally recognized certifications and are equipped for careers in healthcare, public safety, community response, and entry-level emergency technician pathways.',
    summary: 'Earn OSHA 10, CPR, and EMR certifications in 4-week DOL Registered Apprenticeship.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      'Hybrid: Time-based and Competency-based',
      '4-week program (4 weeks RTI)',
      '80 instructional hours (20 hours/week)',
      'Earn OSHA 10 - Career Safe certification',
      'Earn CPR certification',
      'Earn Emergency Medical Responder (EMR) certification',
      'Public health emergency awareness',
      'High school diploma or GED required',
      'Day, evening, weekend, and online options'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '4 Weeks • 80 Hours',
    image: '/images/emergency-health-safety.jpg',
    etplApproved: true,
  },
  {
    slug: 'hvac-technician',
    name: 'HVAC Technician',
    tagline: 'DOL Federally Registered Apprenticeship in HVAC',
    description: 'The HVAC Technician program is a DOL Federally Registered Apprenticeship that provides comprehensive training in heating, ventilation, air conditioning, and refrigeration systems. This hybrid (time-based and competency-based) apprenticeship includes 50 weeks of Related Technical Instruction combined with on-the-job training. Students earn multiple industry-recognized certifications including CPR, Rise Up Credential, OSHA 30, and two Residential HVAC Certifications.',
    summary: 'Earn 5 certifications in DOL Registered HVAC Apprenticeship with 10 active apprentices.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      '50 weeks of Related Technical Instruction (RTI)',
      '125 instructional hours (12 hours/week)',
      'Currently 10 active apprentices',
      'Earn CPR certification',
      'Earn Rise Up Credential',
      'Earn OSHA 30 certification',
      'Earn Residential HVAC Certification 1',
      'Earn Residential HVAC Certification 2 - Refrigeration Diagnostics',
      'No prerequisites'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '50 Weeks • 125 Hours RTI',
    image: '/images/hvac-technician.jpg',
    etplApproved: true,
  },
  {
    slug: 'direct-support-professional',
    name: 'Direct Support Professional (DSP)',
    tagline: 'Compassionate care for individuals with developmental needs',
    description: 'Our Direct Support Professional (DSP) training program is built to prepare compassionate individuals for meaningful work in the care and support field. This program offers hands-on instruction, real-world scenarios, and practical skills that help students feel confident working with individuals who have developmental, physical, or emotional needs.',
    summary: 'Prepare for a rewarding career supporting individuals with developmental, physical, or emotional needs.',
    bullets: [
      'Rolling enrollment - start anytime',
      'Cohorts begin 1st and 15th of each month',
      'Hands-on instruction and real-world scenarios',
      'No prior healthcare experience required',
      'Must be 18+ with high school diploma or GED',
      'Background check required',
      'Job placement assistance included',
      'CDSP, CNA, or QIDP pathway'
    ],
    funding: ['WIOA', 'WRG'],
    duration: 'Rolling Enrollment',
    image: '/images/dsp.jpg',
    etplApproved: true,
  },
  {
    slug: 'professional-esthetician',
    name: 'Professional Esthetician & Client Services',
    tagline: 'Job-ready skincare and spa skills through DOL Federally Registered Apprenticeship',
    description: 'The Esthetics and Skincare Specialist Certificate Program is a DOL Federally Registered Apprenticeship that prepares individuals to enter the high-demand personal care industry with job-ready skills in skin analysis, facial treatments, hair removal, sanitation, customer service, and product knowledge. This RAPIDS-verified program offers traditional wrap around support including career readiness, business startup training, wellness coaching and access to employer networks.',
    summary: 'Master skincare, facial treatments, and client services in 5 weeks through DOL Registered Apprenticeship.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      '5-week program (4 weeks RTI)',
      '60 instructional hours (15 hours/week)',
      'Currently 3 active apprentices',
      'Earn OSHA 10 - Career Safe certification',
      'Customer Service and Sales Certified Specialist',
      'Business of Retail Certified Specialist',
      'Skin analysis and facial treatments',
      'Career readiness and business startup training',
      'No prerequisites - all ages welcome'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '5 Weeks • 60 Hours',
    image: '/images/esthetician.jpg',
    etplApproved: true,
  },
  {
    slug: 'tax-prep-financial-services',
    name: 'Tax Preparation & Financial Services Certificate',
    tagline: 'State Certified Earn and Learn program with IRS VITA/TCE certification',
    description: 'The Tax Preparation & Financial Services Certificate is a State Certified Earn and Learn program (certified 2025-10-01) that prepares individuals to understand federal and state taxation concepts and apply them in real-world settings. Students earn QuickBooks Pro Advisor and Microsoft 365 Fundamentals certifications, plus the Rise Up Credential. Graduates gain the skills required for employment as Tax Preparers, Bookkeeping Assistants, and Financial Service Specialists.',
    summary: 'Earn IRS VITA/TCE, QuickBooks, Microsoft 365, and Rise Up certifications in State Certified Earn and Learn program.',
    bullets: [
      'State Certified Earn and Learn (certified 2025-10-01)',
      '10-week comprehensive program',
      '150 instructional hours (15 hours/week)',
      'Earn QuickBooks Pro Advisor certification',
      'Earn Microsoft 365 Fundamentals certification',
      'Earn Rise Up Credential',
      'IRS VITA/TCE certification included',
      'Federal and state tax law training',
      'Supervised practicum at IRS-approved VITA site',
      'High school diploma or GED required'
    ],
    funding: ['WIOA', 'WRG', 'Earn and Learn'],
    duration: '10 Weeks • 150 Hours',
    image: '/images/tax-prep.jpg',
    etplApproved: true,
  },
  {
    slug: 'public-safety-reentry-specialist',
    name: 'Public Safety Reentry Specialist Program',
    tagline: 'Career pathways for justice-involved individuals',
    description: 'This program directly supports the critical shortage in Indiana\'s behavioral health, reentry, and public safety workforce by training Peer Recovery Specialists with a trauma-informed lens. Aligned with O*NET Code 21-1093.00 (Social and Human Service Assistants), this certification-based program prepares justice-impacted individuals and others to provide frontline recovery, crisis response, and peer coaching services.',
    summary: 'Trauma-informed Peer Recovery Specialist training for justice-impacted individuals and reentry professionals.',
    bullets: [
      '45-day intensive program',
      '180 instructional hours (15 hours/week)',
      'O*NET 21-1093.00 - Social and Human Service Assistants',
      'Certified Peer Recovery Specialist (CPRS) pathway',
      'Trauma-informed coaching and mentorship',
      'Crisis response and peer navigation',
      'No prior credential required',
      '100% online with tutoring support',
      '100% acceptance rate for eligible applicants'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '45 Days • 180 Hours',
    image: '/images/public-safety-reentry.jpg',
    etplApproved: true,
  },
  {
    slug: 'barber-apprenticeship',
    name: 'Barber Apprenticeship Program',
    tagline: 'Master barbering through DOL Federally Registered Apprenticeship',
    description: 'The Barber Apprenticeship Program is a comprehensive 2,000-hour DOL Federally Registered Apprenticeship that combines 12 weeks of instructional training with extensive on-the-job training. Students learn cutting, styling, shaving, sanitation, and business skills in a real barbershop environment. This RAPIDS-verified apprenticeship prepares participants for Indiana Registered Barber License.',
    summary: 'Earn while you learn in a 2,000-hour DOL Federally Registered Apprenticeship.',
    bullets: [
      'DOL Federally Registered Apprenticeship',
      '2,000-hour comprehensive program',
      '12 weeks instructional training',
      'On-the-job training in real barbershops',
      'Learn cutting, styling, shaving, sanitation',
      'Business skills and shop management',
      'RAPIDS-verified apprenticeship',
      'Pathway to Indiana Registered Barber License',
      'Earn while you learn',
      'Shop ownership pathway'
    ],
    funding: ['WIOA', 'WRG', 'Apprenticeship'],
    duration: '2,000 Hours • 12 Weeks + OJT',
    image: '/images/barber-apprenticeship.jpg',
    etplApproved: true,
  },
  {
    slug: 'beauty-career-educator',
    name: 'Beauty & Career Educator Training Program',
    tagline: 'Develop career-ready, technical, and leadership skills in beauty education',
    description: 'The Beauty & Career Educator Training Program is a 12-week hybrid training experience designed to help aspiring beauty professionals and peer educators develop career-ready, technical, and leadership skills. Participants earn a nationally recognized Rise Up Credential, a Career Readiness Certificate, and a custom Certificate of Completion. Designed for youth and adults ages 16+.',
    summary: 'Earn Rise Up Credential + Career Readiness Certificate in 12 weeks.',
    bullets: [
      '12-week hybrid training program',
      'Practical salon service education',
      'Manicuring techniques and customer service',
      'Sanitation and infection control',
      'Peer teaching and community workshops',
      'Entrepreneurship and workforce readiness',
      'Rise Up Credential (nationally recognized)',
      'Career Readiness Certificate',
      'Ages 16+ welcome',
      'CIP Code 13.1326 eligible'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '12 Weeks',
    image: '/images/beauty-career-educator.jpg',
    etplApproved: true,
  },
  {
    slug: 'certified-peer-support-professional',
    name: 'Certified Peer Support Professional',
    tagline: 'Support others through lived experience',
    description: 'The Certified Peer Support Professional program trains individuals with lived experience in mental health or substance use recovery to provide peer support services. This certification is recognized by behavioral health agencies, hospitals, and community organizations. Participants learn recovery principles, ethical boundaries, trauma-informed care, and advocacy skills.',
    summary: 'Become a certified peer support professional and help others in recovery.',
    bullets: [
      'Certification for lived experience professionals',
      'Mental health and substance use recovery focus',
      'Recognized by behavioral health agencies',
      'Recovery principles and ethical boundaries',
      'Trauma-informed care training',
      'Advocacy skills development',
      'Hospital and community organization placement',
      'No prior healthcare degree required',
      'Lived experience valued',
      'Career pathway in behavioral health'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '6-8 Weeks',
    image: '/images/peer-support.jpg',
    etplApproved: true,
  },
  {
    slug: 'certified-peer-recovery-coach',
    name: 'Certified Peer Recovery Coach (CPRC)',
    tagline: 'Guide others on their recovery journey',
    description: 'The Certified Peer Recovery Coach (CPRC) credential prepares individuals to provide recovery coaching services in substance use and mental health settings. This certification is recognized nationally and qualifies graduates to work in treatment centers, recovery housing, hospitals, and community programs. Training covers motivational interviewing, recovery capital, relapse prevention, and ethical practice.',
    summary: 'Earn your CPRC credential and make a difference in recovery services.',
    bullets: [
      'Nationally recognized CPRC credential',
      'Recovery coaching for substance use and mental health',
      'Motivational interviewing techniques',
      'Recovery capital assessment',
      'Relapse prevention strategies',
      'Ethical practice and boundaries',
      'Treatment center placement',
      'Recovery housing opportunities',
      'Hospital and community program roles',
      'Justice-involved individuals welcome'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '45 Days • 180 Hours',
    image: '/images/peer-recovery-coach.jpg',
    etplApproved: true,
  },
  {
    slug: 'cpr-certification',
    name: 'CPR Certification',
    tagline: 'Life-saving skills in one day',
    description: 'CPR Certification provides essential life-saving skills through American Heart Association or Red Cross training. This standalone certification is required for many healthcare, childcare, fitness, and public safety positions. Participants learn adult, child, and infant CPR, AED use, and choking relief. Certification is valid for 2 years.',
    summary: 'Get CPR/AED certified in one day.',
    bullets: [
      'American Heart Association or Red Cross certified',
      'Adult, child, and infant CPR',
      'AED (Automated External Defibrillator) use',
      'Choking relief techniques',
      'Required for healthcare positions',
      'Childcare and fitness industry requirement',
      'Public safety certification',
      '2-year certification validity',
      'One-day training',
      'Recertification available'
    ],
    funding: ['Self-Pay', 'Employer Sponsored'],
    duration: '1 Day • 4-8 Hours',
    image: '/images/cpr-cert.jpg',
    etplApproved: false,
  },
  {
    slug: 'certified-community-healthcare-worker',
    name: 'Certified Community Healthcare Worker (CCHW)',
    tagline: 'Bridge healthcare gaps in your community',
    description: 'The Certified Community Healthcare Worker (CCHW) program trains individuals to serve as liaisons between healthcare providers and communities. CHWs help patients navigate the healthcare system, provide health education, connect people to resources, and advocate for community health needs. This certification is increasingly recognized by hospitals, clinics, and public health departments.',
    summary: 'Become a certified community healthcare worker and improve health outcomes.',
    bullets: [
      'Liaison between healthcare providers and communities',
      'Healthcare system navigation support',
      'Health education and outreach',
      'Resource connection and referrals',
      'Community health advocacy',
      'Hospital and clinic placement',
      'Public health department opportunities',
      'Cultural competency training',
      'No prior healthcare degree required',
      'Community-focused career pathway'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '8-12 Weeks',
    image: '/images/community-healthcare-worker.jpg',
    etplApproved: true,
  },
  {
    slug: 'rise-up-certificate',
    name: 'Rise Up Certificate',
    tagline: 'Foundational skills for career success with Job Ready Indy',
    description: 'The Rise Up Certificate program provides foundational skills for individuals entering or re-entering the workforce. This program covers digital literacy, professional communication, workplace readiness, financial literacy, and personal wellness. Students also complete the Job Ready Indy (JRI) 6-badge series through EmployIndy, earning a nationally recognized workforce readiness credential.',
    summary: 'Build foundational skills and earn Job Ready Indy credential.',
    bullets: [
      'Foundational workforce readiness skills',
      'Digital literacy training',
      'Professional communication',
      'Workplace readiness preparation',
      'Financial literacy education',
      'Personal wellness and self-care',
      'Includes Job Ready Indy (JRI) 6-badge series',
      'Nationally recognized credential',
      'EmployIndy JRI Facilitator: Elevate for Humanity',
      'Pathway to further training or employment'
    ],
    funding: ['WIOA', 'JRI'],
    duration: '4-6 Weeks',
    image: '/images/rise-up.jpg',
    etplApproved: true,
  },
  {
    slug: 'osha-10-certification',
    name: 'OSHA 10 Certification',
    tagline: 'Essential workplace safety training',
    description: 'OSHA 10-Hour General Industry certification provides foundational knowledge of workplace safety and health hazards. This certification is required or preferred for many construction, manufacturing, healthcare, and service industry positions. Participants learn hazard recognition, fall protection, electrical safety, personal protective equipment (PPE), and emergency response. The certification is valid and recognized nationwide.',
    summary: 'Get OSHA 10 certified and meet employer safety requirements.',
    bullets: [
      'OSHA 10-Hour General Industry certification',
      'Workplace safety and health hazards',
      'Hazard recognition and prevention',
      'Fall protection and electrical safety',
      'Personal protective equipment (PPE)',
      'Emergency response procedures',
      'Required for many industry positions',
      'Nationally recognized certification',
      'Valid for career advancement',
      'Included in Beauty & Career Educator program'
    ],
    funding: ['WIOA', 'WRG'],
    duration: '10 Hours • 2 Days',
    image: '/images/osha-10.jpg',
    etplApproved: true,
  },
];
