# EFH AI Agent Worker Configuration
# Deploy: npx wrangler deploy workers/agent/ai-employee.js --config workers/agent/wrangler.toml

name = "efh-agent"
main = "ai-employee.js"
compatibility_date = "2024-10-14"

# Workers AI binding for zero-cost LLM inference
[ai]
binding = "AI"

# KV namespace for activity logs (optional - comment out if not available)
# [[kv_namespaces]]
# binding = "AI_EMPLOYEE_LOGS"
# id = "YOUR_KV_NAMESPACE_ID"

# Cron trigger for automated payout batches (3 AM UTC daily)
[triggers]
crons = ["0 3 * * *"]

# R2 Bucket for file storage (optional - comment out if not available)
# [[r2_buckets]]
# binding = "EFH_BUCKET"
# bucket_name = "efh-private"

# Environment variables (set via: wrangler secret put <NAME>)
# Required secrets:
# - SUPABASE_FUNCTION_URL: https://<project>.functions.supabase.co
# - SUPABASE_SERVICE_ROLE_KEY: Your Supabase service role key (for executeAction)
# - SUPABASE_URL: https://<project>.supabase.co
# - SUPABASE_ANON_KEY: Your Supabase anon key
# - STRIPE_SECRET_KEY: Your Stripe secret key (sk_live_... or sk_test_...)
# - STRIPE_WEBHOOK_SECRET: Your Stripe webhook secret (whsec_...)
# - POSTMARK_INBOUND_TOKEN: Your Postmark inbound webhook token
# - CF_ACCOUNT_ID: Your Cloudflare account ID
# - CF_API_TOKEN: Your Cloudflare API token

[env.production]
# Production environment
# Set secrets with: wrangler secret put STRIPE_SECRET_KEY --env production
# Set secrets with: wrangler secret put STRIPE_WEBHOOK_SECRET --env production
# Set secrets with: wrangler secret put POSTMARK_INBOUND_TOKEN --env production

[[env.production.kv_namespaces]]
binding = "AI_EMPLOYEE_LOGS"
id = "YOUR_PROD_KV_NAMESPACE_ID"

[[env.production.r2_buckets]]
binding = "EFH_BUCKET"
bucket_name = "efh-private-prod"

[env.staging]
# Staging environment for testing
# Set secrets with: wrangler secret put STRIPE_SECRET_KEY --env staging (use test key)
# Set secrets with: wrangler secret put POSTMARK_INBOUND_TOKEN --env staging

[[env.staging.kv_namespaces]]
binding = "AI_EMPLOYEE_LOGS"
id = "YOUR_STAGING_KV_NAMESPACE_ID"

[[env.staging.r2_buckets]]
binding = "EFH_BUCKET"
bucket_name = "efh-private-staging"
