# EFH AI Agent Worker Configuration
# Deploy: npx wrangler deploy workers/agent/agent-worker.js --config workers/agent/wrangler.toml

name = "efh-agent"
main = "agent-worker.js"
compatibility_date = "2024-10-14"

# Cron trigger for automated payout batches (3 AM UTC daily)
[triggers]
crons = ["0 3 * * *"]

# R2 Bucket for file storage
[[r2_buckets]]
binding = "EFH_BUCKET"
bucket_name = "efh-private"

# Environment variables (set via: wrangler secret put <NAME>)
# Required secrets:
# - OPENAI_API_KEY: Your OpenAI API key (sk-...)
# - SUPABASE_FUNCTION_URL: https://<project>.functions.supabase.co
# - SUPABASE_SERVICE_ROLE_KEY: Your Supabase service role key
# - SUPABASE_URL: https://<project>.supabase.co
# - SUPABASE_ANON_KEY: Your Supabase anon key
# - STRIPE_SECRET_KEY: Your Stripe secret key (sk_live_... or sk_test_...)
# - STRIPE_WEBHOOK_SECRET: Your Stripe webhook secret (whsec_...)

[env.production]
# Production environment
# Set secrets with: wrangler secret put OPENAI_API_KEY --env production
# Set secrets with: wrangler secret put STRIPE_SECRET_KEY --env production
# Set secrets with: wrangler secret put STRIPE_WEBHOOK_SECRET --env production

[[env.production.r2_buckets]]
binding = "EFH_BUCKET"
bucket_name = "efh-private-prod"

[env.staging]
# Staging environment for testing
# Set secrets with: wrangler secret put OPENAI_API_KEY --env staging
# Set secrets with: wrangler secret put STRIPE_SECRET_KEY --env staging (use test key)

[[env.staging.r2_buckets]]
binding = "EFH_BUCKET"
bucket_name = "efh-private-staging"
