name = "ai-form-gen"
main = "worker.js"
compatibility_date = "2024-09-01"

[[kv_namespaces]]
binding = "REGISTRY"
id = "f8ab4f8ad558406eaea36934805125c7"

[vars]
BRAND_NAME = "Elevate For Humanity"
ANALYZER_URL = "https://efh-autopilot-analyzer.elevateforhumanity.workers.dev/logs/ingest"
