# Gitpod One-Click Setup for Polished Next.js Site
# Elevate for Humanity - Design-First Landing Page

image: gitpod/workspace-node

tasks:
  - name: Setup & Launch
    init: bash scripts/setup-polished-site.sh
    command: |
      cd web
      echo ""
      echo "🎉 Polished Next.js site is ready!"
      echo "=================================="
      echo ""
      echo "📦 Installed:"
      echo "   • Next.js 15 with App Router"
      echo "   • Tailwind CSS + shadcn/ui"
      echo "   • Framer Motion animations"
      echo "   • Lucide React icons"
      echo ""
      echo "🎨 Components:"
      echo "   • Hero banner with CTA"
      echo "   • Features grid"
      echo "   • Pricing cards"
      echo "   • Footer & Navigation"
      echo ""
      echo "🚀 Starting dev server..."
      npm run dev -- --port 3000

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
    description: Next.js Development Server

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - github.copilot
    - github.copilot-chat
