name: Daily Admin Report

on:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC
  workflow_dispatch: {}

jobs:
  daily-report:
    runs-on: ubuntu-latest
    steps:
      - name: Call EFH daily report endpoint
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${{ secrets.REPORT_CRON_TOKEN }}" \
            https://elevateconnectsdirectory.org/api/admin/reports/daily || exit 1
