#!/bin/bash
# Manual deployment helper
echo "🚀 Manual Deployment Options"
echo ""
echo "Option 1: Netlify Drop (Easiest)"
echo "  → Open: https://app.netlify.com/drop"
echo "  → Drag: ./dist folder"
echo ""
echo "Option 2: Netlify CLI"
echo "  → Run: npx netlify-cli deploy --dir=dist --prod"
echo ""
echo "Option 3: GitHub Pages"
echo "  → Run: npm run deploy:gh-pages"
echo ""
echo "Option 4: Vercel"
echo "  → Run: npx vercel --prod"
echo ""
echo "Option 5: Local Preview"
echo "  → Run: npx serve dist -p 8080"
echo ""
