name = "cima-importer"
main = "index.js"
compatibility_date = "2024-01-01"

# Bindings
[vars]
R2_PREFIX = "cima-exports/"
IMPORTED_PREFIX = "cima-imported/"

# Secrets (set with: wrangler secret put SECRET_NAME)
# SUPABASE_URL - Your Supabase project URL
# SUPABASE_SERVICE_KEY - Your Supabase service role key
# SUPABASE_JWT_SECRET - Your Supabase JWT secret (for token verification)
# MAIL_FROM - Email sender address (e.g., no-reply@yourdomain.com)
# MAIL_FROM_NAME - Email sender name (e.g., Elevate Apprenticeship)
# MAIL_BCC - Optional BCC address for all emails
# SIGN_SECRET - Secret for generating sign tokens (optional, uses random if not set)
# FRONTEND_URL - Frontend URL for email links (e.g., https://elevateforhumanity.org)

# R2 bucket for automated CSV imports
[[r2_buckets]]
binding = "R2"
bucket_name = "efh-assets"

# Cron trigger for nightly auto-import
[triggers]
crons = ["0 3 * * *"]  # Every day at 3 AM UTC

# Routes (uncomment and configure for production)
# routes = [
#   { pattern = "cima.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Development
[env.development]
name = "cima-importer-dev"

# Production
[env.production]
name = "cima-importer-prod"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "efh-assets"

[env.production.triggers]
crons = ["0 3 * * *"]
