name: Cancel Stuck Workflows

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Workflow name to cancel (leave empty for all stuck workflows)'
        required: false
        default: 'Autonomous Netlify Deploy'
      max_age_hours:
        description: 'Cancel workflows older than X hours'
        required: false
        default: '1'

jobs:
  cancel-stuck-workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cancel stuck workflows
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "🔍 Finding stuck workflows..."
          echo ""

          # Get current time in seconds
          NOW=$(date +%s)
          MAX_AGE_SECONDS=$((${MAX_AGE_HOURS:-1} * 3600))

          # Get all in-progress workflows
          gh api repos/${{ github.repository }}/actions/runs \
            --jq '.workflow_runs[] | select(.status == "in_progress") | {id: .id, name: .name, created_at: .created_at, html_url: .html_url}' \
            > /tmp/running_workflows.json

          CANCELLED=0
          SKIPPED=0
          FAILED=0

          # Process each workflow
          while IFS= read -r workflow; do
            ID=$(echo "$workflow" | jq -r '.id')
            NAME=$(echo "$workflow" | jq -r '.name')
            CREATED=$(echo "$workflow" | jq -r '.created_at')
            URL=$(echo "$workflow" | jq -r '.html_url')
            
            # Calculate age
            CREATED_SECONDS=$(date -d "$CREATED" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$CREATED" +%s 2>/dev/null || echo 0)
            AGE_SECONDS=$((NOW - CREATED_SECONDS))
            AGE_HOURS=$((AGE_SECONDS / 3600))
            
            # Check if workflow matches filter
            if [ -n "${{ inputs.workflow_name }}" ] && [ "$NAME" != "${{ inputs.workflow_name }}" ]; then
              echo "⏭️  Skipping: $NAME (ID: $ID) - doesn't match filter"
              ((SKIPPED++))
              continue
            fi
            
            # Check if workflow is old enough
            if [ $AGE_SECONDS -lt $MAX_AGE_SECONDS ]; then
              echo "⏭️  Skipping: $NAME (ID: $ID) - only ${AGE_HOURS}h old"
              ((SKIPPED++))
              continue
            fi
            
            echo "🔴 Cancelling: $NAME (ID: $ID)"
            echo "   Age: ${AGE_HOURS} hours"
            echo "   URL: $URL"
            
            if gh api -X POST repos/${{ github.repository }}/actions/runs/$ID/cancel; then
              echo "   ✅ Cancelled successfully"
              ((CANCELLED++))
            else
              echo "   ❌ Failed to cancel"
              ((FAILED++))
            fi
            echo ""
          done < <(cat /tmp/running_workflows.json | jq -c '.')

          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Summary:"
          echo "  ✅ Cancelled: $CANCELLED"
          echo "  ⏭️  Skipped: $SKIPPED"
          echo "  ❌ Failed: $FAILED"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Create summary
          echo "## 🤖 Autopilot Workflow Cancellation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Filter:** ${{ inputs.workflow_name || 'All workflows' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Max Age:** ${{ inputs.max_age_hours || '1' }} hours" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Cancelled: $CANCELLED" >> $GITHUB_STEP_SUMMARY
          echo "- ⏭️ Skipped: $SKIPPED" >> $GITHUB_STEP_SUMMARY
          echo "- ❌ Failed: $FAILED" >> $GITHUB_STEP_SUMMARY

          if [ $CANCELLED -gt 0 ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### ✅ Success" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Stuck workflows have been cancelled. Queued workflows should now start." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Verify cancellation
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "🔍 Checking remaining in-progress workflows..."
          echo ""

          REMAINING=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '[.workflow_runs[] | select(.status == "in_progress")] | length')

          echo "Remaining in-progress workflows: $REMAINING"

          if [ "$REMAINING" -eq 0 ]; then
            echo "✅ All workflows cleared!"
          else
            echo "⚠️  $REMAINING workflows still running"
            echo ""
            echo "Remaining workflows:"
            gh api repos/${{ github.repository }}/actions/runs \
              --jq '.workflow_runs[] | select(.status == "in_progress") | "  - \(.name) (ID: \(.id), Age: \(.created_at))"'
          fi

      - name: Check queued workflows
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo ""
          echo "🔍 Checking queued workflows..."
          echo ""

          QUEUED=$(gh api repos/${{ github.repository }}/actions/runs \
            --jq '[.workflow_runs[] | select(.status == "queued")] | length')

          echo "Queued workflows: $QUEUED"

          if [ "$QUEUED" -gt 0 ]; then
            echo ""
            echo "These workflows should start soon:"
            gh api repos/${{ github.repository }}/actions/runs \
              --jq '.workflow_runs[] | select(.status == "queued") | "  - \(.name) (ID: \(.id))"' | head -10
          fi
