name: Durable Enrollment Autopilot

on:
  schedule:
    # Run every 30 minutes until successful
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if already deployed'
        required: false
        default: 'false'

jobs:
  deploy-enrollment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: |
          npm install puppeteer
          echo "✅ Puppeteer installed"

      - name: Run Durable Autopilot
        env:
          DURABLE_EMAIL: ${{ secrets.DURABLE_EMAIL }}
          DURABLE_PASSWORD: ${{ secrets.DURABLE_PASSWORD }}
        run: |
          echo "🤖 Starting Durable Enrollment Autopilot..."
          echo ""

          chmod +x durable-autopilot.js
          node durable-autopilot.js || echo "Autopilot completed with warnings"

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: durable-autopilot-screenshots-${{ github.run_number }}
          path: logs/*.png
          retention-days: 30
          if-no-files-found: ignore

      - name: Read deployment status
        id: status
        run: |
          if [ -f "logs/deployment-status.json" ]; then
            SUCCESS=$(jq -r '.success' logs/deployment-status.json)
            VISIBLE=$(jq -r '.enrollmentVisible' logs/deployment-status.json)
            echo "success=$SUCCESS" >> $GITHUB_OUTPUT
            echo "visible=$VISIBLE" >> $GITHUB_OUTPUT
            echo "✅ Status file found: success=$SUCCESS, visible=$VISIBLE"
          else
            echo "success=false" >> $GITHUB_OUTPUT
            echo "visible=false" >> $GITHUB_OUTPUT
            echo "⚠️ Status file not found"
          fi

      - name: Commit status
        if: steps.status.outputs.success == 'true'
        run: |
          git config --local user.email "autopilot@elevateforhumanity.org"
          git config --local user.name "EFH Enrollment Autopilot"

          git add logs/deployment-status.json || true
          git commit -m "chore: enrollment autopilot deployed successfully

          🤖 Autopilot Actions:
          - Logged into Durable.co
          - Injected enrollment programs
          - Published changes
          - Verified deployment

          Status: ✅ SUCCESS
          Enrollment Visible: ${{ steps.status.outputs.visible }}
          Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

          Co-authored-by: Ona <no-reply@ona.com>" || echo "No changes"

          git push origin main || echo "Nothing to push"

      - name: Create summary
        if: always()
        run: |
          echo "## 🤖 Durable Enrollment Autopilot" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.status.outputs.success }}" = "true" ]; then
            echo "### ✅ Deployment Successful" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Autopilot successfully:" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Logged into Durable.co" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Found and opened site editor" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Added Custom HTML block" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Pasted enrollment code" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Published changes" >> $GITHUB_STEP_SUMMARY
            
            if [ "${{ steps.status.outputs.visible }}" = "true" ]; then
              echo "- ✅ Verified enrollment programs are LIVE" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "**🎉 Enrollment programs are now live on www.elevateforhumanity.org!**" >> $GITHUB_STEP_SUMMARY
            else
              echo "- ⚠️ Enrollment programs not visible yet (CDN caching)" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "**Wait 1-2 minutes and refresh the page**" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "### ⚠️ Deployment Incomplete" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Autopilot encountered issues. Check screenshots for details." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Possible reasons:**" >> $GITHUB_STEP_SUMMARY
            echo "- Durable.co UI changed" >> $GITHUB_STEP_SUMMARY
            echo "- Login credentials incorrect" >> $GITHUB_STEP_SUMMARY
            echo "- Network timeout" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Autopilot will retry in 30 minutes**" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "*Next autopilot run in 30 minutes*" >> $GITHUB_STEP_SUMMARY

      - name: Create issue if failed
        if: steps.status.outputs.success == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'enrollment-autopilot,deployment-failed'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🤖 Enrollment Autopilot: Deployment Failed',
                body: `## Enrollment Autopilot Status

                The enrollment autopilot attempted to deploy enrollment programs to Durable.co but encountered issues.

                **Timestamp:** ${new Date().toISOString()}

                ### What the Autopilot Tried

                1. Login to Durable.co
                2. Find and open site editor
                3. Add Custom HTML block
                4. Paste enrollment code
                5. Publish changes
                6. Verify deployment

                ### Troubleshooting

                - Check workflow logs: [Run #${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
                - Review screenshot artifacts
                - Verify Durable credentials are correct

                ### Manual Deployment

                If autopilot continues to fail, you can deploy manually:

                1. Log into Durable.co
                2. Edit your homepage
                3. Add Custom HTML block
                4. Paste code from \`DURABLE_ENROLLMENT_CODE.html\`
                5. Publish

                ---

                *This issue was created by Enrollment Autopilot and will auto-close when deployment succeeds.*`,
                labels: ['enrollment-autopilot', 'deployment-failed', 'auto-created']
              });
            }

      - name: Close issue if successful
        if: steps.status.outputs.success == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'enrollment-autopilot,deployment-failed'
            });

            for (const issue of issues.data) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '✅ Enrollment autopilot successfully deployed enrollment programs to Durable.co. Closing this issue.'
              });
            }
