#!/bin/bash

# Auto-populate .env.local from Gitpod environment variables
# Run this once to set up: bash .gitpod/save-env-to-gitpod.sh

echo "🔧 Creating .env.local from environment variables..."

cat > /workspaces/fix2/.env.local << EOF
# Database & Supabase
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
POSTGRES_URL=${POSTGRES_URL}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=${DATABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_URL=${SUPABASE_URL}
POSTGRES_DATABASE=${POSTGRES_DATABASE}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_USER=${POSTGRES_USER}
SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}

# Authentication
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
SESSION_SECRET=${SESSION_SECRET}

# Payments
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
AFFIRM_PUBLIC_KEY=${AFFIRM_PUBLIC_KEY}
AFFIRM_PRIVATE_KEY=${AFFIRM_PRIVATE_KEY}
NEXT_PUBLIC_AFFIRM_PUBLIC_KEY=${NEXT_PUBLIC_AFFIRM_PUBLIC_KEY}

# Services
OPENAI_API_KEY=${OPENAI_API_KEY}
RESEND_API_KEY=${RESEND_API_KEY}
UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}

# Email
EMAIL_FROM=${EMAIL_FROM}
REPLY_TO_EMAIL=${REPLY_TO_EMAIL}
MOU_ARCHIVE_EMAIL=${MOU_ARCHIVE_EMAIL}
SPONSOR_FINANCE_EMAIL=${SPONSOR_FINANCE_EMAIL}

# Configuration
NODE_ENV=${NODE_ENV:-production}
CRON_SECRET=${CRON_SECRET}
ZAPIER_WEBHOOK_URL=${ZAPIER_WEBHOOK_URL}
SAM_API_KEY=${SAM_API_KEY}
NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
NEXT_PUBLIC_RAPIDS_PROGRAM_NUMBER=${NEXT_PUBLIC_RAPIDS_PROGRAM_NUMBER}
NEXT_PUBLIC_RTI_PROVIDER_ID=${NEXT_PUBLIC_RTI_PROVIDER_ID}
NEXT_PUBLIC_RAPIDS_SPONSOR_NAME=${NEXT_PUBLIC_RAPIDS_SPONSOR_NAME}
LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
EOF

echo "✅ .env.local created from Gitpod environment variables"
