#!/bin/bash
echo "🗄️  SUPABASE MIGRATION HELPER"
echo "=============================="
echo ""
echo "📋 Instructions:"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Click 'SQL Editor' in left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy contents of: migrations/001_add_messages_and_assignments.sql"
echo "6. Paste into SQL Editor"
echo "7. Click 'Run' button"
echo ""
echo "✅ Migration creates:"
echo "   - messages table"
echo "   - assignments table"  
echo "   - assignment_submissions table"
echo "   - All RLS policies"
echo ""
echo "📄 Migration file:"
echo "   $(pwd)/migrations/001_add_messages_and_assignments.sql"
