name = "efh-autopilot-metrics"
main = "autopilot-metrics-durable.ts"
compatibility_date = "2024-01-01"

# Durable Object bindings
[[durable_objects.bindings]]
name = "AUTOPILOT_METRICS"
class_name = "AutopilotMetrics"
script_name = "efh-autopilot-metrics"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_classes = ["AutopilotMetrics"]

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# AUTOPILOT_TOKEN = "your-token-here"

# Routes
routes = [
  { pattern = "metrics.elevateforhumanity.org/*", zone_name = "elevateforhumanity.org" }
]

# Alternative: Use workers.dev subdomain
workers_dev = true
