name: Autopilot Deploy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.*'
      - 'index.html'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.7.0
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
    
    - name: 📥 Install dependencies
      run: pnpm install --frozen-lockfile=false
    
    - name: 🔧 Configure environment
      run: |
        cat > .env << EOF
        VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
        NODE_ENV=production
        EOF
        echo "✅ Environment configured"
    
    - name: 🏗️ Build application
      run: pnpm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    
    - name: 🚀 Deploy to Cloudflare Pages
      if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy dist --project-name=elevateforhumanity
    
    - name: 🔔 Trigger Render Deployment
      if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
        echo "✅ Render deployment triggered"
    
    - name: ✅ Deployment Summary
      run: |
        echo "╔════════════════════════════════════════════════════════════╗"
        echo "║              AUTOPILOT DEPLOYMENT COMPLETE! 🎉             ║"
        echo "╚════════════════════════════════════════════════════════════╝"
        echo ""
        echo "🌐 Cloudflare Pages: https://elevateforhumanity.pages.dev"
        echo "🌐 Render: https://elevateforhumanity.onrender.com"
        echo ""
        echo "✅ Build completed"
        echo "✅ Deployed to Cloudflare Pages"
        echo "✅ Triggered Render deployment"
