name: Autopilot Auto-Deploy

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
  workflow_dispatch:

env:
  AUTOPILOT_SECRET: ${{ secrets.AUTOPILOT_SECRET }}
  SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
  SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply migrations automatically
        run: |
          echo "🤖 Auto-applying all autopilot migrations..."
          for migration in supabase/migrations/202501*.sql; do
            if [[ -f "$migration" ]]; then
              echo "Applying: $migration"
              psql "$SUPABASE_DB_URL" -f "$migration" 2>&1 | grep -v "already exists" || true
            fi
          done
          echo "✅ All migrations applied"

      - name: Trigger Netlify build
        if: env.NETLIFY_BUILD_HOOK != ''
        run: |
          curl -X POST "$NETLIFY_BUILD_HOOK"
          echo "✅ Netlify build triggered"

      - name: Notify Slack
        if: env.SLACK_WEBHOOK_URL != '' && always()
        run: |
          STATUS="${{ job.status }}"
          EMOJI="✅"
          [[ "$STATUS" != "success" ]] && EMOJI="❌"

          curl -X POST "$SLACK_WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d "{\"text\":\"$EMOJI Autopilot Auto-Deploy $STATUS for commit ${{ github.sha }}\"}"
