name: Autopilot Comment Bridge

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  bridge:
    # Only run if comment starts with /
    if: startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Parse and forward command
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          
          # Create JSON payload
          PAYLOAD=$(jq -nc --arg t "$COMMENT_BODY" '{text:$t}')
          
          # Forward to autopilot bridge
          RESPONSE=$(curl -sS -X POST "${{ secrets.AUTOPILOT_BRIDGE_URL }}" \
            -H "Content-Type: application/json" \
            -H "x-bridge-sign: ${{ secrets.AUTOPILOT_SECRET }}" \
            -d "$PAYLOAD" \
            -w "\nHTTP_CODE:%{http_code}" \
            2>&1)
          
          HTTP_CODE=$(echo "$RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_CODE:/d')
          
          echo "Response Code: $HTTP_CODE"
          echo "Response Body: $BODY"
          
          # Post result as comment
          if [ "$HTTP_CODE" = "200" ]; then
            RESULT="✅ Command executed successfully\n\`\`\`json\n$BODY\n\`\`\`"
          else
            RESULT="❌ Command failed (HTTP $HTTP_CODE)\n\`\`\`json\n$BODY\n\`\`\`"
          fi
          
          # Use GitHub API to post comment
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.comment.issue_url || github.event.comment.pull_request_url }}/comments" \
            -d "{\"body\":\"$RESULT\"}"
      
      - name: Log command
        if: always()
        run: |
          echo "Command: ${{ github.event.comment.body }}"
          echo "User: ${{ github.event.comment.user.login }}"
          echo "Issue/PR: ${{ github.event.issue.number || github.event.pull_request.number }}"
