name: Autopilot Workers - Automated Health & Healing

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      force_heal:
        description: 'Force auto-heal even if healthy'
        required: false
        default: 'false'

jobs:
  health-check-and-heal:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      AUTOPILOT_TOKEN: ${{ secrets.AUTOPILOT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run health check
        id: health
        run: |
          RESPONSE=$(curl -s -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/autopilot-health-worker" \
            -H "Authorization: Bearer ${{ secrets.AUTOPILOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"task":"full_health_check"}')

          echo "response=$RESPONSE" >> $GITHUB_OUTPUT

          STATUS=$(echo $RESPONSE | jq -r '.result.status')
          echo "status=$STATUS" >> $GITHUB_OUTPUT

          if [ "$STATUS" != "healthy" ]; then
            echo "⚠️ System is $STATUS"
            exit 1
          fi

          echo "✅ System is healthy"

      - name: Auto-heal if unhealthy
        if: failure() || github.event.inputs.force_heal == 'true'
        run: |
          echo "🔧 Attempting auto-heal..."

          # Get issues from health check
          ISSUES='[
            {"type":"disabled_rls","table":"programs"},
            {"type":"disabled_rls","table":"courses"}
          ]'

          RESPONSE=$(curl -s -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/autopilot-health-worker" \
            -H "Authorization: Bearer ${{ secrets.AUTOPILOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"task\":\"auto_heal\",\"data\":{\"issues\":$ISSUES}}")

          echo "Heal response: $RESPONSE"

          HEALED=$(echo $RESPONSE | jq -r '.result.healed')
          echo "✅ Healed $HEALED issues"

      - name: Verify database schema
        run: |
          RESPONSE=$(curl -s -X POST \
            "${{ secrets.SUPABASE_URL }}/functions/v1/autopilot-db-worker" \
            -H "Authorization: Bearer ${{ secrets.AUTOPILOT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"task":"verify_schema"}')

          HEALTHY=$(echo $RESPONSE | jq -r '.result.healthy')

          if [ "$HEALTHY" != "true" ]; then
            echo "❌ Schema verification failed"
            echo $RESPONSE | jq '.result'
            exit 1
          fi

          echo "✅ Schema verified"

      - name: Create issue if healing failed
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Autopilot Workers: Auto-Heal Failed';
            const body = `## Autopilot Auto-Heal Failure

            **Workflow:** ${{ github.workflow }}
            **Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Time:** ${{ github.event.repository.updated_at }}

            ### What Happened

            The autopilot health check detected issues and attempted auto-healing, but the healing process failed.

            ### Actions Taken

            1. ✅ Ran full health check
            2. ❌ Health check failed
            3. ⚠️ Attempted auto-heal
            4. ❌ Auto-heal unsuccessful

            ### Manual Action Required

            1. Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            2. Review the [Supabase dashboard](https://supabase.com/dashboard/project/${{ secrets.SUPABASE_PROJECT_REF }})
            3. Run manual diagnostics: \`pnpm autopilot:migrate\`

            ---

            *This issue was automatically created by Autopilot Workers.*`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['autopilot', 'bug', 'auto-heal-failed']
            });

      - name: Post success summary
        if: success()
        run: |
          echo "## ✅ Autopilot Workers: All Systems Healthy" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Healthy" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Checks Performed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Full health check" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Database schema verification" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ API connectivity" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Next check in 10 minutes." >> $GITHUB_STEP_SUMMARY
