name: Close specific Dependabot PRs

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  close-dependabot-prs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - dependabot/npm_and_yarn/tailwindcss-4.1.14
          - dependabot/npm_and_yarn/react-19.2.0
          - dependabot/npm_and_yarn/sentry/react-10.19.0
          - dependabot/npm_and_yarn/vite-7.1.10
          - dependabot/npm_and_yarn/react-router-dom-7.9.4
    steps:
      - name: Close ${{ matrix.branch }}
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const headRef = `${owner}:${process.env.BRANCH}`;
            const commentBody = "Major version with breaking changes - will upgrade manually when ready";

            // Find open PR for this branch
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: "open", per_page: 100
            });

            const pr = prs.find(p => p.head && p.head.ref === process.env.BRANCH);
            if (!pr) {
              core.info(`No open PR found for ${process.env.BRANCH}. Skipping.`);
              return;
            }

            // Leave the comment
            await github.rest.issues.createComment({
              owner, repo, issue_number: pr.number, body: commentBody
            });

            // Optionally add a label
            try {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: pr.number, labels: ["blocked", "manual-upgrade"]
              });
            } catch (e) {
              core.info("Could not add labels (may not exist). Continuing.");
            }

            // Close the PR
            await github.rest.pulls.update({
              owner, repo, pull_number: pr.number, state: "closed"
            });

            core.info(`Closed PR #${pr.number} (${process.env.BRANCH}).`);
        env:
          BRANCH: ${{ matrix.branch }}
