name: Daily Content Generation

on:
  schedule:
    # Run every day at 6 AM EST (11 AM UTC)
    - cron: '0 11 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to generate'
        required: false
        default: '7'

jobs:
  generate-content:
    runs-on: ubuntu-latest
    name: Generate Social Media Content
    
    steps:
      - name: Generate content for next 7 days
        run: |
          curl -X POST ${{ secrets.FRONTEND_URL }}/.netlify/functions/generate-content-calendar \
            -H "Content-Type: application/json" \
            -d '{
              "days": ${{ github.event.inputs.days || 7 }},
              "programs": ["Tax Business", "Barber", "Building Tech", "Healthcare"]
            }'
      
      - name: Notify on success
        if: success()
        run: |
          echo "✅ Content generated successfully for next ${{ github.event.inputs.days || 7 }} days"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Content generation failed"
          # TODO: Send Slack notification
