name: System Health Check

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    name: Check System Health

    steps:
      - name: Run health check
        id: health
        run: |
          response=$(curl -s -w "\n%{http_code}" ${{ secrets.FRONTEND_URL }}/.netlify/functions/health-check)
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "HTTP Status: $http_code"
          echo "$body" | jq '.'

          if [ "$http_code" != "200" ]; then
            echo "::error::Health check failed with status $http_code"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "🚨 Health check failed - alerts sent via Slack"
