name: Netlify Build Monitor

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript check
        run: pnpm run typecheck

      - name: ESLint check
        run: pnpm run lint

      - name: Build test
        run: CI=true pnpm run build

      - name: Report success
        if: success()
        run: |
          echo "✅ All checks passing - Netlify builds will succeed" >> $GITHUB_STEP_SUMMARY
